// Code generated by Fern. DO NOT EDIT.

package client

import (
	agents "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/agents"
	core "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/core"
	internal "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/internal"
	option "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/option"
	phonenumbers "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/phonenumbers"
	telephony "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/telephony"
	os "os"
)

type Client struct {
	Agents       *agents.Client
	Telephony    *telephony.Client
	PhoneNumbers *phonenumbers.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	if options.AuthToken == "" {
		options.AuthToken = os.Getenv("AGORA_AUTH_TOKEN")
	}
	return &Client{
		Agents:       agents.NewClient(options),
		Telephony:    telephony.NewClient(options),
		PhoneNumbers: phonenumbers.NewClient(options),
		options:      options,
		baseURL:      options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
