// Code generated by Fern. DO NOT EDIT.

package client

import (
	agents "github.com/fern-demo/agoraio-go-sdk/v505/agents"
	core "github.com/fern-demo/agoraio-go-sdk/v505/core"
	internal "github.com/fern-demo/agoraio-go-sdk/v505/internal"
	option "github.com/fern-demo/agoraio-go-sdk/v505/option"
	phonenumbers "github.com/fern-demo/agoraio-go-sdk/v505/phonenumbers"
	telephony "github.com/fern-demo/agoraio-go-sdk/v505/telephony"
)

type Client struct {
	Agents       *agents.Client
	Telephony    *telephony.Client
	PhoneNumbers *phonenumbers.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Agents:       agents.NewClient(options),
		Telephony:    telephony.NewClient(options),
		PhoneNumbers: phonenumbers.NewClient(options),
		options:      options,
		baseURL:      options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
