// Code generated by Fern. DO NOT EDIT.

package Agora

// Environments defines all of the API environments.
// These values can be used with the WithBaseURL
// RequestOption to override the client's default environment,
// if any.
var Environments = struct {
	Default string
}{
	Default: "https://api.agora.io/api/conversational-ai-agent",
}
