// Code generated by Fern. DO NOT EDIT.

package Agora

import (
	internal "github.com/AgoraIO-Conversational-AI/agora-agent-go-sdk/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{}
