// Code generated by Fern. DO NOT EDIT.

package Agora

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/fern-demo/agoraio-go-sdk/v505/internal"
	big "math/big"
)

var (
	addPhoneNumberManagementRequestFieldProvider       = big.NewInt(1 << 0)
	addPhoneNumberManagementRequestFieldPhoneNumber    = big.NewInt(1 << 1)
	addPhoneNumberManagementRequestFieldLabel          = big.NewInt(1 << 2)
	addPhoneNumberManagementRequestFieldInbound        = big.NewInt(1 << 3)
	addPhoneNumberManagementRequestFieldOutbound       = big.NewInt(1 << 4)
	addPhoneNumberManagementRequestFieldInboundConfig  = big.NewInt(1 << 5)
	addPhoneNumberManagementRequestFieldOutboundConfig = big.NewInt(1 << 6)
)

type AddPhoneNumberManagementRequest struct {
	// Number provider:
	// - `byo`: BYO (Bring Your Own)
	// - `twilio`: Twilio
	Provider AddPhoneNumberManagementRequestProvider `json:"provider" url:"-"`
	// Telephone number in E.164 format.
	PhoneNumber string `json:"phone_number" url:"-"`
	// A label used to identify the number.
	Label string `json:"label" url:"-"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"-"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"-"`
	// SIP inbound call configuration.
	InboundConfig *AddPhoneNumberManagementRequestInboundConfig `json:"inbound_config,omitempty" url:"-"`
	// SIP outbound call configuration.
	OutboundConfig *AddPhoneNumberManagementRequestOutboundConfig `json:"outbound_config,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AddPhoneNumberManagementRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementRequest) SetProvider(provider AddPhoneNumberManagementRequestProvider) {
	a.Provider = provider
	a.require(addPhoneNumberManagementRequestFieldProvider)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementRequest) SetPhoneNumber(phoneNumber string) {
	a.PhoneNumber = phoneNumber
	a.require(addPhoneNumberManagementRequestFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementRequest) SetLabel(label string) {
	a.Label = label
	a.require(addPhoneNumberManagementRequestFieldLabel)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementRequest) SetInbound(inbound *bool) {
	a.Inbound = inbound
	a.require(addPhoneNumberManagementRequestFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementRequest) SetOutbound(outbound *bool) {
	a.Outbound = outbound
	a.require(addPhoneNumberManagementRequestFieldOutbound)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementRequest) SetInboundConfig(inboundConfig *AddPhoneNumberManagementRequestInboundConfig) {
	a.InboundConfig = inboundConfig
	a.require(addPhoneNumberManagementRequestFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementRequest) SetOutboundConfig(outboundConfig *AddPhoneNumberManagementRequestOutboundConfig) {
	a.OutboundConfig = outboundConfig
	a.require(addPhoneNumberManagementRequestFieldOutboundConfig)
}

var (
	deletePhoneNumberManagementRequestFieldPhoneNumber = big.NewInt(1 << 0)
)

type DeletePhoneNumberManagementRequest struct {
	// Telephone number in E.164 format. For example, +11234567890.
	PhoneNumber string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeletePhoneNumberManagementRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePhoneNumberManagementRequest) SetPhoneNumber(phoneNumber string) {
	d.PhoneNumber = phoneNumber
	d.require(deletePhoneNumberManagementRequestFieldPhoneNumber)
}

var (
	getPhoneNumberManagementRequestFieldPhoneNumber = big.NewInt(1 << 0)
)

type GetPhoneNumberManagementRequest struct {
	// Telephone number in E.164 format. For example, +11234567890.
	PhoneNumber string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPhoneNumberManagementRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumberManagementRequest) SetPhoneNumber(phoneNumber string) {
	g.PhoneNumber = phoneNumber
	g.require(getPhoneNumberManagementRequestFieldPhoneNumber)
}

// SIP inbound call configuration.
var (
	addPhoneNumberManagementRequestInboundConfigFieldAllowedAddresses = big.NewInt(1 << 0)
)

type AddPhoneNumberManagementRequestInboundConfig struct {
	// List of allowed IP addresses. For example `112.126.15.64/27`
	AllowedAddresses []string `json:"allowed_addresses,omitempty" url:"allowed_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AddPhoneNumberManagementRequestInboundConfig) GetAllowedAddresses() []string {
	if a == nil {
		return nil
	}
	return a.AllowedAddresses
}

func (a *AddPhoneNumberManagementRequestInboundConfig) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AddPhoneNumberManagementRequestInboundConfig) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetAllowedAddresses sets the AllowedAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementRequestInboundConfig) SetAllowedAddresses(allowedAddresses []string) {
	a.AllowedAddresses = allowedAddresses
	a.require(addPhoneNumberManagementRequestInboundConfigFieldAllowedAddresses)
}

func (a *AddPhoneNumberManagementRequestInboundConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler AddPhoneNumberManagementRequestInboundConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AddPhoneNumberManagementRequestInboundConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AddPhoneNumberManagementRequestInboundConfig) MarshalJSON() ([]byte, error) {
	type embed AddPhoneNumberManagementRequestInboundConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AddPhoneNumberManagementRequestInboundConfig) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// SIP outbound call configuration.
var (
	addPhoneNumberManagementRequestOutboundConfigFieldAddress   = big.NewInt(1 << 0)
	addPhoneNumberManagementRequestOutboundConfigFieldTransport = big.NewInt(1 << 1)
	addPhoneNumberManagementRequestOutboundConfigFieldPrefix    = big.NewInt(1 << 2)
)

type AddPhoneNumberManagementRequestOutboundConfig struct {
	// SIP address. For example `xxx:xxx@sip.example.com`
	Address *string `json:"address,omitempty" url:"address,omitempty"`
	// Transport protocol. For example `tls`
	Transport *string `json:"transport,omitempty" url:"transport,omitempty"`
	// Number prefix. For example `6036`
	Prefix *string `json:"prefix,omitempty" url:"prefix,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AddPhoneNumberManagementRequestOutboundConfig) GetAddress() *string {
	if a == nil {
		return nil
	}
	return a.Address
}

func (a *AddPhoneNumberManagementRequestOutboundConfig) GetTransport() *string {
	if a == nil {
		return nil
	}
	return a.Transport
}

func (a *AddPhoneNumberManagementRequestOutboundConfig) GetPrefix() *string {
	if a == nil {
		return nil
	}
	return a.Prefix
}

func (a *AddPhoneNumberManagementRequestOutboundConfig) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AddPhoneNumberManagementRequestOutboundConfig) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementRequestOutboundConfig) SetAddress(address *string) {
	a.Address = address
	a.require(addPhoneNumberManagementRequestOutboundConfigFieldAddress)
}

// SetTransport sets the Transport field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementRequestOutboundConfig) SetTransport(transport *string) {
	a.Transport = transport
	a.require(addPhoneNumberManagementRequestOutboundConfigFieldTransport)
}

// SetPrefix sets the Prefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementRequestOutboundConfig) SetPrefix(prefix *string) {
	a.Prefix = prefix
	a.require(addPhoneNumberManagementRequestOutboundConfigFieldPrefix)
}

func (a *AddPhoneNumberManagementRequestOutboundConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler AddPhoneNumberManagementRequestOutboundConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AddPhoneNumberManagementRequestOutboundConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AddPhoneNumberManagementRequestOutboundConfig) MarshalJSON() ([]byte, error) {
	type embed AddPhoneNumberManagementRequestOutboundConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AddPhoneNumberManagementRequestOutboundConfig) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// Number provider:
// - `byo`: BYO (Bring Your Own)
// - `twilio`: Twilio
type AddPhoneNumberManagementRequestProvider string

const (
	AddPhoneNumberManagementRequestProviderByo    AddPhoneNumberManagementRequestProvider = "byo"
	AddPhoneNumberManagementRequestProviderTwilio AddPhoneNumberManagementRequestProvider = "twilio"
)

func NewAddPhoneNumberManagementRequestProviderFromString(s string) (AddPhoneNumberManagementRequestProvider, error) {
	switch s {
	case "byo":
		return AddPhoneNumberManagementRequestProviderByo, nil
	case "twilio":
		return AddPhoneNumberManagementRequestProviderTwilio, nil
	}
	var t AddPhoneNumberManagementRequestProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AddPhoneNumberManagementRequestProvider) Ptr() *AddPhoneNumberManagementRequestProvider {
	return &a
}

var (
	addPhoneNumberManagementResponseFieldPhoneNumber        = big.NewInt(1 << 0)
	addPhoneNumberManagementResponseFieldLabel              = big.NewInt(1 << 1)
	addPhoneNumberManagementResponseFieldProvider           = big.NewInt(1 << 2)
	addPhoneNumberManagementResponseFieldInbound            = big.NewInt(1 << 3)
	addPhoneNumberManagementResponseFieldOutbound           = big.NewInt(1 << 4)
	addPhoneNumberManagementResponseFieldAssociatedPipeline = big.NewInt(1 << 5)
)

type AddPhoneNumberManagementResponse struct {
	// A telephone number in E.164 format, used as a unique identifier.
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	// A label used to identify the number.
	Label *string `json:"label,omitempty" url:"label,omitempty"`
	// Number provider.
	Provider *string `json:"provider,omitempty" url:"provider,omitempty"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"inbound,omitempty"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"outbound,omitempty"`
	// The associated pipeline information. Returns `null` if no pipeline is associated.
	AssociatedPipeline *AddPhoneNumberManagementResponseAssociatedPipeline `json:"associated_pipeline,omitempty" url:"associated_pipeline,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AddPhoneNumberManagementResponse) GetPhoneNumber() *string {
	if a == nil {
		return nil
	}
	return a.PhoneNumber
}

func (a *AddPhoneNumberManagementResponse) GetLabel() *string {
	if a == nil {
		return nil
	}
	return a.Label
}

func (a *AddPhoneNumberManagementResponse) GetProvider() *string {
	if a == nil {
		return nil
	}
	return a.Provider
}

func (a *AddPhoneNumberManagementResponse) GetInbound() *bool {
	if a == nil {
		return nil
	}
	return a.Inbound
}

func (a *AddPhoneNumberManagementResponse) GetOutbound() *bool {
	if a == nil {
		return nil
	}
	return a.Outbound
}

func (a *AddPhoneNumberManagementResponse) GetAssociatedPipeline() *AddPhoneNumberManagementResponseAssociatedPipeline {
	if a == nil {
		return nil
	}
	return a.AssociatedPipeline
}

func (a *AddPhoneNumberManagementResponse) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AddPhoneNumberManagementResponse) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementResponse) SetPhoneNumber(phoneNumber *string) {
	a.PhoneNumber = phoneNumber
	a.require(addPhoneNumberManagementResponseFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementResponse) SetLabel(label *string) {
	a.Label = label
	a.require(addPhoneNumberManagementResponseFieldLabel)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementResponse) SetProvider(provider *string) {
	a.Provider = provider
	a.require(addPhoneNumberManagementResponseFieldProvider)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementResponse) SetInbound(inbound *bool) {
	a.Inbound = inbound
	a.require(addPhoneNumberManagementResponseFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementResponse) SetOutbound(outbound *bool) {
	a.Outbound = outbound
	a.require(addPhoneNumberManagementResponseFieldOutbound)
}

// SetAssociatedPipeline sets the AssociatedPipeline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementResponse) SetAssociatedPipeline(associatedPipeline *AddPhoneNumberManagementResponseAssociatedPipeline) {
	a.AssociatedPipeline = associatedPipeline
	a.require(addPhoneNumberManagementResponseFieldAssociatedPipeline)
}

func (a *AddPhoneNumberManagementResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler AddPhoneNumberManagementResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AddPhoneNumberManagementResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AddPhoneNumberManagementResponse) MarshalJSON() ([]byte, error) {
	type embed AddPhoneNumberManagementResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AddPhoneNumberManagementResponse) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// The associated pipeline information. Returns `null` if no pipeline is associated.
var (
	addPhoneNumberManagementResponseAssociatedPipelineFieldPipelineID   = big.NewInt(1 << 0)
	addPhoneNumberManagementResponseAssociatedPipelineFieldPipelineName = big.NewInt(1 << 1)
)

type AddPhoneNumberManagementResponseAssociatedPipeline struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Pipeline name.
	PipelineName *string `json:"pipeline_name,omitempty" url:"pipeline_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AddPhoneNumberManagementResponseAssociatedPipeline) GetPipelineID() *string {
	if a == nil {
		return nil
	}
	return a.PipelineID
}

func (a *AddPhoneNumberManagementResponseAssociatedPipeline) GetPipelineName() *string {
	if a == nil {
		return nil
	}
	return a.PipelineName
}

func (a *AddPhoneNumberManagementResponseAssociatedPipeline) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AddPhoneNumberManagementResponseAssociatedPipeline) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementResponseAssociatedPipeline) SetPipelineID(pipelineID *string) {
	a.PipelineID = pipelineID
	a.require(addPhoneNumberManagementResponseAssociatedPipelineFieldPipelineID)
}

// SetPipelineName sets the PipelineName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumberManagementResponseAssociatedPipeline) SetPipelineName(pipelineName *string) {
	a.PipelineName = pipelineName
	a.require(addPhoneNumberManagementResponseAssociatedPipelineFieldPipelineName)
}

func (a *AddPhoneNumberManagementResponseAssociatedPipeline) UnmarshalJSON(data []byte) error {
	type unmarshaler AddPhoneNumberManagementResponseAssociatedPipeline
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AddPhoneNumberManagementResponseAssociatedPipeline(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AddPhoneNumberManagementResponseAssociatedPipeline) MarshalJSON() ([]byte, error) {
	type embed AddPhoneNumberManagementResponseAssociatedPipeline
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AddPhoneNumberManagementResponseAssociatedPipeline) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	getPhoneNumberManagementResponseFieldProvider           = big.NewInt(1 << 0)
	getPhoneNumberManagementResponseFieldPhoneNumber        = big.NewInt(1 << 1)
	getPhoneNumberManagementResponseFieldLabel              = big.NewInt(1 << 2)
	getPhoneNumberManagementResponseFieldInbound            = big.NewInt(1 << 3)
	getPhoneNumberManagementResponseFieldOutbound           = big.NewInt(1 << 4)
	getPhoneNumberManagementResponseFieldAssociatedPipeline = big.NewInt(1 << 5)
	getPhoneNumberManagementResponseFieldInboundConfig      = big.NewInt(1 << 6)
	getPhoneNumberManagementResponseFieldOutboundConfig     = big.NewInt(1 << 7)
)

type GetPhoneNumberManagementResponse struct {
	// Number provider:
	// - `byo`: BYO (Bring Your Own)
	// - `twilio`: Twilio
	Provider *GetPhoneNumberManagementResponseProvider `json:"provider,omitempty" url:"provider,omitempty"`
	// A telephone number in E.164 format, used as a unique identifier.
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	// A label used to identify the number.
	Label *string `json:"label,omitempty" url:"label,omitempty"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"inbound,omitempty"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"outbound,omitempty"`
	// The associated pipeline information. Returns `null` if no pipeline is associated.
	AssociatedPipeline *GetPhoneNumberManagementResponseAssociatedPipeline `json:"associated_pipeline,omitempty" url:"associated_pipeline,omitempty"`
	// SIP inbound call configuration details. Returns `null` if not configured.
	InboundConfig map[string]interface{} `json:"inbound_config,omitempty" url:"inbound_config,omitempty"`
	// SIP outbound call configuration details. Returns `null` if not configured.
	OutboundConfig map[string]interface{} `json:"outbound_config,omitempty" url:"outbound_config,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetPhoneNumberManagementResponse) GetProvider() *GetPhoneNumberManagementResponseProvider {
	if g == nil {
		return nil
	}
	return g.Provider
}

func (g *GetPhoneNumberManagementResponse) GetPhoneNumber() *string {
	if g == nil {
		return nil
	}
	return g.PhoneNumber
}

func (g *GetPhoneNumberManagementResponse) GetLabel() *string {
	if g == nil {
		return nil
	}
	return g.Label
}

func (g *GetPhoneNumberManagementResponse) GetInbound() *bool {
	if g == nil {
		return nil
	}
	return g.Inbound
}

func (g *GetPhoneNumberManagementResponse) GetOutbound() *bool {
	if g == nil {
		return nil
	}
	return g.Outbound
}

func (g *GetPhoneNumberManagementResponse) GetAssociatedPipeline() *GetPhoneNumberManagementResponseAssociatedPipeline {
	if g == nil {
		return nil
	}
	return g.AssociatedPipeline
}

func (g *GetPhoneNumberManagementResponse) GetInboundConfig() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.InboundConfig
}

func (g *GetPhoneNumberManagementResponse) GetOutboundConfig() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.OutboundConfig
}

func (g *GetPhoneNumberManagementResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetPhoneNumberManagementResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumberManagementResponse) SetProvider(provider *GetPhoneNumberManagementResponseProvider) {
	g.Provider = provider
	g.require(getPhoneNumberManagementResponseFieldProvider)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumberManagementResponse) SetPhoneNumber(phoneNumber *string) {
	g.PhoneNumber = phoneNumber
	g.require(getPhoneNumberManagementResponseFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumberManagementResponse) SetLabel(label *string) {
	g.Label = label
	g.require(getPhoneNumberManagementResponseFieldLabel)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumberManagementResponse) SetInbound(inbound *bool) {
	g.Inbound = inbound
	g.require(getPhoneNumberManagementResponseFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumberManagementResponse) SetOutbound(outbound *bool) {
	g.Outbound = outbound
	g.require(getPhoneNumberManagementResponseFieldOutbound)
}

// SetAssociatedPipeline sets the AssociatedPipeline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumberManagementResponse) SetAssociatedPipeline(associatedPipeline *GetPhoneNumberManagementResponseAssociatedPipeline) {
	g.AssociatedPipeline = associatedPipeline
	g.require(getPhoneNumberManagementResponseFieldAssociatedPipeline)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumberManagementResponse) SetInboundConfig(inboundConfig map[string]interface{}) {
	g.InboundConfig = inboundConfig
	g.require(getPhoneNumberManagementResponseFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumberManagementResponse) SetOutboundConfig(outboundConfig map[string]interface{}) {
	g.OutboundConfig = outboundConfig
	g.require(getPhoneNumberManagementResponseFieldOutboundConfig)
}

func (g *GetPhoneNumberManagementResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPhoneNumberManagementResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetPhoneNumberManagementResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetPhoneNumberManagementResponse) MarshalJSON() ([]byte, error) {
	type embed GetPhoneNumberManagementResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetPhoneNumberManagementResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// The associated pipeline information. Returns `null` if no pipeline is associated.
var (
	getPhoneNumberManagementResponseAssociatedPipelineFieldPipelineID   = big.NewInt(1 << 0)
	getPhoneNumberManagementResponseAssociatedPipelineFieldPipelineName = big.NewInt(1 << 1)
)

type GetPhoneNumberManagementResponseAssociatedPipeline struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Pipeline name.
	PipelineName *string `json:"pipeline_name,omitempty" url:"pipeline_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetPhoneNumberManagementResponseAssociatedPipeline) GetPipelineID() *string {
	if g == nil {
		return nil
	}
	return g.PipelineID
}

func (g *GetPhoneNumberManagementResponseAssociatedPipeline) GetPipelineName() *string {
	if g == nil {
		return nil
	}
	return g.PipelineName
}

func (g *GetPhoneNumberManagementResponseAssociatedPipeline) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetPhoneNumberManagementResponseAssociatedPipeline) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumberManagementResponseAssociatedPipeline) SetPipelineID(pipelineID *string) {
	g.PipelineID = pipelineID
	g.require(getPhoneNumberManagementResponseAssociatedPipelineFieldPipelineID)
}

// SetPipelineName sets the PipelineName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumberManagementResponseAssociatedPipeline) SetPipelineName(pipelineName *string) {
	g.PipelineName = pipelineName
	g.require(getPhoneNumberManagementResponseAssociatedPipelineFieldPipelineName)
}

func (g *GetPhoneNumberManagementResponseAssociatedPipeline) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPhoneNumberManagementResponseAssociatedPipeline
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetPhoneNumberManagementResponseAssociatedPipeline(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetPhoneNumberManagementResponseAssociatedPipeline) MarshalJSON() ([]byte, error) {
	type embed GetPhoneNumberManagementResponseAssociatedPipeline
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetPhoneNumberManagementResponseAssociatedPipeline) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Number provider:
// - `byo`: BYO (Bring Your Own)
// - `twilio`: Twilio
type GetPhoneNumberManagementResponseProvider string

const (
	GetPhoneNumberManagementResponseProviderByo    GetPhoneNumberManagementResponseProvider = "byo"
	GetPhoneNumberManagementResponseProviderTwilio GetPhoneNumberManagementResponseProvider = "twilio"
)

func NewGetPhoneNumberManagementResponseProviderFromString(s string) (GetPhoneNumberManagementResponseProvider, error) {
	switch s {
	case "byo":
		return GetPhoneNumberManagementResponseProviderByo, nil
	case "twilio":
		return GetPhoneNumberManagementResponseProviderTwilio, nil
	}
	var t GetPhoneNumberManagementResponseProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetPhoneNumberManagementResponseProvider) Ptr() *GetPhoneNumberManagementResponseProvider {
	return &g
}

var (
	listPhoneNumberManagementResponseItemFieldProvider           = big.NewInt(1 << 0)
	listPhoneNumberManagementResponseItemFieldPhoneNumber        = big.NewInt(1 << 1)
	listPhoneNumberManagementResponseItemFieldLabel              = big.NewInt(1 << 2)
	listPhoneNumberManagementResponseItemFieldInbound            = big.NewInt(1 << 3)
	listPhoneNumberManagementResponseItemFieldOutbound           = big.NewInt(1 << 4)
	listPhoneNumberManagementResponseItemFieldAssociatedPipeline = big.NewInt(1 << 5)
	listPhoneNumberManagementResponseItemFieldInboundConfig      = big.NewInt(1 << 6)
	listPhoneNumberManagementResponseItemFieldOutboundConfig     = big.NewInt(1 << 7)
)

type ListPhoneNumberManagementResponseItem struct {
	// Number provider:
	// - `byo`: BYO (Bring Your Own).
	// - `twilio`: Twilio.
	Provider *ListPhoneNumberManagementResponseItemProvider `json:"provider,omitempty" url:"provider,omitempty"`
	// A telephone number in E.164 format, used as a unique identifier.
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	// A label used to identify the number.
	Label *string `json:"label,omitempty" url:"label,omitempty"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"inbound,omitempty"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"outbound,omitempty"`
	// The associated pipeline information. Returns `null` if no pipeline is associated.
	AssociatedPipeline *ListPhoneNumberManagementResponseItemAssociatedPipeline `json:"associated_pipeline,omitempty" url:"associated_pipeline,omitempty"`
	// SIP inbound call configuration details. Returns `null` if not configured.
	InboundConfig map[string]interface{} `json:"inbound_config,omitempty" url:"inbound_config,omitempty"`
	// SIP outbound call configuration details. Returns `null` if not configured.
	OutboundConfig map[string]interface{} `json:"outbound_config,omitempty" url:"outbound_config,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListPhoneNumberManagementResponseItem) GetProvider() *ListPhoneNumberManagementResponseItemProvider {
	if l == nil {
		return nil
	}
	return l.Provider
}

func (l *ListPhoneNumberManagementResponseItem) GetPhoneNumber() *string {
	if l == nil {
		return nil
	}
	return l.PhoneNumber
}

func (l *ListPhoneNumberManagementResponseItem) GetLabel() *string {
	if l == nil {
		return nil
	}
	return l.Label
}

func (l *ListPhoneNumberManagementResponseItem) GetInbound() *bool {
	if l == nil {
		return nil
	}
	return l.Inbound
}

func (l *ListPhoneNumberManagementResponseItem) GetOutbound() *bool {
	if l == nil {
		return nil
	}
	return l.Outbound
}

func (l *ListPhoneNumberManagementResponseItem) GetAssociatedPipeline() *ListPhoneNumberManagementResponseItemAssociatedPipeline {
	if l == nil {
		return nil
	}
	return l.AssociatedPipeline
}

func (l *ListPhoneNumberManagementResponseItem) GetInboundConfig() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.InboundConfig
}

func (l *ListPhoneNumberManagementResponseItem) GetOutboundConfig() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.OutboundConfig
}

func (l *ListPhoneNumberManagementResponseItem) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListPhoneNumberManagementResponseItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumberManagementResponseItem) SetProvider(provider *ListPhoneNumberManagementResponseItemProvider) {
	l.Provider = provider
	l.require(listPhoneNumberManagementResponseItemFieldProvider)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumberManagementResponseItem) SetPhoneNumber(phoneNumber *string) {
	l.PhoneNumber = phoneNumber
	l.require(listPhoneNumberManagementResponseItemFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumberManagementResponseItem) SetLabel(label *string) {
	l.Label = label
	l.require(listPhoneNumberManagementResponseItemFieldLabel)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumberManagementResponseItem) SetInbound(inbound *bool) {
	l.Inbound = inbound
	l.require(listPhoneNumberManagementResponseItemFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumberManagementResponseItem) SetOutbound(outbound *bool) {
	l.Outbound = outbound
	l.require(listPhoneNumberManagementResponseItemFieldOutbound)
}

// SetAssociatedPipeline sets the AssociatedPipeline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumberManagementResponseItem) SetAssociatedPipeline(associatedPipeline *ListPhoneNumberManagementResponseItemAssociatedPipeline) {
	l.AssociatedPipeline = associatedPipeline
	l.require(listPhoneNumberManagementResponseItemFieldAssociatedPipeline)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumberManagementResponseItem) SetInboundConfig(inboundConfig map[string]interface{}) {
	l.InboundConfig = inboundConfig
	l.require(listPhoneNumberManagementResponseItemFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumberManagementResponseItem) SetOutboundConfig(outboundConfig map[string]interface{}) {
	l.OutboundConfig = outboundConfig
	l.require(listPhoneNumberManagementResponseItemFieldOutboundConfig)
}

func (l *ListPhoneNumberManagementResponseItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListPhoneNumberManagementResponseItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListPhoneNumberManagementResponseItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListPhoneNumberManagementResponseItem) MarshalJSON() ([]byte, error) {
	type embed ListPhoneNumberManagementResponseItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListPhoneNumberManagementResponseItem) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// The associated pipeline information. Returns `null` if no pipeline is associated.
var (
	listPhoneNumberManagementResponseItemAssociatedPipelineFieldPipelineID   = big.NewInt(1 << 0)
	listPhoneNumberManagementResponseItemAssociatedPipelineFieldPipelineName = big.NewInt(1 << 1)
)

type ListPhoneNumberManagementResponseItemAssociatedPipeline struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Pipeline name.
	PipelineName *string `json:"pipeline_name,omitempty" url:"pipeline_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListPhoneNumberManagementResponseItemAssociatedPipeline) GetPipelineID() *string {
	if l == nil {
		return nil
	}
	return l.PipelineID
}

func (l *ListPhoneNumberManagementResponseItemAssociatedPipeline) GetPipelineName() *string {
	if l == nil {
		return nil
	}
	return l.PipelineName
}

func (l *ListPhoneNumberManagementResponseItemAssociatedPipeline) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListPhoneNumberManagementResponseItemAssociatedPipeline) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumberManagementResponseItemAssociatedPipeline) SetPipelineID(pipelineID *string) {
	l.PipelineID = pipelineID
	l.require(listPhoneNumberManagementResponseItemAssociatedPipelineFieldPipelineID)
}

// SetPipelineName sets the PipelineName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumberManagementResponseItemAssociatedPipeline) SetPipelineName(pipelineName *string) {
	l.PipelineName = pipelineName
	l.require(listPhoneNumberManagementResponseItemAssociatedPipelineFieldPipelineName)
}

func (l *ListPhoneNumberManagementResponseItemAssociatedPipeline) UnmarshalJSON(data []byte) error {
	type unmarshaler ListPhoneNumberManagementResponseItemAssociatedPipeline
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListPhoneNumberManagementResponseItemAssociatedPipeline(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListPhoneNumberManagementResponseItemAssociatedPipeline) MarshalJSON() ([]byte, error) {
	type embed ListPhoneNumberManagementResponseItemAssociatedPipeline
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListPhoneNumberManagementResponseItemAssociatedPipeline) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// Number provider:
// - `byo`: BYO (Bring Your Own).
// - `twilio`: Twilio.
type ListPhoneNumberManagementResponseItemProvider string

const (
	ListPhoneNumberManagementResponseItemProviderByo    ListPhoneNumberManagementResponseItemProvider = "byo"
	ListPhoneNumberManagementResponseItemProviderTwilio ListPhoneNumberManagementResponseItemProvider = "twilio"
)

func NewListPhoneNumberManagementResponseItemProviderFromString(s string) (ListPhoneNumberManagementResponseItemProvider, error) {
	switch s {
	case "byo":
		return ListPhoneNumberManagementResponseItemProviderByo, nil
	case "twilio":
		return ListPhoneNumberManagementResponseItemProviderTwilio, nil
	}
	var t ListPhoneNumberManagementResponseItemProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListPhoneNumberManagementResponseItemProvider) Ptr() *ListPhoneNumberManagementResponseItemProvider {
	return &l
}

// Update inbound call configuration. Passing `null` will clear the configuration.
var (
	updatePhoneNumberManagementRequestInboundConfigFieldPipelineID = big.NewInt(1 << 0)
)

type UpdatePhoneNumberManagementRequestInboundConfig struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdatePhoneNumberManagementRequestInboundConfig) GetPipelineID() *string {
	if u == nil {
		return nil
	}
	return u.PipelineID
}

func (u *UpdatePhoneNumberManagementRequestInboundConfig) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdatePhoneNumberManagementRequestInboundConfig) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumberManagementRequestInboundConfig) SetPipelineID(pipelineID *string) {
	u.PipelineID = pipelineID
	u.require(updatePhoneNumberManagementRequestInboundConfigFieldPipelineID)
}

func (u *UpdatePhoneNumberManagementRequestInboundConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePhoneNumberManagementRequestInboundConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdatePhoneNumberManagementRequestInboundConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdatePhoneNumberManagementRequestInboundConfig) MarshalJSON() ([]byte, error) {
	type embed UpdatePhoneNumberManagementRequestInboundConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdatePhoneNumberManagementRequestInboundConfig) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// Update outbound call configuration. Passing `null` will clear the configuration.
var (
	updatePhoneNumberManagementRequestOutboundConfigFieldPipelineID = big.NewInt(1 << 0)
)

type UpdatePhoneNumberManagementRequestOutboundConfig struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdatePhoneNumberManagementRequestOutboundConfig) GetPipelineID() *string {
	if u == nil {
		return nil
	}
	return u.PipelineID
}

func (u *UpdatePhoneNumberManagementRequestOutboundConfig) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdatePhoneNumberManagementRequestOutboundConfig) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumberManagementRequestOutboundConfig) SetPipelineID(pipelineID *string) {
	u.PipelineID = pipelineID
	u.require(updatePhoneNumberManagementRequestOutboundConfigFieldPipelineID)
}

func (u *UpdatePhoneNumberManagementRequestOutboundConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePhoneNumberManagementRequestOutboundConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdatePhoneNumberManagementRequestOutboundConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdatePhoneNumberManagementRequestOutboundConfig) MarshalJSON() ([]byte, error) {
	type embed UpdatePhoneNumberManagementRequestOutboundConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdatePhoneNumberManagementRequestOutboundConfig) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updatePhoneNumberManagementResponseFieldProvider           = big.NewInt(1 << 0)
	updatePhoneNumberManagementResponseFieldPhoneNumber        = big.NewInt(1 << 1)
	updatePhoneNumberManagementResponseFieldLabel              = big.NewInt(1 << 2)
	updatePhoneNumberManagementResponseFieldInbound            = big.NewInt(1 << 3)
	updatePhoneNumberManagementResponseFieldOutbound           = big.NewInt(1 << 4)
	updatePhoneNumberManagementResponseFieldAssociatedPipeline = big.NewInt(1 << 5)
	updatePhoneNumberManagementResponseFieldInboundConfig      = big.NewInt(1 << 6)
	updatePhoneNumberManagementResponseFieldOutboundConfig     = big.NewInt(1 << 7)
)

type UpdatePhoneNumberManagementResponse struct {
	// Number provider:
	// - `byo`: BYO (Bring Your Own)
	// - `twilio`: Twilio
	Provider *UpdatePhoneNumberManagementResponseProvider `json:"provider,omitempty" url:"provider,omitempty"`
	// A telephone number in E.164 format, used as a unique identifier.
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	// A label used to identify the number.
	Label *string `json:"label,omitempty" url:"label,omitempty"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"inbound,omitempty"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"outbound,omitempty"`
	// The associated pipeline information. Returns `null` if no pipeline is associated.
	AssociatedPipeline *UpdatePhoneNumberManagementResponseAssociatedPipeline `json:"associated_pipeline,omitempty" url:"associated_pipeline,omitempty"`
	// SIP inbound call configuration details. Returns `null` if not configured.
	InboundConfig map[string]interface{} `json:"inbound_config,omitempty" url:"inbound_config,omitempty"`
	// SIP outbound call configuration details. Returns `null` if not configured.
	OutboundConfig map[string]interface{} `json:"outbound_config,omitempty" url:"outbound_config,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdatePhoneNumberManagementResponse) GetProvider() *UpdatePhoneNumberManagementResponseProvider {
	if u == nil {
		return nil
	}
	return u.Provider
}

func (u *UpdatePhoneNumberManagementResponse) GetPhoneNumber() *string {
	if u == nil {
		return nil
	}
	return u.PhoneNumber
}

func (u *UpdatePhoneNumberManagementResponse) GetLabel() *string {
	if u == nil {
		return nil
	}
	return u.Label
}

func (u *UpdatePhoneNumberManagementResponse) GetInbound() *bool {
	if u == nil {
		return nil
	}
	return u.Inbound
}

func (u *UpdatePhoneNumberManagementResponse) GetOutbound() *bool {
	if u == nil {
		return nil
	}
	return u.Outbound
}

func (u *UpdatePhoneNumberManagementResponse) GetAssociatedPipeline() *UpdatePhoneNumberManagementResponseAssociatedPipeline {
	if u == nil {
		return nil
	}
	return u.AssociatedPipeline
}

func (u *UpdatePhoneNumberManagementResponse) GetInboundConfig() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.InboundConfig
}

func (u *UpdatePhoneNumberManagementResponse) GetOutboundConfig() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.OutboundConfig
}

func (u *UpdatePhoneNumberManagementResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdatePhoneNumberManagementResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumberManagementResponse) SetProvider(provider *UpdatePhoneNumberManagementResponseProvider) {
	u.Provider = provider
	u.require(updatePhoneNumberManagementResponseFieldProvider)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumberManagementResponse) SetPhoneNumber(phoneNumber *string) {
	u.PhoneNumber = phoneNumber
	u.require(updatePhoneNumberManagementResponseFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumberManagementResponse) SetLabel(label *string) {
	u.Label = label
	u.require(updatePhoneNumberManagementResponseFieldLabel)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumberManagementResponse) SetInbound(inbound *bool) {
	u.Inbound = inbound
	u.require(updatePhoneNumberManagementResponseFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumberManagementResponse) SetOutbound(outbound *bool) {
	u.Outbound = outbound
	u.require(updatePhoneNumberManagementResponseFieldOutbound)
}

// SetAssociatedPipeline sets the AssociatedPipeline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumberManagementResponse) SetAssociatedPipeline(associatedPipeline *UpdatePhoneNumberManagementResponseAssociatedPipeline) {
	u.AssociatedPipeline = associatedPipeline
	u.require(updatePhoneNumberManagementResponseFieldAssociatedPipeline)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumberManagementResponse) SetInboundConfig(inboundConfig map[string]interface{}) {
	u.InboundConfig = inboundConfig
	u.require(updatePhoneNumberManagementResponseFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumberManagementResponse) SetOutboundConfig(outboundConfig map[string]interface{}) {
	u.OutboundConfig = outboundConfig
	u.require(updatePhoneNumberManagementResponseFieldOutboundConfig)
}

func (u *UpdatePhoneNumberManagementResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePhoneNumberManagementResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdatePhoneNumberManagementResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdatePhoneNumberManagementResponse) MarshalJSON() ([]byte, error) {
	type embed UpdatePhoneNumberManagementResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdatePhoneNumberManagementResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// The associated pipeline information. Returns `null` if no pipeline is associated.
var (
	updatePhoneNumberManagementResponseAssociatedPipelineFieldPipelineID   = big.NewInt(1 << 0)
	updatePhoneNumberManagementResponseAssociatedPipelineFieldPipelineName = big.NewInt(1 << 1)
)

type UpdatePhoneNumberManagementResponseAssociatedPipeline struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Pipeline name.
	PipelineName *string `json:"pipeline_name,omitempty" url:"pipeline_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdatePhoneNumberManagementResponseAssociatedPipeline) GetPipelineID() *string {
	if u == nil {
		return nil
	}
	return u.PipelineID
}

func (u *UpdatePhoneNumberManagementResponseAssociatedPipeline) GetPipelineName() *string {
	if u == nil {
		return nil
	}
	return u.PipelineName
}

func (u *UpdatePhoneNumberManagementResponseAssociatedPipeline) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdatePhoneNumberManagementResponseAssociatedPipeline) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumberManagementResponseAssociatedPipeline) SetPipelineID(pipelineID *string) {
	u.PipelineID = pipelineID
	u.require(updatePhoneNumberManagementResponseAssociatedPipelineFieldPipelineID)
}

// SetPipelineName sets the PipelineName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumberManagementResponseAssociatedPipeline) SetPipelineName(pipelineName *string) {
	u.PipelineName = pipelineName
	u.require(updatePhoneNumberManagementResponseAssociatedPipelineFieldPipelineName)
}

func (u *UpdatePhoneNumberManagementResponseAssociatedPipeline) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePhoneNumberManagementResponseAssociatedPipeline
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdatePhoneNumberManagementResponseAssociatedPipeline(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdatePhoneNumberManagementResponseAssociatedPipeline) MarshalJSON() ([]byte, error) {
	type embed UpdatePhoneNumberManagementResponseAssociatedPipeline
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdatePhoneNumberManagementResponseAssociatedPipeline) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// Number provider:
// - `byo`: BYO (Bring Your Own)
// - `twilio`: Twilio
type UpdatePhoneNumberManagementResponseProvider string

const (
	UpdatePhoneNumberManagementResponseProviderByo    UpdatePhoneNumberManagementResponseProvider = "byo"
	UpdatePhoneNumberManagementResponseProviderTwilio UpdatePhoneNumberManagementResponseProvider = "twilio"
)

func NewUpdatePhoneNumberManagementResponseProviderFromString(s string) (UpdatePhoneNumberManagementResponseProvider, error) {
	switch s {
	case "byo":
		return UpdatePhoneNumberManagementResponseProviderByo, nil
	case "twilio":
		return UpdatePhoneNumberManagementResponseProviderTwilio, nil
	}
	var t UpdatePhoneNumberManagementResponseProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdatePhoneNumberManagementResponseProvider) Ptr() *UpdatePhoneNumberManagementResponseProvider {
	return &u
}

var (
	updatePhoneNumberManagementRequestFieldPhoneNumber    = big.NewInt(1 << 0)
	updatePhoneNumberManagementRequestFieldInboundConfig  = big.NewInt(1 << 1)
	updatePhoneNumberManagementRequestFieldOutboundConfig = big.NewInt(1 << 2)
)

type UpdatePhoneNumberManagementRequest struct {
	// Telephone number in E.164 format. For example, +11234567890.
	PhoneNumber string `json:"-" url:"-"`
	// Update inbound call configuration. Passing `null` will clear the configuration.
	InboundConfig *UpdatePhoneNumberManagementRequestInboundConfig `json:"inbound_config,omitempty" url:"-"`
	// Update outbound call configuration. Passing `null` will clear the configuration.
	OutboundConfig *UpdatePhoneNumberManagementRequestOutboundConfig `json:"outbound_config,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdatePhoneNumberManagementRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumberManagementRequest) SetPhoneNumber(phoneNumber string) {
	u.PhoneNumber = phoneNumber
	u.require(updatePhoneNumberManagementRequestFieldPhoneNumber)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumberManagementRequest) SetInboundConfig(inboundConfig *UpdatePhoneNumberManagementRequestInboundConfig) {
	u.InboundConfig = inboundConfig
	u.require(updatePhoneNumberManagementRequestFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumberManagementRequest) SetOutboundConfig(outboundConfig *UpdatePhoneNumberManagementRequestOutboundConfig) {
	u.OutboundConfig = outboundConfig
	u.require(updatePhoneNumberManagementRequestFieldOutboundConfig)
}
