// Code generated by Fern. DO NOT EDIT.

package Agora

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/fern-demo/agoraio-go-sdk/internal"
	big "math/big"
)

var (
	importNumberRequestFieldProvider       = big.NewInt(1 << 0)
	importNumberRequestFieldPhoneNumber    = big.NewInt(1 << 1)
	importNumberRequestFieldLabel          = big.NewInt(1 << 2)
	importNumberRequestFieldInbound        = big.NewInt(1 << 3)
	importNumberRequestFieldOutbound       = big.NewInt(1 << 4)
	importNumberRequestFieldInboundConfig  = big.NewInt(1 << 5)
	importNumberRequestFieldOutboundConfig = big.NewInt(1 << 6)
)

type ImportNumberRequest struct {
	// Number provider:
	// - `byo`: BYO (Bring Your Own)
	// - `twilio`: Twilio
	Provider ImportNumberRequestProvider `json:"provider" url:"-"`
	// Telephone number in E.164 format.
	PhoneNumber string `json:"phone_number" url:"-"`
	// A label used to identify the number.
	Label string `json:"label" url:"-"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"-"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"-"`
	// SIP inbound call configuration.
	InboundConfig *ImportNumberRequestInboundConfig `json:"inbound_config,omitempty" url:"-"`
	// SIP outbound call configuration.
	OutboundConfig *ImportNumberRequestOutboundConfig `json:"outbound_config,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *ImportNumberRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberRequest) SetProvider(provider ImportNumberRequestProvider) {
	i.Provider = provider
	i.require(importNumberRequestFieldProvider)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberRequest) SetPhoneNumber(phoneNumber string) {
	i.PhoneNumber = phoneNumber
	i.require(importNumberRequestFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberRequest) SetLabel(label string) {
	i.Label = label
	i.require(importNumberRequestFieldLabel)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberRequest) SetInbound(inbound *bool) {
	i.Inbound = inbound
	i.require(importNumberRequestFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberRequest) SetOutbound(outbound *bool) {
	i.Outbound = outbound
	i.require(importNumberRequestFieldOutbound)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberRequest) SetInboundConfig(inboundConfig *ImportNumberRequestInboundConfig) {
	i.InboundConfig = inboundConfig
	i.require(importNumberRequestFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberRequest) SetOutboundConfig(outboundConfig *ImportNumberRequestOutboundConfig) {
	i.OutboundConfig = outboundConfig
	i.require(importNumberRequestFieldOutboundConfig)
}

// SIP inbound call configuration.
var (
	importNumberRequestInboundConfigFieldAllowedAddresses = big.NewInt(1 << 0)
)

type ImportNumberRequestInboundConfig struct {
	// List of allowed IP addresses. For example `112.126.15.64/27`
	AllowedAddresses []string `json:"allowed_addresses,omitempty" url:"allowed_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *ImportNumberRequestInboundConfig) GetAllowedAddresses() []string {
	if i == nil {
		return nil
	}
	return i.AllowedAddresses
}

func (i *ImportNumberRequestInboundConfig) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *ImportNumberRequestInboundConfig) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetAllowedAddresses sets the AllowedAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberRequestInboundConfig) SetAllowedAddresses(allowedAddresses []string) {
	i.AllowedAddresses = allowedAddresses
	i.require(importNumberRequestInboundConfigFieldAllowedAddresses)
}

func (i *ImportNumberRequestInboundConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler ImportNumberRequestInboundConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = ImportNumberRequestInboundConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *ImportNumberRequestInboundConfig) MarshalJSON() ([]byte, error) {
	type embed ImportNumberRequestInboundConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *ImportNumberRequestInboundConfig) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// SIP outbound call configuration.
var (
	importNumberRequestOutboundConfigFieldAddress   = big.NewInt(1 << 0)
	importNumberRequestOutboundConfigFieldTransport = big.NewInt(1 << 1)
	importNumberRequestOutboundConfigFieldPrefix    = big.NewInt(1 << 2)
)

type ImportNumberRequestOutboundConfig struct {
	// SIP address. For example `xxx:xxx@sip.example.com`
	Address *string `json:"address,omitempty" url:"address,omitempty"`
	// Transport protocol. For example `tls`
	Transport *string `json:"transport,omitempty" url:"transport,omitempty"`
	// Number prefix. For example `6036`
	Prefix *string `json:"prefix,omitempty" url:"prefix,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *ImportNumberRequestOutboundConfig) GetAddress() *string {
	if i == nil {
		return nil
	}
	return i.Address
}

func (i *ImportNumberRequestOutboundConfig) GetTransport() *string {
	if i == nil {
		return nil
	}
	return i.Transport
}

func (i *ImportNumberRequestOutboundConfig) GetPrefix() *string {
	if i == nil {
		return nil
	}
	return i.Prefix
}

func (i *ImportNumberRequestOutboundConfig) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *ImportNumberRequestOutboundConfig) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberRequestOutboundConfig) SetAddress(address *string) {
	i.Address = address
	i.require(importNumberRequestOutboundConfigFieldAddress)
}

// SetTransport sets the Transport field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberRequestOutboundConfig) SetTransport(transport *string) {
	i.Transport = transport
	i.require(importNumberRequestOutboundConfigFieldTransport)
}

// SetPrefix sets the Prefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberRequestOutboundConfig) SetPrefix(prefix *string) {
	i.Prefix = prefix
	i.require(importNumberRequestOutboundConfigFieldPrefix)
}

func (i *ImportNumberRequestOutboundConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler ImportNumberRequestOutboundConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = ImportNumberRequestOutboundConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *ImportNumberRequestOutboundConfig) MarshalJSON() ([]byte, error) {
	type embed ImportNumberRequestOutboundConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *ImportNumberRequestOutboundConfig) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Number provider:
// - `byo`: BYO (Bring Your Own)
// - `twilio`: Twilio
type ImportNumberRequestProvider string

const (
	ImportNumberRequestProviderByo    ImportNumberRequestProvider = "byo"
	ImportNumberRequestProviderTwilio ImportNumberRequestProvider = "twilio"
)

func NewImportNumberRequestProviderFromString(s string) (ImportNumberRequestProvider, error) {
	switch s {
	case "byo":
		return ImportNumberRequestProviderByo, nil
	case "twilio":
		return ImportNumberRequestProviderTwilio, nil
	}
	var t ImportNumberRequestProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i ImportNumberRequestProvider) Ptr() *ImportNumberRequestProvider {
	return &i
}

var (
	importNumberResponseFieldPhoneNumber        = big.NewInt(1 << 0)
	importNumberResponseFieldLabel              = big.NewInt(1 << 1)
	importNumberResponseFieldProvider           = big.NewInt(1 << 2)
	importNumberResponseFieldInbound            = big.NewInt(1 << 3)
	importNumberResponseFieldOutbound           = big.NewInt(1 << 4)
	importNumberResponseFieldAssociatedPipeline = big.NewInt(1 << 5)
)

type ImportNumberResponse struct {
	// A telephone number in E.164 format, used as a unique identifier.
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	// A label used to identify the number.
	Label *string `json:"label,omitempty" url:"label,omitempty"`
	// Number provider.
	Provider *string `json:"provider,omitempty" url:"provider,omitempty"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"inbound,omitempty"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"outbound,omitempty"`
	// The associated pipeline information. Returns `null` if no pipeline is associated.
	AssociatedPipeline *ImportNumberResponseAssociatedPipeline `json:"associated_pipeline,omitempty" url:"associated_pipeline,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *ImportNumberResponse) GetPhoneNumber() *string {
	if i == nil {
		return nil
	}
	return i.PhoneNumber
}

func (i *ImportNumberResponse) GetLabel() *string {
	if i == nil {
		return nil
	}
	return i.Label
}

func (i *ImportNumberResponse) GetProvider() *string {
	if i == nil {
		return nil
	}
	return i.Provider
}

func (i *ImportNumberResponse) GetInbound() *bool {
	if i == nil {
		return nil
	}
	return i.Inbound
}

func (i *ImportNumberResponse) GetOutbound() *bool {
	if i == nil {
		return nil
	}
	return i.Outbound
}

func (i *ImportNumberResponse) GetAssociatedPipeline() *ImportNumberResponseAssociatedPipeline {
	if i == nil {
		return nil
	}
	return i.AssociatedPipeline
}

func (i *ImportNumberResponse) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *ImportNumberResponse) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberResponse) SetPhoneNumber(phoneNumber *string) {
	i.PhoneNumber = phoneNumber
	i.require(importNumberResponseFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberResponse) SetLabel(label *string) {
	i.Label = label
	i.require(importNumberResponseFieldLabel)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberResponse) SetProvider(provider *string) {
	i.Provider = provider
	i.require(importNumberResponseFieldProvider)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberResponse) SetInbound(inbound *bool) {
	i.Inbound = inbound
	i.require(importNumberResponseFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberResponse) SetOutbound(outbound *bool) {
	i.Outbound = outbound
	i.require(importNumberResponseFieldOutbound)
}

// SetAssociatedPipeline sets the AssociatedPipeline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberResponse) SetAssociatedPipeline(associatedPipeline *ImportNumberResponseAssociatedPipeline) {
	i.AssociatedPipeline = associatedPipeline
	i.require(importNumberResponseFieldAssociatedPipeline)
}

func (i *ImportNumberResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ImportNumberResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = ImportNumberResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *ImportNumberResponse) MarshalJSON() ([]byte, error) {
	type embed ImportNumberResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *ImportNumberResponse) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// The associated pipeline information. Returns `null` if no pipeline is associated.
var (
	importNumberResponseAssociatedPipelineFieldPipelineID   = big.NewInt(1 << 0)
	importNumberResponseAssociatedPipelineFieldPipelineName = big.NewInt(1 << 1)
)

type ImportNumberResponseAssociatedPipeline struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Pipeline name.
	PipelineName *string `json:"pipeline_name,omitempty" url:"pipeline_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *ImportNumberResponseAssociatedPipeline) GetPipelineID() *string {
	if i == nil {
		return nil
	}
	return i.PipelineID
}

func (i *ImportNumberResponseAssociatedPipeline) GetPipelineName() *string {
	if i == nil {
		return nil
	}
	return i.PipelineName
}

func (i *ImportNumberResponseAssociatedPipeline) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *ImportNumberResponseAssociatedPipeline) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberResponseAssociatedPipeline) SetPipelineID(pipelineID *string) {
	i.PipelineID = pipelineID
	i.require(importNumberResponseAssociatedPipelineFieldPipelineID)
}

// SetPipelineName sets the PipelineName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportNumberResponseAssociatedPipeline) SetPipelineName(pipelineName *string) {
	i.PipelineName = pipelineName
	i.require(importNumberResponseAssociatedPipelineFieldPipelineName)
}

func (i *ImportNumberResponseAssociatedPipeline) UnmarshalJSON(data []byte) error {
	type unmarshaler ImportNumberResponseAssociatedPipeline
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = ImportNumberResponseAssociatedPipeline(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *ImportNumberResponseAssociatedPipeline) MarshalJSON() ([]byte, error) {
	type embed ImportNumberResponseAssociatedPipeline
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *ImportNumberResponseAssociatedPipeline) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	retrieveNumberInformationResponseFieldProvider           = big.NewInt(1 << 0)
	retrieveNumberInformationResponseFieldPhoneNumber        = big.NewInt(1 << 1)
	retrieveNumberInformationResponseFieldLabel              = big.NewInt(1 << 2)
	retrieveNumberInformationResponseFieldInbound            = big.NewInt(1 << 3)
	retrieveNumberInformationResponseFieldOutbound           = big.NewInt(1 << 4)
	retrieveNumberInformationResponseFieldAssociatedPipeline = big.NewInt(1 << 5)
	retrieveNumberInformationResponseFieldInboundConfig      = big.NewInt(1 << 6)
	retrieveNumberInformationResponseFieldOutboundConfig     = big.NewInt(1 << 7)
)

type RetrieveNumberInformationResponse struct {
	// Number provider:
	// - `byo`: BYO (Bring Your Own)
	// - `twilio`: Twilio
	Provider *RetrieveNumberInformationResponseProvider `json:"provider,omitempty" url:"provider,omitempty"`
	// A telephone number in E.164 format, used as a unique identifier.
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	// A label used to identify the number.
	Label *string `json:"label,omitempty" url:"label,omitempty"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"inbound,omitempty"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"outbound,omitempty"`
	// The associated pipeline information. Returns `null` if no pipeline is associated.
	AssociatedPipeline *RetrieveNumberInformationResponseAssociatedPipeline `json:"associated_pipeline,omitempty" url:"associated_pipeline,omitempty"`
	// SIP inbound call configuration details. Returns `null` if not configured.
	InboundConfig map[string]interface{} `json:"inbound_config,omitempty" url:"inbound_config,omitempty"`
	// SIP outbound call configuration details. Returns `null` if not configured.
	OutboundConfig map[string]interface{} `json:"outbound_config,omitempty" url:"outbound_config,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RetrieveNumberInformationResponse) GetProvider() *RetrieveNumberInformationResponseProvider {
	if r == nil {
		return nil
	}
	return r.Provider
}

func (r *RetrieveNumberInformationResponse) GetPhoneNumber() *string {
	if r == nil {
		return nil
	}
	return r.PhoneNumber
}

func (r *RetrieveNumberInformationResponse) GetLabel() *string {
	if r == nil {
		return nil
	}
	return r.Label
}

func (r *RetrieveNumberInformationResponse) GetInbound() *bool {
	if r == nil {
		return nil
	}
	return r.Inbound
}

func (r *RetrieveNumberInformationResponse) GetOutbound() *bool {
	if r == nil {
		return nil
	}
	return r.Outbound
}

func (r *RetrieveNumberInformationResponse) GetAssociatedPipeline() *RetrieveNumberInformationResponseAssociatedPipeline {
	if r == nil {
		return nil
	}
	return r.AssociatedPipeline
}

func (r *RetrieveNumberInformationResponse) GetInboundConfig() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.InboundConfig
}

func (r *RetrieveNumberInformationResponse) GetOutboundConfig() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.OutboundConfig
}

func (r *RetrieveNumberInformationResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RetrieveNumberInformationResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberInformationResponse) SetProvider(provider *RetrieveNumberInformationResponseProvider) {
	r.Provider = provider
	r.require(retrieveNumberInformationResponseFieldProvider)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberInformationResponse) SetPhoneNumber(phoneNumber *string) {
	r.PhoneNumber = phoneNumber
	r.require(retrieveNumberInformationResponseFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberInformationResponse) SetLabel(label *string) {
	r.Label = label
	r.require(retrieveNumberInformationResponseFieldLabel)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberInformationResponse) SetInbound(inbound *bool) {
	r.Inbound = inbound
	r.require(retrieveNumberInformationResponseFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberInformationResponse) SetOutbound(outbound *bool) {
	r.Outbound = outbound
	r.require(retrieveNumberInformationResponseFieldOutbound)
}

// SetAssociatedPipeline sets the AssociatedPipeline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberInformationResponse) SetAssociatedPipeline(associatedPipeline *RetrieveNumberInformationResponseAssociatedPipeline) {
	r.AssociatedPipeline = associatedPipeline
	r.require(retrieveNumberInformationResponseFieldAssociatedPipeline)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberInformationResponse) SetInboundConfig(inboundConfig map[string]interface{}) {
	r.InboundConfig = inboundConfig
	r.require(retrieveNumberInformationResponseFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberInformationResponse) SetOutboundConfig(outboundConfig map[string]interface{}) {
	r.OutboundConfig = outboundConfig
	r.require(retrieveNumberInformationResponseFieldOutboundConfig)
}

func (r *RetrieveNumberInformationResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RetrieveNumberInformationResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RetrieveNumberInformationResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RetrieveNumberInformationResponse) MarshalJSON() ([]byte, error) {
	type embed RetrieveNumberInformationResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RetrieveNumberInformationResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// The associated pipeline information. Returns `null` if no pipeline is associated.
var (
	retrieveNumberInformationResponseAssociatedPipelineFieldPipelineID   = big.NewInt(1 << 0)
	retrieveNumberInformationResponseAssociatedPipelineFieldPipelineName = big.NewInt(1 << 1)
)

type RetrieveNumberInformationResponseAssociatedPipeline struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Pipeline name.
	PipelineName *string `json:"pipeline_name,omitempty" url:"pipeline_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RetrieveNumberInformationResponseAssociatedPipeline) GetPipelineID() *string {
	if r == nil {
		return nil
	}
	return r.PipelineID
}

func (r *RetrieveNumberInformationResponseAssociatedPipeline) GetPipelineName() *string {
	if r == nil {
		return nil
	}
	return r.PipelineName
}

func (r *RetrieveNumberInformationResponseAssociatedPipeline) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RetrieveNumberInformationResponseAssociatedPipeline) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberInformationResponseAssociatedPipeline) SetPipelineID(pipelineID *string) {
	r.PipelineID = pipelineID
	r.require(retrieveNumberInformationResponseAssociatedPipelineFieldPipelineID)
}

// SetPipelineName sets the PipelineName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberInformationResponseAssociatedPipeline) SetPipelineName(pipelineName *string) {
	r.PipelineName = pipelineName
	r.require(retrieveNumberInformationResponseAssociatedPipelineFieldPipelineName)
}

func (r *RetrieveNumberInformationResponseAssociatedPipeline) UnmarshalJSON(data []byte) error {
	type unmarshaler RetrieveNumberInformationResponseAssociatedPipeline
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RetrieveNumberInformationResponseAssociatedPipeline(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RetrieveNumberInformationResponseAssociatedPipeline) MarshalJSON() ([]byte, error) {
	type embed RetrieveNumberInformationResponseAssociatedPipeline
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RetrieveNumberInformationResponseAssociatedPipeline) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Number provider:
// - `byo`: BYO (Bring Your Own)
// - `twilio`: Twilio
type RetrieveNumberInformationResponseProvider string

const (
	RetrieveNumberInformationResponseProviderByo    RetrieveNumberInformationResponseProvider = "byo"
	RetrieveNumberInformationResponseProviderTwilio RetrieveNumberInformationResponseProvider = "twilio"
)

func NewRetrieveNumberInformationResponseProviderFromString(s string) (RetrieveNumberInformationResponseProvider, error) {
	switch s {
	case "byo":
		return RetrieveNumberInformationResponseProviderByo, nil
	case "twilio":
		return RetrieveNumberInformationResponseProviderTwilio, nil
	}
	var t RetrieveNumberInformationResponseProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RetrieveNumberInformationResponseProvider) Ptr() *RetrieveNumberInformationResponseProvider {
	return &r
}

var (
	retrieveNumberListResponseItemFieldProvider           = big.NewInt(1 << 0)
	retrieveNumberListResponseItemFieldPhoneNumber        = big.NewInt(1 << 1)
	retrieveNumberListResponseItemFieldLabel              = big.NewInt(1 << 2)
	retrieveNumberListResponseItemFieldInbound            = big.NewInt(1 << 3)
	retrieveNumberListResponseItemFieldOutbound           = big.NewInt(1 << 4)
	retrieveNumberListResponseItemFieldAssociatedPipeline = big.NewInt(1 << 5)
	retrieveNumberListResponseItemFieldInboundConfig      = big.NewInt(1 << 6)
	retrieveNumberListResponseItemFieldOutboundConfig     = big.NewInt(1 << 7)
)

type RetrieveNumberListResponseItem struct {
	// Number provider:
	// - `byo`: BYO (Bring Your Own).
	// - `twilio`: Twilio.
	Provider *RetrieveNumberListResponseItemProvider `json:"provider,omitempty" url:"provider,omitempty"`
	// A telephone number in E.164 format, used as a unique identifier.
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	// A label used to identify the number.
	Label *string `json:"label,omitempty" url:"label,omitempty"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"inbound,omitempty"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"outbound,omitempty"`
	// The associated pipeline information. Returns `null` if no pipeline is associated.
	AssociatedPipeline *RetrieveNumberListResponseItemAssociatedPipeline `json:"associated_pipeline,omitempty" url:"associated_pipeline,omitempty"`
	// SIP inbound call configuration details. Returns `null` if not configured.
	InboundConfig map[string]interface{} `json:"inbound_config,omitempty" url:"inbound_config,omitempty"`
	// SIP outbound call configuration details. Returns `null` if not configured.
	OutboundConfig map[string]interface{} `json:"outbound_config,omitempty" url:"outbound_config,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RetrieveNumberListResponseItem) GetProvider() *RetrieveNumberListResponseItemProvider {
	if r == nil {
		return nil
	}
	return r.Provider
}

func (r *RetrieveNumberListResponseItem) GetPhoneNumber() *string {
	if r == nil {
		return nil
	}
	return r.PhoneNumber
}

func (r *RetrieveNumberListResponseItem) GetLabel() *string {
	if r == nil {
		return nil
	}
	return r.Label
}

func (r *RetrieveNumberListResponseItem) GetInbound() *bool {
	if r == nil {
		return nil
	}
	return r.Inbound
}

func (r *RetrieveNumberListResponseItem) GetOutbound() *bool {
	if r == nil {
		return nil
	}
	return r.Outbound
}

func (r *RetrieveNumberListResponseItem) GetAssociatedPipeline() *RetrieveNumberListResponseItemAssociatedPipeline {
	if r == nil {
		return nil
	}
	return r.AssociatedPipeline
}

func (r *RetrieveNumberListResponseItem) GetInboundConfig() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.InboundConfig
}

func (r *RetrieveNumberListResponseItem) GetOutboundConfig() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.OutboundConfig
}

func (r *RetrieveNumberListResponseItem) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RetrieveNumberListResponseItem) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberListResponseItem) SetProvider(provider *RetrieveNumberListResponseItemProvider) {
	r.Provider = provider
	r.require(retrieveNumberListResponseItemFieldProvider)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberListResponseItem) SetPhoneNumber(phoneNumber *string) {
	r.PhoneNumber = phoneNumber
	r.require(retrieveNumberListResponseItemFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberListResponseItem) SetLabel(label *string) {
	r.Label = label
	r.require(retrieveNumberListResponseItemFieldLabel)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberListResponseItem) SetInbound(inbound *bool) {
	r.Inbound = inbound
	r.require(retrieveNumberListResponseItemFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberListResponseItem) SetOutbound(outbound *bool) {
	r.Outbound = outbound
	r.require(retrieveNumberListResponseItemFieldOutbound)
}

// SetAssociatedPipeline sets the AssociatedPipeline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberListResponseItem) SetAssociatedPipeline(associatedPipeline *RetrieveNumberListResponseItemAssociatedPipeline) {
	r.AssociatedPipeline = associatedPipeline
	r.require(retrieveNumberListResponseItemFieldAssociatedPipeline)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberListResponseItem) SetInboundConfig(inboundConfig map[string]interface{}) {
	r.InboundConfig = inboundConfig
	r.require(retrieveNumberListResponseItemFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberListResponseItem) SetOutboundConfig(outboundConfig map[string]interface{}) {
	r.OutboundConfig = outboundConfig
	r.require(retrieveNumberListResponseItemFieldOutboundConfig)
}

func (r *RetrieveNumberListResponseItem) UnmarshalJSON(data []byte) error {
	type unmarshaler RetrieveNumberListResponseItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RetrieveNumberListResponseItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RetrieveNumberListResponseItem) MarshalJSON() ([]byte, error) {
	type embed RetrieveNumberListResponseItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RetrieveNumberListResponseItem) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// The associated pipeline information. Returns `null` if no pipeline is associated.
var (
	retrieveNumberListResponseItemAssociatedPipelineFieldPipelineID   = big.NewInt(1 << 0)
	retrieveNumberListResponseItemAssociatedPipelineFieldPipelineName = big.NewInt(1 << 1)
)

type RetrieveNumberListResponseItemAssociatedPipeline struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Pipeline name.
	PipelineName *string `json:"pipeline_name,omitempty" url:"pipeline_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RetrieveNumberListResponseItemAssociatedPipeline) GetPipelineID() *string {
	if r == nil {
		return nil
	}
	return r.PipelineID
}

func (r *RetrieveNumberListResponseItemAssociatedPipeline) GetPipelineName() *string {
	if r == nil {
		return nil
	}
	return r.PipelineName
}

func (r *RetrieveNumberListResponseItemAssociatedPipeline) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RetrieveNumberListResponseItemAssociatedPipeline) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberListResponseItemAssociatedPipeline) SetPipelineID(pipelineID *string) {
	r.PipelineID = pipelineID
	r.require(retrieveNumberListResponseItemAssociatedPipelineFieldPipelineID)
}

// SetPipelineName sets the PipelineName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNumberListResponseItemAssociatedPipeline) SetPipelineName(pipelineName *string) {
	r.PipelineName = pipelineName
	r.require(retrieveNumberListResponseItemAssociatedPipelineFieldPipelineName)
}

func (r *RetrieveNumberListResponseItemAssociatedPipeline) UnmarshalJSON(data []byte) error {
	type unmarshaler RetrieveNumberListResponseItemAssociatedPipeline
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RetrieveNumberListResponseItemAssociatedPipeline(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RetrieveNumberListResponseItemAssociatedPipeline) MarshalJSON() ([]byte, error) {
	type embed RetrieveNumberListResponseItemAssociatedPipeline
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RetrieveNumberListResponseItemAssociatedPipeline) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Number provider:
// - `byo`: BYO (Bring Your Own).
// - `twilio`: Twilio.
type RetrieveNumberListResponseItemProvider string

const (
	RetrieveNumberListResponseItemProviderByo    RetrieveNumberListResponseItemProvider = "byo"
	RetrieveNumberListResponseItemProviderTwilio RetrieveNumberListResponseItemProvider = "twilio"
)

func NewRetrieveNumberListResponseItemProviderFromString(s string) (RetrieveNumberListResponseItemProvider, error) {
	switch s {
	case "byo":
		return RetrieveNumberListResponseItemProviderByo, nil
	case "twilio":
		return RetrieveNumberListResponseItemProviderTwilio, nil
	}
	var t RetrieveNumberListResponseItemProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RetrieveNumberListResponseItemProvider) Ptr() *RetrieveNumberListResponseItemProvider {
	return &r
}

// Update inbound call configuration. Passing `null` will clear the configuration.
var (
	updateNumberConfigurationRequestInboundConfigFieldPipelineID = big.NewInt(1 << 0)
)

type UpdateNumberConfigurationRequestInboundConfig struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateNumberConfigurationRequestInboundConfig) GetPipelineID() *string {
	if u == nil {
		return nil
	}
	return u.PipelineID
}

func (u *UpdateNumberConfigurationRequestInboundConfig) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateNumberConfigurationRequestInboundConfig) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberConfigurationRequestInboundConfig) SetPipelineID(pipelineID *string) {
	u.PipelineID = pipelineID
	u.require(updateNumberConfigurationRequestInboundConfigFieldPipelineID)
}

func (u *UpdateNumberConfigurationRequestInboundConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateNumberConfigurationRequestInboundConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateNumberConfigurationRequestInboundConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateNumberConfigurationRequestInboundConfig) MarshalJSON() ([]byte, error) {
	type embed UpdateNumberConfigurationRequestInboundConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateNumberConfigurationRequestInboundConfig) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// Update outbound call configuration. Passing `null` will clear the configuration.
var (
	updateNumberConfigurationRequestOutboundConfigFieldPipelineID = big.NewInt(1 << 0)
)

type UpdateNumberConfigurationRequestOutboundConfig struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateNumberConfigurationRequestOutboundConfig) GetPipelineID() *string {
	if u == nil {
		return nil
	}
	return u.PipelineID
}

func (u *UpdateNumberConfigurationRequestOutboundConfig) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateNumberConfigurationRequestOutboundConfig) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberConfigurationRequestOutboundConfig) SetPipelineID(pipelineID *string) {
	u.PipelineID = pipelineID
	u.require(updateNumberConfigurationRequestOutboundConfigFieldPipelineID)
}

func (u *UpdateNumberConfigurationRequestOutboundConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateNumberConfigurationRequestOutboundConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateNumberConfigurationRequestOutboundConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateNumberConfigurationRequestOutboundConfig) MarshalJSON() ([]byte, error) {
	type embed UpdateNumberConfigurationRequestOutboundConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateNumberConfigurationRequestOutboundConfig) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateNumberConfigurationResponseFieldProvider           = big.NewInt(1 << 0)
	updateNumberConfigurationResponseFieldPhoneNumber        = big.NewInt(1 << 1)
	updateNumberConfigurationResponseFieldLabel              = big.NewInt(1 << 2)
	updateNumberConfigurationResponseFieldInbound            = big.NewInt(1 << 3)
	updateNumberConfigurationResponseFieldOutbound           = big.NewInt(1 << 4)
	updateNumberConfigurationResponseFieldAssociatedPipeline = big.NewInt(1 << 5)
	updateNumberConfigurationResponseFieldInboundConfig      = big.NewInt(1 << 6)
	updateNumberConfigurationResponseFieldOutboundConfig     = big.NewInt(1 << 7)
)

type UpdateNumberConfigurationResponse struct {
	// Number provider:
	// - `byo`: BYO (Bring Your Own)
	// - `twilio`: Twilio
	Provider *UpdateNumberConfigurationResponseProvider `json:"provider,omitempty" url:"provider,omitempty"`
	// A telephone number in E.164 format, used as a unique identifier.
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	// A label used to identify the number.
	Label *string `json:"label,omitempty" url:"label,omitempty"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"inbound,omitempty"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"outbound,omitempty"`
	// The associated pipeline information. Returns `null` if no pipeline is associated.
	AssociatedPipeline *UpdateNumberConfigurationResponseAssociatedPipeline `json:"associated_pipeline,omitempty" url:"associated_pipeline,omitempty"`
	// SIP inbound call configuration details. Returns `null` if not configured.
	InboundConfig map[string]interface{} `json:"inbound_config,omitempty" url:"inbound_config,omitempty"`
	// SIP outbound call configuration details. Returns `null` if not configured.
	OutboundConfig map[string]interface{} `json:"outbound_config,omitempty" url:"outbound_config,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateNumberConfigurationResponse) GetProvider() *UpdateNumberConfigurationResponseProvider {
	if u == nil {
		return nil
	}
	return u.Provider
}

func (u *UpdateNumberConfigurationResponse) GetPhoneNumber() *string {
	if u == nil {
		return nil
	}
	return u.PhoneNumber
}

func (u *UpdateNumberConfigurationResponse) GetLabel() *string {
	if u == nil {
		return nil
	}
	return u.Label
}

func (u *UpdateNumberConfigurationResponse) GetInbound() *bool {
	if u == nil {
		return nil
	}
	return u.Inbound
}

func (u *UpdateNumberConfigurationResponse) GetOutbound() *bool {
	if u == nil {
		return nil
	}
	return u.Outbound
}

func (u *UpdateNumberConfigurationResponse) GetAssociatedPipeline() *UpdateNumberConfigurationResponseAssociatedPipeline {
	if u == nil {
		return nil
	}
	return u.AssociatedPipeline
}

func (u *UpdateNumberConfigurationResponse) GetInboundConfig() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.InboundConfig
}

func (u *UpdateNumberConfigurationResponse) GetOutboundConfig() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.OutboundConfig
}

func (u *UpdateNumberConfigurationResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateNumberConfigurationResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberConfigurationResponse) SetProvider(provider *UpdateNumberConfigurationResponseProvider) {
	u.Provider = provider
	u.require(updateNumberConfigurationResponseFieldProvider)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberConfigurationResponse) SetPhoneNumber(phoneNumber *string) {
	u.PhoneNumber = phoneNumber
	u.require(updateNumberConfigurationResponseFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberConfigurationResponse) SetLabel(label *string) {
	u.Label = label
	u.require(updateNumberConfigurationResponseFieldLabel)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberConfigurationResponse) SetInbound(inbound *bool) {
	u.Inbound = inbound
	u.require(updateNumberConfigurationResponseFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberConfigurationResponse) SetOutbound(outbound *bool) {
	u.Outbound = outbound
	u.require(updateNumberConfigurationResponseFieldOutbound)
}

// SetAssociatedPipeline sets the AssociatedPipeline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberConfigurationResponse) SetAssociatedPipeline(associatedPipeline *UpdateNumberConfigurationResponseAssociatedPipeline) {
	u.AssociatedPipeline = associatedPipeline
	u.require(updateNumberConfigurationResponseFieldAssociatedPipeline)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberConfigurationResponse) SetInboundConfig(inboundConfig map[string]interface{}) {
	u.InboundConfig = inboundConfig
	u.require(updateNumberConfigurationResponseFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberConfigurationResponse) SetOutboundConfig(outboundConfig map[string]interface{}) {
	u.OutboundConfig = outboundConfig
	u.require(updateNumberConfigurationResponseFieldOutboundConfig)
}

func (u *UpdateNumberConfigurationResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateNumberConfigurationResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateNumberConfigurationResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateNumberConfigurationResponse) MarshalJSON() ([]byte, error) {
	type embed UpdateNumberConfigurationResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateNumberConfigurationResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// The associated pipeline information. Returns `null` if no pipeline is associated.
var (
	updateNumberConfigurationResponseAssociatedPipelineFieldPipelineID   = big.NewInt(1 << 0)
	updateNumberConfigurationResponseAssociatedPipelineFieldPipelineName = big.NewInt(1 << 1)
)

type UpdateNumberConfigurationResponseAssociatedPipeline struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Pipeline name.
	PipelineName *string `json:"pipeline_name,omitempty" url:"pipeline_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateNumberConfigurationResponseAssociatedPipeline) GetPipelineID() *string {
	if u == nil {
		return nil
	}
	return u.PipelineID
}

func (u *UpdateNumberConfigurationResponseAssociatedPipeline) GetPipelineName() *string {
	if u == nil {
		return nil
	}
	return u.PipelineName
}

func (u *UpdateNumberConfigurationResponseAssociatedPipeline) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateNumberConfigurationResponseAssociatedPipeline) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberConfigurationResponseAssociatedPipeline) SetPipelineID(pipelineID *string) {
	u.PipelineID = pipelineID
	u.require(updateNumberConfigurationResponseAssociatedPipelineFieldPipelineID)
}

// SetPipelineName sets the PipelineName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberConfigurationResponseAssociatedPipeline) SetPipelineName(pipelineName *string) {
	u.PipelineName = pipelineName
	u.require(updateNumberConfigurationResponseAssociatedPipelineFieldPipelineName)
}

func (u *UpdateNumberConfigurationResponseAssociatedPipeline) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateNumberConfigurationResponseAssociatedPipeline
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateNumberConfigurationResponseAssociatedPipeline(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateNumberConfigurationResponseAssociatedPipeline) MarshalJSON() ([]byte, error) {
	type embed UpdateNumberConfigurationResponseAssociatedPipeline
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateNumberConfigurationResponseAssociatedPipeline) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// Number provider:
// - `byo`: BYO (Bring Your Own)
// - `twilio`: Twilio
type UpdateNumberConfigurationResponseProvider string

const (
	UpdateNumberConfigurationResponseProviderByo    UpdateNumberConfigurationResponseProvider = "byo"
	UpdateNumberConfigurationResponseProviderTwilio UpdateNumberConfigurationResponseProvider = "twilio"
)

func NewUpdateNumberConfigurationResponseProviderFromString(s string) (UpdateNumberConfigurationResponseProvider, error) {
	switch s {
	case "byo":
		return UpdateNumberConfigurationResponseProviderByo, nil
	case "twilio":
		return UpdateNumberConfigurationResponseProviderTwilio, nil
	}
	var t UpdateNumberConfigurationResponseProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateNumberConfigurationResponseProvider) Ptr() *UpdateNumberConfigurationResponseProvider {
	return &u
}

var (
	updateNumberConfigurationRequestFieldInboundConfig  = big.NewInt(1 << 0)
	updateNumberConfigurationRequestFieldOutboundConfig = big.NewInt(1 << 1)
)

type UpdateNumberConfigurationRequest struct {
	// Update inbound call configuration. Passing `null` will clear the configuration.
	InboundConfig *UpdateNumberConfigurationRequestInboundConfig `json:"inbound_config,omitempty" url:"-"`
	// Update outbound call configuration. Passing `null` will clear the configuration.
	OutboundConfig *UpdateNumberConfigurationRequestOutboundConfig `json:"outbound_config,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateNumberConfigurationRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberConfigurationRequest) SetInboundConfig(inboundConfig *UpdateNumberConfigurationRequestInboundConfig) {
	u.InboundConfig = inboundConfig
	u.require(updateNumberConfigurationRequestFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNumberConfigurationRequest) SetOutboundConfig(outboundConfig *UpdateNumberConfigurationRequestOutboundConfig) {
	u.OutboundConfig = outboundConfig
	u.require(updateNumberConfigurationRequestFieldOutboundConfig)
}
