// Code generated by Fern. DO NOT EDIT.

package Agora

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/fern-demo/agoraio-go-sdk/v505/internal"
	big "math/big"
)

var (
	phoneNumberManagementAddRequestFieldProvider       = big.NewInt(1 << 0)
	phoneNumberManagementAddRequestFieldPhoneNumber    = big.NewInt(1 << 1)
	phoneNumberManagementAddRequestFieldLabel          = big.NewInt(1 << 2)
	phoneNumberManagementAddRequestFieldInbound        = big.NewInt(1 << 3)
	phoneNumberManagementAddRequestFieldOutbound       = big.NewInt(1 << 4)
	phoneNumberManagementAddRequestFieldInboundConfig  = big.NewInt(1 << 5)
	phoneNumberManagementAddRequestFieldOutboundConfig = big.NewInt(1 << 6)
)

type PhoneNumberManagementAddRequest struct {
	// Number provider:
	// - `byo`: BYO (Bring Your Own)
	// - `twilio`: Twilio
	Provider PhoneNumberManagementAddRequestProvider `json:"provider" url:"-"`
	// Telephone number in E.164 format.
	PhoneNumber string `json:"phone_number" url:"-"`
	// A label used to identify the number.
	Label string `json:"label" url:"-"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"-"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"-"`
	// SIP inbound call configuration.
	InboundConfig *PhoneNumberManagementAddRequestInboundConfig `json:"inbound_config,omitempty" url:"-"`
	// SIP outbound call configuration.
	OutboundConfig *PhoneNumberManagementAddRequestOutboundConfig `json:"outbound_config,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PhoneNumberManagementAddRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddRequest) SetProvider(provider PhoneNumberManagementAddRequestProvider) {
	p.Provider = provider
	p.require(phoneNumberManagementAddRequestFieldProvider)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddRequest) SetPhoneNumber(phoneNumber string) {
	p.PhoneNumber = phoneNumber
	p.require(phoneNumberManagementAddRequestFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddRequest) SetLabel(label string) {
	p.Label = label
	p.require(phoneNumberManagementAddRequestFieldLabel)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddRequest) SetInbound(inbound *bool) {
	p.Inbound = inbound
	p.require(phoneNumberManagementAddRequestFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddRequest) SetOutbound(outbound *bool) {
	p.Outbound = outbound
	p.require(phoneNumberManagementAddRequestFieldOutbound)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddRequest) SetInboundConfig(inboundConfig *PhoneNumberManagementAddRequestInboundConfig) {
	p.InboundConfig = inboundConfig
	p.require(phoneNumberManagementAddRequestFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddRequest) SetOutboundConfig(outboundConfig *PhoneNumberManagementAddRequestOutboundConfig) {
	p.OutboundConfig = outboundConfig
	p.require(phoneNumberManagementAddRequestFieldOutboundConfig)
}

// SIP inbound call configuration.
var (
	phoneNumberManagementAddRequestInboundConfigFieldAllowedAddresses = big.NewInt(1 << 0)
)

type PhoneNumberManagementAddRequestInboundConfig struct {
	// List of allowed IP addresses. For example `112.126.15.64/27`
	AllowedAddresses []string `json:"allowed_addresses,omitempty" url:"allowed_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneNumberManagementAddRequestInboundConfig) GetAllowedAddresses() []string {
	if p == nil {
		return nil
	}
	return p.AllowedAddresses
}

func (p *PhoneNumberManagementAddRequestInboundConfig) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PhoneNumberManagementAddRequestInboundConfig) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetAllowedAddresses sets the AllowedAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddRequestInboundConfig) SetAllowedAddresses(allowedAddresses []string) {
	p.AllowedAddresses = allowedAddresses
	p.require(phoneNumberManagementAddRequestInboundConfigFieldAllowedAddresses)
}

func (p *PhoneNumberManagementAddRequestInboundConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneNumberManagementAddRequestInboundConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneNumberManagementAddRequestInboundConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneNumberManagementAddRequestInboundConfig) MarshalJSON() ([]byte, error) {
	type embed PhoneNumberManagementAddRequestInboundConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneNumberManagementAddRequestInboundConfig) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// SIP outbound call configuration.
var (
	phoneNumberManagementAddRequestOutboundConfigFieldAddress   = big.NewInt(1 << 0)
	phoneNumberManagementAddRequestOutboundConfigFieldTransport = big.NewInt(1 << 1)
	phoneNumberManagementAddRequestOutboundConfigFieldPrefix    = big.NewInt(1 << 2)
)

type PhoneNumberManagementAddRequestOutboundConfig struct {
	// SIP address. For example `xxx:xxx@sip.example.com`
	Address *string `json:"address,omitempty" url:"address,omitempty"`
	// Transport protocol. For example `tls`
	Transport *string `json:"transport,omitempty" url:"transport,omitempty"`
	// Number prefix. For example `6036`
	Prefix *string `json:"prefix,omitempty" url:"prefix,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneNumberManagementAddRequestOutboundConfig) GetAddress() *string {
	if p == nil {
		return nil
	}
	return p.Address
}

func (p *PhoneNumberManagementAddRequestOutboundConfig) GetTransport() *string {
	if p == nil {
		return nil
	}
	return p.Transport
}

func (p *PhoneNumberManagementAddRequestOutboundConfig) GetPrefix() *string {
	if p == nil {
		return nil
	}
	return p.Prefix
}

func (p *PhoneNumberManagementAddRequestOutboundConfig) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PhoneNumberManagementAddRequestOutboundConfig) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddRequestOutboundConfig) SetAddress(address *string) {
	p.Address = address
	p.require(phoneNumberManagementAddRequestOutboundConfigFieldAddress)
}

// SetTransport sets the Transport field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddRequestOutboundConfig) SetTransport(transport *string) {
	p.Transport = transport
	p.require(phoneNumberManagementAddRequestOutboundConfigFieldTransport)
}

// SetPrefix sets the Prefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddRequestOutboundConfig) SetPrefix(prefix *string) {
	p.Prefix = prefix
	p.require(phoneNumberManagementAddRequestOutboundConfigFieldPrefix)
}

func (p *PhoneNumberManagementAddRequestOutboundConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneNumberManagementAddRequestOutboundConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneNumberManagementAddRequestOutboundConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneNumberManagementAddRequestOutboundConfig) MarshalJSON() ([]byte, error) {
	type embed PhoneNumberManagementAddRequestOutboundConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneNumberManagementAddRequestOutboundConfig) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Number provider:
// - `byo`: BYO (Bring Your Own)
// - `twilio`: Twilio
type PhoneNumberManagementAddRequestProvider string

const (
	PhoneNumberManagementAddRequestProviderByo    PhoneNumberManagementAddRequestProvider = "byo"
	PhoneNumberManagementAddRequestProviderTwilio PhoneNumberManagementAddRequestProvider = "twilio"
)

func NewPhoneNumberManagementAddRequestProviderFromString(s string) (PhoneNumberManagementAddRequestProvider, error) {
	switch s {
	case "byo":
		return PhoneNumberManagementAddRequestProviderByo, nil
	case "twilio":
		return PhoneNumberManagementAddRequestProviderTwilio, nil
	}
	var t PhoneNumberManagementAddRequestProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PhoneNumberManagementAddRequestProvider) Ptr() *PhoneNumberManagementAddRequestProvider {
	return &p
}

var (
	phoneNumberManagementAddResponseFieldPhoneNumber        = big.NewInt(1 << 0)
	phoneNumberManagementAddResponseFieldLabel              = big.NewInt(1 << 1)
	phoneNumberManagementAddResponseFieldProvider           = big.NewInt(1 << 2)
	phoneNumberManagementAddResponseFieldInbound            = big.NewInt(1 << 3)
	phoneNumberManagementAddResponseFieldOutbound           = big.NewInt(1 << 4)
	phoneNumberManagementAddResponseFieldAssociatedPipeline = big.NewInt(1 << 5)
)

type PhoneNumberManagementAddResponse struct {
	// A telephone number in E.164 format, used as a unique identifier.
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	// A label used to identify the number.
	Label *string `json:"label,omitempty" url:"label,omitempty"`
	// Number provider.
	Provider *string `json:"provider,omitempty" url:"provider,omitempty"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"inbound,omitempty"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"outbound,omitempty"`
	// The associated pipeline information. Returns `null` if no pipeline is associated.
	AssociatedPipeline *PhoneNumberManagementAddResponseAssociatedPipeline `json:"associated_pipeline,omitempty" url:"associated_pipeline,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneNumberManagementAddResponse) GetPhoneNumber() *string {
	if p == nil {
		return nil
	}
	return p.PhoneNumber
}

func (p *PhoneNumberManagementAddResponse) GetLabel() *string {
	if p == nil {
		return nil
	}
	return p.Label
}

func (p *PhoneNumberManagementAddResponse) GetProvider() *string {
	if p == nil {
		return nil
	}
	return p.Provider
}

func (p *PhoneNumberManagementAddResponse) GetInbound() *bool {
	if p == nil {
		return nil
	}
	return p.Inbound
}

func (p *PhoneNumberManagementAddResponse) GetOutbound() *bool {
	if p == nil {
		return nil
	}
	return p.Outbound
}

func (p *PhoneNumberManagementAddResponse) GetAssociatedPipeline() *PhoneNumberManagementAddResponseAssociatedPipeline {
	if p == nil {
		return nil
	}
	return p.AssociatedPipeline
}

func (p *PhoneNumberManagementAddResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PhoneNumberManagementAddResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddResponse) SetPhoneNumber(phoneNumber *string) {
	p.PhoneNumber = phoneNumber
	p.require(phoneNumberManagementAddResponseFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddResponse) SetLabel(label *string) {
	p.Label = label
	p.require(phoneNumberManagementAddResponseFieldLabel)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddResponse) SetProvider(provider *string) {
	p.Provider = provider
	p.require(phoneNumberManagementAddResponseFieldProvider)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddResponse) SetInbound(inbound *bool) {
	p.Inbound = inbound
	p.require(phoneNumberManagementAddResponseFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddResponse) SetOutbound(outbound *bool) {
	p.Outbound = outbound
	p.require(phoneNumberManagementAddResponseFieldOutbound)
}

// SetAssociatedPipeline sets the AssociatedPipeline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddResponse) SetAssociatedPipeline(associatedPipeline *PhoneNumberManagementAddResponseAssociatedPipeline) {
	p.AssociatedPipeline = associatedPipeline
	p.require(phoneNumberManagementAddResponseFieldAssociatedPipeline)
}

func (p *PhoneNumberManagementAddResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneNumberManagementAddResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneNumberManagementAddResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneNumberManagementAddResponse) MarshalJSON() ([]byte, error) {
	type embed PhoneNumberManagementAddResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneNumberManagementAddResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// The associated pipeline information. Returns `null` if no pipeline is associated.
var (
	phoneNumberManagementAddResponseAssociatedPipelineFieldPipelineID   = big.NewInt(1 << 0)
	phoneNumberManagementAddResponseAssociatedPipelineFieldPipelineName = big.NewInt(1 << 1)
)

type PhoneNumberManagementAddResponseAssociatedPipeline struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Pipeline name.
	PipelineName *string `json:"pipeline_name,omitempty" url:"pipeline_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneNumberManagementAddResponseAssociatedPipeline) GetPipelineID() *string {
	if p == nil {
		return nil
	}
	return p.PipelineID
}

func (p *PhoneNumberManagementAddResponseAssociatedPipeline) GetPipelineName() *string {
	if p == nil {
		return nil
	}
	return p.PipelineName
}

func (p *PhoneNumberManagementAddResponseAssociatedPipeline) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PhoneNumberManagementAddResponseAssociatedPipeline) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddResponseAssociatedPipeline) SetPipelineID(pipelineID *string) {
	p.PipelineID = pipelineID
	p.require(phoneNumberManagementAddResponseAssociatedPipelineFieldPipelineID)
}

// SetPipelineName sets the PipelineName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementAddResponseAssociatedPipeline) SetPipelineName(pipelineName *string) {
	p.PipelineName = pipelineName
	p.require(phoneNumberManagementAddResponseAssociatedPipelineFieldPipelineName)
}

func (p *PhoneNumberManagementAddResponseAssociatedPipeline) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneNumberManagementAddResponseAssociatedPipeline
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneNumberManagementAddResponseAssociatedPipeline(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneNumberManagementAddResponseAssociatedPipeline) MarshalJSON() ([]byte, error) {
	type embed PhoneNumberManagementAddResponseAssociatedPipeline
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneNumberManagementAddResponseAssociatedPipeline) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	phoneNumberManagementGetResponseFieldProvider           = big.NewInt(1 << 0)
	phoneNumberManagementGetResponseFieldPhoneNumber        = big.NewInt(1 << 1)
	phoneNumberManagementGetResponseFieldLabel              = big.NewInt(1 << 2)
	phoneNumberManagementGetResponseFieldInbound            = big.NewInt(1 << 3)
	phoneNumberManagementGetResponseFieldOutbound           = big.NewInt(1 << 4)
	phoneNumberManagementGetResponseFieldAssociatedPipeline = big.NewInt(1 << 5)
	phoneNumberManagementGetResponseFieldInboundConfig      = big.NewInt(1 << 6)
	phoneNumberManagementGetResponseFieldOutboundConfig     = big.NewInt(1 << 7)
)

type PhoneNumberManagementGetResponse struct {
	// Number provider:
	// - `byo`: BYO (Bring Your Own)
	// - `twilio`: Twilio
	Provider *PhoneNumberManagementGetResponseProvider `json:"provider,omitempty" url:"provider,omitempty"`
	// A telephone number in E.164 format, used as a unique identifier.
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	// A label used to identify the number.
	Label *string `json:"label,omitempty" url:"label,omitempty"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"inbound,omitempty"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"outbound,omitempty"`
	// The associated pipeline information. Returns `null` if no pipeline is associated.
	AssociatedPipeline *PhoneNumberManagementGetResponseAssociatedPipeline `json:"associated_pipeline,omitempty" url:"associated_pipeline,omitempty"`
	// SIP inbound call configuration details. Returns `null` if not configured.
	InboundConfig map[string]interface{} `json:"inbound_config,omitempty" url:"inbound_config,omitempty"`
	// SIP outbound call configuration details. Returns `null` if not configured.
	OutboundConfig map[string]interface{} `json:"outbound_config,omitempty" url:"outbound_config,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneNumberManagementGetResponse) GetProvider() *PhoneNumberManagementGetResponseProvider {
	if p == nil {
		return nil
	}
	return p.Provider
}

func (p *PhoneNumberManagementGetResponse) GetPhoneNumber() *string {
	if p == nil {
		return nil
	}
	return p.PhoneNumber
}

func (p *PhoneNumberManagementGetResponse) GetLabel() *string {
	if p == nil {
		return nil
	}
	return p.Label
}

func (p *PhoneNumberManagementGetResponse) GetInbound() *bool {
	if p == nil {
		return nil
	}
	return p.Inbound
}

func (p *PhoneNumberManagementGetResponse) GetOutbound() *bool {
	if p == nil {
		return nil
	}
	return p.Outbound
}

func (p *PhoneNumberManagementGetResponse) GetAssociatedPipeline() *PhoneNumberManagementGetResponseAssociatedPipeline {
	if p == nil {
		return nil
	}
	return p.AssociatedPipeline
}

func (p *PhoneNumberManagementGetResponse) GetInboundConfig() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.InboundConfig
}

func (p *PhoneNumberManagementGetResponse) GetOutboundConfig() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.OutboundConfig
}

func (p *PhoneNumberManagementGetResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PhoneNumberManagementGetResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementGetResponse) SetProvider(provider *PhoneNumberManagementGetResponseProvider) {
	p.Provider = provider
	p.require(phoneNumberManagementGetResponseFieldProvider)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementGetResponse) SetPhoneNumber(phoneNumber *string) {
	p.PhoneNumber = phoneNumber
	p.require(phoneNumberManagementGetResponseFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementGetResponse) SetLabel(label *string) {
	p.Label = label
	p.require(phoneNumberManagementGetResponseFieldLabel)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementGetResponse) SetInbound(inbound *bool) {
	p.Inbound = inbound
	p.require(phoneNumberManagementGetResponseFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementGetResponse) SetOutbound(outbound *bool) {
	p.Outbound = outbound
	p.require(phoneNumberManagementGetResponseFieldOutbound)
}

// SetAssociatedPipeline sets the AssociatedPipeline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementGetResponse) SetAssociatedPipeline(associatedPipeline *PhoneNumberManagementGetResponseAssociatedPipeline) {
	p.AssociatedPipeline = associatedPipeline
	p.require(phoneNumberManagementGetResponseFieldAssociatedPipeline)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementGetResponse) SetInboundConfig(inboundConfig map[string]interface{}) {
	p.InboundConfig = inboundConfig
	p.require(phoneNumberManagementGetResponseFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementGetResponse) SetOutboundConfig(outboundConfig map[string]interface{}) {
	p.OutboundConfig = outboundConfig
	p.require(phoneNumberManagementGetResponseFieldOutboundConfig)
}

func (p *PhoneNumberManagementGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneNumberManagementGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneNumberManagementGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneNumberManagementGetResponse) MarshalJSON() ([]byte, error) {
	type embed PhoneNumberManagementGetResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneNumberManagementGetResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// The associated pipeline information. Returns `null` if no pipeline is associated.
var (
	phoneNumberManagementGetResponseAssociatedPipelineFieldPipelineID   = big.NewInt(1 << 0)
	phoneNumberManagementGetResponseAssociatedPipelineFieldPipelineName = big.NewInt(1 << 1)
)

type PhoneNumberManagementGetResponseAssociatedPipeline struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Pipeline name.
	PipelineName *string `json:"pipeline_name,omitempty" url:"pipeline_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneNumberManagementGetResponseAssociatedPipeline) GetPipelineID() *string {
	if p == nil {
		return nil
	}
	return p.PipelineID
}

func (p *PhoneNumberManagementGetResponseAssociatedPipeline) GetPipelineName() *string {
	if p == nil {
		return nil
	}
	return p.PipelineName
}

func (p *PhoneNumberManagementGetResponseAssociatedPipeline) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PhoneNumberManagementGetResponseAssociatedPipeline) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementGetResponseAssociatedPipeline) SetPipelineID(pipelineID *string) {
	p.PipelineID = pipelineID
	p.require(phoneNumberManagementGetResponseAssociatedPipelineFieldPipelineID)
}

// SetPipelineName sets the PipelineName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementGetResponseAssociatedPipeline) SetPipelineName(pipelineName *string) {
	p.PipelineName = pipelineName
	p.require(phoneNumberManagementGetResponseAssociatedPipelineFieldPipelineName)
}

func (p *PhoneNumberManagementGetResponseAssociatedPipeline) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneNumberManagementGetResponseAssociatedPipeline
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneNumberManagementGetResponseAssociatedPipeline(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneNumberManagementGetResponseAssociatedPipeline) MarshalJSON() ([]byte, error) {
	type embed PhoneNumberManagementGetResponseAssociatedPipeline
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneNumberManagementGetResponseAssociatedPipeline) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Number provider:
// - `byo`: BYO (Bring Your Own)
// - `twilio`: Twilio
type PhoneNumberManagementGetResponseProvider string

const (
	PhoneNumberManagementGetResponseProviderByo    PhoneNumberManagementGetResponseProvider = "byo"
	PhoneNumberManagementGetResponseProviderTwilio PhoneNumberManagementGetResponseProvider = "twilio"
)

func NewPhoneNumberManagementGetResponseProviderFromString(s string) (PhoneNumberManagementGetResponseProvider, error) {
	switch s {
	case "byo":
		return PhoneNumberManagementGetResponseProviderByo, nil
	case "twilio":
		return PhoneNumberManagementGetResponseProviderTwilio, nil
	}
	var t PhoneNumberManagementGetResponseProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PhoneNumberManagementGetResponseProvider) Ptr() *PhoneNumberManagementGetResponseProvider {
	return &p
}

var (
	phoneNumberManagementListResponseItemFieldProvider           = big.NewInt(1 << 0)
	phoneNumberManagementListResponseItemFieldPhoneNumber        = big.NewInt(1 << 1)
	phoneNumberManagementListResponseItemFieldLabel              = big.NewInt(1 << 2)
	phoneNumberManagementListResponseItemFieldInbound            = big.NewInt(1 << 3)
	phoneNumberManagementListResponseItemFieldOutbound           = big.NewInt(1 << 4)
	phoneNumberManagementListResponseItemFieldAssociatedPipeline = big.NewInt(1 << 5)
	phoneNumberManagementListResponseItemFieldInboundConfig      = big.NewInt(1 << 6)
	phoneNumberManagementListResponseItemFieldOutboundConfig     = big.NewInt(1 << 7)
)

type PhoneNumberManagementListResponseItem struct {
	// Number provider:
	// - `byo`: BYO (Bring Your Own).
	// - `twilio`: Twilio.
	Provider *PhoneNumberManagementListResponseItemProvider `json:"provider,omitempty" url:"provider,omitempty"`
	// A telephone number in E.164 format, used as a unique identifier.
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	// A label used to identify the number.
	Label *string `json:"label,omitempty" url:"label,omitempty"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"inbound,omitempty"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"outbound,omitempty"`
	// The associated pipeline information. Returns `null` if no pipeline is associated.
	AssociatedPipeline *PhoneNumberManagementListResponseItemAssociatedPipeline `json:"associated_pipeline,omitempty" url:"associated_pipeline,omitempty"`
	// SIP inbound call configuration details. Returns `null` if not configured.
	InboundConfig map[string]interface{} `json:"inbound_config,omitempty" url:"inbound_config,omitempty"`
	// SIP outbound call configuration details. Returns `null` if not configured.
	OutboundConfig map[string]interface{} `json:"outbound_config,omitempty" url:"outbound_config,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneNumberManagementListResponseItem) GetProvider() *PhoneNumberManagementListResponseItemProvider {
	if p == nil {
		return nil
	}
	return p.Provider
}

func (p *PhoneNumberManagementListResponseItem) GetPhoneNumber() *string {
	if p == nil {
		return nil
	}
	return p.PhoneNumber
}

func (p *PhoneNumberManagementListResponseItem) GetLabel() *string {
	if p == nil {
		return nil
	}
	return p.Label
}

func (p *PhoneNumberManagementListResponseItem) GetInbound() *bool {
	if p == nil {
		return nil
	}
	return p.Inbound
}

func (p *PhoneNumberManagementListResponseItem) GetOutbound() *bool {
	if p == nil {
		return nil
	}
	return p.Outbound
}

func (p *PhoneNumberManagementListResponseItem) GetAssociatedPipeline() *PhoneNumberManagementListResponseItemAssociatedPipeline {
	if p == nil {
		return nil
	}
	return p.AssociatedPipeline
}

func (p *PhoneNumberManagementListResponseItem) GetInboundConfig() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.InboundConfig
}

func (p *PhoneNumberManagementListResponseItem) GetOutboundConfig() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.OutboundConfig
}

func (p *PhoneNumberManagementListResponseItem) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PhoneNumberManagementListResponseItem) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementListResponseItem) SetProvider(provider *PhoneNumberManagementListResponseItemProvider) {
	p.Provider = provider
	p.require(phoneNumberManagementListResponseItemFieldProvider)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementListResponseItem) SetPhoneNumber(phoneNumber *string) {
	p.PhoneNumber = phoneNumber
	p.require(phoneNumberManagementListResponseItemFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementListResponseItem) SetLabel(label *string) {
	p.Label = label
	p.require(phoneNumberManagementListResponseItemFieldLabel)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementListResponseItem) SetInbound(inbound *bool) {
	p.Inbound = inbound
	p.require(phoneNumberManagementListResponseItemFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementListResponseItem) SetOutbound(outbound *bool) {
	p.Outbound = outbound
	p.require(phoneNumberManagementListResponseItemFieldOutbound)
}

// SetAssociatedPipeline sets the AssociatedPipeline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementListResponseItem) SetAssociatedPipeline(associatedPipeline *PhoneNumberManagementListResponseItemAssociatedPipeline) {
	p.AssociatedPipeline = associatedPipeline
	p.require(phoneNumberManagementListResponseItemFieldAssociatedPipeline)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementListResponseItem) SetInboundConfig(inboundConfig map[string]interface{}) {
	p.InboundConfig = inboundConfig
	p.require(phoneNumberManagementListResponseItemFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementListResponseItem) SetOutboundConfig(outboundConfig map[string]interface{}) {
	p.OutboundConfig = outboundConfig
	p.require(phoneNumberManagementListResponseItemFieldOutboundConfig)
}

func (p *PhoneNumberManagementListResponseItem) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneNumberManagementListResponseItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneNumberManagementListResponseItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneNumberManagementListResponseItem) MarshalJSON() ([]byte, error) {
	type embed PhoneNumberManagementListResponseItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneNumberManagementListResponseItem) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// The associated pipeline information. Returns `null` if no pipeline is associated.
var (
	phoneNumberManagementListResponseItemAssociatedPipelineFieldPipelineID   = big.NewInt(1 << 0)
	phoneNumberManagementListResponseItemAssociatedPipelineFieldPipelineName = big.NewInt(1 << 1)
)

type PhoneNumberManagementListResponseItemAssociatedPipeline struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Pipeline name.
	PipelineName *string `json:"pipeline_name,omitempty" url:"pipeline_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneNumberManagementListResponseItemAssociatedPipeline) GetPipelineID() *string {
	if p == nil {
		return nil
	}
	return p.PipelineID
}

func (p *PhoneNumberManagementListResponseItemAssociatedPipeline) GetPipelineName() *string {
	if p == nil {
		return nil
	}
	return p.PipelineName
}

func (p *PhoneNumberManagementListResponseItemAssociatedPipeline) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PhoneNumberManagementListResponseItemAssociatedPipeline) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementListResponseItemAssociatedPipeline) SetPipelineID(pipelineID *string) {
	p.PipelineID = pipelineID
	p.require(phoneNumberManagementListResponseItemAssociatedPipelineFieldPipelineID)
}

// SetPipelineName sets the PipelineName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementListResponseItemAssociatedPipeline) SetPipelineName(pipelineName *string) {
	p.PipelineName = pipelineName
	p.require(phoneNumberManagementListResponseItemAssociatedPipelineFieldPipelineName)
}

func (p *PhoneNumberManagementListResponseItemAssociatedPipeline) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneNumberManagementListResponseItemAssociatedPipeline
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneNumberManagementListResponseItemAssociatedPipeline(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneNumberManagementListResponseItemAssociatedPipeline) MarshalJSON() ([]byte, error) {
	type embed PhoneNumberManagementListResponseItemAssociatedPipeline
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneNumberManagementListResponseItemAssociatedPipeline) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Number provider:
// - `byo`: BYO (Bring Your Own).
// - `twilio`: Twilio.
type PhoneNumberManagementListResponseItemProvider string

const (
	PhoneNumberManagementListResponseItemProviderByo    PhoneNumberManagementListResponseItemProvider = "byo"
	PhoneNumberManagementListResponseItemProviderTwilio PhoneNumberManagementListResponseItemProvider = "twilio"
)

func NewPhoneNumberManagementListResponseItemProviderFromString(s string) (PhoneNumberManagementListResponseItemProvider, error) {
	switch s {
	case "byo":
		return PhoneNumberManagementListResponseItemProviderByo, nil
	case "twilio":
		return PhoneNumberManagementListResponseItemProviderTwilio, nil
	}
	var t PhoneNumberManagementListResponseItemProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PhoneNumberManagementListResponseItemProvider) Ptr() *PhoneNumberManagementListResponseItemProvider {
	return &p
}

// Update inbound call configuration. Passing `null` will clear the configuration.
var (
	phoneNumberManagementUpdateRequestInboundConfigFieldPipelineID = big.NewInt(1 << 0)
)

type PhoneNumberManagementUpdateRequestInboundConfig struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneNumberManagementUpdateRequestInboundConfig) GetPipelineID() *string {
	if p == nil {
		return nil
	}
	return p.PipelineID
}

func (p *PhoneNumberManagementUpdateRequestInboundConfig) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PhoneNumberManagementUpdateRequestInboundConfig) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementUpdateRequestInboundConfig) SetPipelineID(pipelineID *string) {
	p.PipelineID = pipelineID
	p.require(phoneNumberManagementUpdateRequestInboundConfigFieldPipelineID)
}

func (p *PhoneNumberManagementUpdateRequestInboundConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneNumberManagementUpdateRequestInboundConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneNumberManagementUpdateRequestInboundConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneNumberManagementUpdateRequestInboundConfig) MarshalJSON() ([]byte, error) {
	type embed PhoneNumberManagementUpdateRequestInboundConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneNumberManagementUpdateRequestInboundConfig) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Update outbound call configuration. Passing `null` will clear the configuration.
var (
	phoneNumberManagementUpdateRequestOutboundConfigFieldPipelineID = big.NewInt(1 << 0)
)

type PhoneNumberManagementUpdateRequestOutboundConfig struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneNumberManagementUpdateRequestOutboundConfig) GetPipelineID() *string {
	if p == nil {
		return nil
	}
	return p.PipelineID
}

func (p *PhoneNumberManagementUpdateRequestOutboundConfig) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PhoneNumberManagementUpdateRequestOutboundConfig) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementUpdateRequestOutboundConfig) SetPipelineID(pipelineID *string) {
	p.PipelineID = pipelineID
	p.require(phoneNumberManagementUpdateRequestOutboundConfigFieldPipelineID)
}

func (p *PhoneNumberManagementUpdateRequestOutboundConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneNumberManagementUpdateRequestOutboundConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneNumberManagementUpdateRequestOutboundConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneNumberManagementUpdateRequestOutboundConfig) MarshalJSON() ([]byte, error) {
	type embed PhoneNumberManagementUpdateRequestOutboundConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneNumberManagementUpdateRequestOutboundConfig) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	phoneNumberManagementUpdateResponseFieldProvider           = big.NewInt(1 << 0)
	phoneNumberManagementUpdateResponseFieldPhoneNumber        = big.NewInt(1 << 1)
	phoneNumberManagementUpdateResponseFieldLabel              = big.NewInt(1 << 2)
	phoneNumberManagementUpdateResponseFieldInbound            = big.NewInt(1 << 3)
	phoneNumberManagementUpdateResponseFieldOutbound           = big.NewInt(1 << 4)
	phoneNumberManagementUpdateResponseFieldAssociatedPipeline = big.NewInt(1 << 5)
	phoneNumberManagementUpdateResponseFieldInboundConfig      = big.NewInt(1 << 6)
	phoneNumberManagementUpdateResponseFieldOutboundConfig     = big.NewInt(1 << 7)
)

type PhoneNumberManagementUpdateResponse struct {
	// Number provider:
	// - `byo`: BYO (Bring Your Own)
	// - `twilio`: Twilio
	Provider *PhoneNumberManagementUpdateResponseProvider `json:"provider,omitempty" url:"provider,omitempty"`
	// A telephone number in E.164 format, used as a unique identifier.
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	// A label used to identify the number.
	Label *string `json:"label,omitempty" url:"label,omitempty"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"inbound,omitempty"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"outbound,omitempty"`
	// The associated pipeline information. Returns `null` if no pipeline is associated.
	AssociatedPipeline *PhoneNumberManagementUpdateResponseAssociatedPipeline `json:"associated_pipeline,omitempty" url:"associated_pipeline,omitempty"`
	// SIP inbound call configuration details. Returns `null` if not configured.
	InboundConfig map[string]interface{} `json:"inbound_config,omitempty" url:"inbound_config,omitempty"`
	// SIP outbound call configuration details. Returns `null` if not configured.
	OutboundConfig map[string]interface{} `json:"outbound_config,omitempty" url:"outbound_config,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneNumberManagementUpdateResponse) GetProvider() *PhoneNumberManagementUpdateResponseProvider {
	if p == nil {
		return nil
	}
	return p.Provider
}

func (p *PhoneNumberManagementUpdateResponse) GetPhoneNumber() *string {
	if p == nil {
		return nil
	}
	return p.PhoneNumber
}

func (p *PhoneNumberManagementUpdateResponse) GetLabel() *string {
	if p == nil {
		return nil
	}
	return p.Label
}

func (p *PhoneNumberManagementUpdateResponse) GetInbound() *bool {
	if p == nil {
		return nil
	}
	return p.Inbound
}

func (p *PhoneNumberManagementUpdateResponse) GetOutbound() *bool {
	if p == nil {
		return nil
	}
	return p.Outbound
}

func (p *PhoneNumberManagementUpdateResponse) GetAssociatedPipeline() *PhoneNumberManagementUpdateResponseAssociatedPipeline {
	if p == nil {
		return nil
	}
	return p.AssociatedPipeline
}

func (p *PhoneNumberManagementUpdateResponse) GetInboundConfig() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.InboundConfig
}

func (p *PhoneNumberManagementUpdateResponse) GetOutboundConfig() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.OutboundConfig
}

func (p *PhoneNumberManagementUpdateResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PhoneNumberManagementUpdateResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementUpdateResponse) SetProvider(provider *PhoneNumberManagementUpdateResponseProvider) {
	p.Provider = provider
	p.require(phoneNumberManagementUpdateResponseFieldProvider)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementUpdateResponse) SetPhoneNumber(phoneNumber *string) {
	p.PhoneNumber = phoneNumber
	p.require(phoneNumberManagementUpdateResponseFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementUpdateResponse) SetLabel(label *string) {
	p.Label = label
	p.require(phoneNumberManagementUpdateResponseFieldLabel)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementUpdateResponse) SetInbound(inbound *bool) {
	p.Inbound = inbound
	p.require(phoneNumberManagementUpdateResponseFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementUpdateResponse) SetOutbound(outbound *bool) {
	p.Outbound = outbound
	p.require(phoneNumberManagementUpdateResponseFieldOutbound)
}

// SetAssociatedPipeline sets the AssociatedPipeline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementUpdateResponse) SetAssociatedPipeline(associatedPipeline *PhoneNumberManagementUpdateResponseAssociatedPipeline) {
	p.AssociatedPipeline = associatedPipeline
	p.require(phoneNumberManagementUpdateResponseFieldAssociatedPipeline)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementUpdateResponse) SetInboundConfig(inboundConfig map[string]interface{}) {
	p.InboundConfig = inboundConfig
	p.require(phoneNumberManagementUpdateResponseFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementUpdateResponse) SetOutboundConfig(outboundConfig map[string]interface{}) {
	p.OutboundConfig = outboundConfig
	p.require(phoneNumberManagementUpdateResponseFieldOutboundConfig)
}

func (p *PhoneNumberManagementUpdateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneNumberManagementUpdateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneNumberManagementUpdateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneNumberManagementUpdateResponse) MarshalJSON() ([]byte, error) {
	type embed PhoneNumberManagementUpdateResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneNumberManagementUpdateResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// The associated pipeline information. Returns `null` if no pipeline is associated.
var (
	phoneNumberManagementUpdateResponseAssociatedPipelineFieldPipelineID   = big.NewInt(1 << 0)
	phoneNumberManagementUpdateResponseAssociatedPipelineFieldPipelineName = big.NewInt(1 << 1)
)

type PhoneNumberManagementUpdateResponseAssociatedPipeline struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Pipeline name.
	PipelineName *string `json:"pipeline_name,omitempty" url:"pipeline_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneNumberManagementUpdateResponseAssociatedPipeline) GetPipelineID() *string {
	if p == nil {
		return nil
	}
	return p.PipelineID
}

func (p *PhoneNumberManagementUpdateResponseAssociatedPipeline) GetPipelineName() *string {
	if p == nil {
		return nil
	}
	return p.PipelineName
}

func (p *PhoneNumberManagementUpdateResponseAssociatedPipeline) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PhoneNumberManagementUpdateResponseAssociatedPipeline) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementUpdateResponseAssociatedPipeline) SetPipelineID(pipelineID *string) {
	p.PipelineID = pipelineID
	p.require(phoneNumberManagementUpdateResponseAssociatedPipelineFieldPipelineID)
}

// SetPipelineName sets the PipelineName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementUpdateResponseAssociatedPipeline) SetPipelineName(pipelineName *string) {
	p.PipelineName = pipelineName
	p.require(phoneNumberManagementUpdateResponseAssociatedPipelineFieldPipelineName)
}

func (p *PhoneNumberManagementUpdateResponseAssociatedPipeline) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneNumberManagementUpdateResponseAssociatedPipeline
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneNumberManagementUpdateResponseAssociatedPipeline(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneNumberManagementUpdateResponseAssociatedPipeline) MarshalJSON() ([]byte, error) {
	type embed PhoneNumberManagementUpdateResponseAssociatedPipeline
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneNumberManagementUpdateResponseAssociatedPipeline) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Number provider:
// - `byo`: BYO (Bring Your Own)
// - `twilio`: Twilio
type PhoneNumberManagementUpdateResponseProvider string

const (
	PhoneNumberManagementUpdateResponseProviderByo    PhoneNumberManagementUpdateResponseProvider = "byo"
	PhoneNumberManagementUpdateResponseProviderTwilio PhoneNumberManagementUpdateResponseProvider = "twilio"
)

func NewPhoneNumberManagementUpdateResponseProviderFromString(s string) (PhoneNumberManagementUpdateResponseProvider, error) {
	switch s {
	case "byo":
		return PhoneNumberManagementUpdateResponseProviderByo, nil
	case "twilio":
		return PhoneNumberManagementUpdateResponseProviderTwilio, nil
	}
	var t PhoneNumberManagementUpdateResponseProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PhoneNumberManagementUpdateResponseProvider) Ptr() *PhoneNumberManagementUpdateResponseProvider {
	return &p
}

var (
	phoneNumberManagementUpdateRequestFieldInboundConfig  = big.NewInt(1 << 0)
	phoneNumberManagementUpdateRequestFieldOutboundConfig = big.NewInt(1 << 1)
)

type PhoneNumberManagementUpdateRequest struct {
	// Update inbound call configuration. Passing `null` will clear the configuration.
	InboundConfig *PhoneNumberManagementUpdateRequestInboundConfig `json:"inbound_config,omitempty" url:"-"`
	// Update outbound call configuration. Passing `null` will clear the configuration.
	OutboundConfig *PhoneNumberManagementUpdateRequestOutboundConfig `json:"outbound_config,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PhoneNumberManagementUpdateRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementUpdateRequest) SetInboundConfig(inboundConfig *PhoneNumberManagementUpdateRequestInboundConfig) {
	p.InboundConfig = inboundConfig
	p.require(phoneNumberManagementUpdateRequestFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneNumberManagementUpdateRequest) SetOutboundConfig(outboundConfig *PhoneNumberManagementUpdateRequestOutboundConfig) {
	p.OutboundConfig = outboundConfig
	p.require(phoneNumberManagementUpdateRequestFieldOutboundConfig)
}
