// Code generated by Fern. DO NOT EDIT.

package Agora

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/fern-demo/agoraio-go-sdk/v505/internal"
	big "math/big"
)

var (
	telephonyCallRequestFieldName       = big.NewInt(1 << 0)
	telephonyCallRequestFieldSip        = big.NewInt(1 << 1)
	telephonyCallRequestFieldPipelineID = big.NewInt(1 << 2)
	telephonyCallRequestFieldProperties = big.NewInt(1 << 3)
)

type TelephonyCallRequest struct {
	// The name identifier of the call session.
	Name string `json:"name" url:"-"`
	// SIP (Session Initiation Protocol) call configuration object.
	Sip *TelephonyCallRequestSip `json:"sip,omitempty" url:"-"`
	// The unique ID of a published project in AI Studio.
	PipelineID *string `json:"pipeline_id,omitempty" url:"-"`
	// Call attribute configuration. The content of this field varies depending on the invocation method:
	// - **Using pipeline ID**: Simply pass in `channel`, `token`, and `agent_rtc_uid`.
	// - **Using complete configuration**: Pass in the complete parameters of the [Start a conversational AI agent](https://docs.agora.io/en/conversational-ai/rest-api/agent/join) `properties`, including all required fields such as `channel`, `token`, `agent_rtc_uid`, `remote_rtc_uids`, `tts`, and `llm`.
	Properties *TelephonyCallRequestProperties `json:"properties,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TelephonyCallRequest) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyCallRequest) SetName(name string) {
	t.Name = name
	t.require(telephonyCallRequestFieldName)
}

// SetSip sets the Sip field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyCallRequest) SetSip(sip *TelephonyCallRequestSip) {
	t.Sip = sip
	t.require(telephonyCallRequestFieldSip)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyCallRequest) SetPipelineID(pipelineID *string) {
	t.PipelineID = pipelineID
	t.require(telephonyCallRequestFieldPipelineID)
}

// SetProperties sets the Properties field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyCallRequest) SetProperties(properties *TelephonyCallRequestProperties) {
	t.Properties = properties
	t.require(telephonyCallRequestFieldProperties)
}

type TelephonyHangupRequest struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TelephonyHangupRequest) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

var (
	telephonyListRequestFieldNumber   = big.NewInt(1 << 0)
	telephonyListRequestFieldFromTime = big.NewInt(1 << 1)
	telephonyListRequestFieldToTime   = big.NewInt(1 << 2)
	telephonyListRequestFieldType     = big.NewInt(1 << 3)
	telephonyListRequestFieldLimit    = big.NewInt(1 << 4)
	telephonyListRequestFieldCursor   = big.NewInt(1 << 5)
)

type TelephonyListRequest struct {
	// Filter by phone number. Can be either the calling number or the called number.
	Number *string `json:"-" url:"number,omitempty"`
	// Query list start timestamp (in seconds). Default is 60 days ago.
	FromTime *int `json:"-" url:"from_time,omitempty"`
	// Query list end timestamp (in seconds). Default is current time.
	ToTime *int `json:"-" url:"to_time,omitempty"`
	// Call type filter:
	// - `inbound`: Inbound call.
	// - `outbound`: Outbound call.
	//
	// If not specified, all call types are returned.
	Type *TelephonyListRequestType `json:"-" url:"type,omitempty"`
	// Maximum number of items returned in a single page.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Pagination cursor. Use the `agent_id` from the previous page as the cursor for the next page.
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TelephonyListRequest) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetNumber sets the Number field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListRequest) SetNumber(number *string) {
	t.Number = number
	t.require(telephonyListRequestFieldNumber)
}

// SetFromTime sets the FromTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListRequest) SetFromTime(fromTime *int) {
	t.FromTime = fromTime
	t.require(telephonyListRequestFieldFromTime)
}

// SetToTime sets the ToTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListRequest) SetToTime(toTime *int) {
	t.ToTime = toTime
	t.require(telephonyListRequestFieldToTime)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListRequest) SetType(type_ *TelephonyListRequestType) {
	t.Type = type_
	t.require(telephonyListRequestFieldType)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListRequest) SetLimit(limit *int) {
	t.Limit = limit
	t.require(telephonyListRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListRequest) SetCursor(cursor *string) {
	t.Cursor = cursor
	t.require(telephonyListRequestFieldCursor)
}

// Call attribute configuration. The content of this field varies depending on the invocation method:
// - **Using pipeline ID**: Simply pass in `channel`, `token`, and `agent_rtc_uid`.
// - **Using complete configuration**: Pass in the complete parameters of the [Start a conversational AI agent](https://docs.agora.io/en/conversational-ai/rest-api/agent/join) `properties`, including all required fields such as `channel`, `token`, `agent_rtc_uid`, `remote_rtc_uids`, `tts`, and `llm`.
var (
	telephonyCallRequestPropertiesFieldChannel     = big.NewInt(1 << 0)
	telephonyCallRequestPropertiesFieldToken       = big.NewInt(1 << 1)
	telephonyCallRequestPropertiesFieldAgentRtcUID = big.NewInt(1 << 2)
)

type TelephonyCallRequestProperties struct {
	// RTC channel name.
	Channel string `json:"channel" url:"channel"`
	// RTC Channel Token.
	Token string `json:"token" url:"token"`
	// The agent's user ID in the RTC channel.
	AgentRtcUID string `json:"agent_rtc_uid" url:"agent_rtc_uid"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (t *TelephonyCallRequestProperties) GetChannel() string {
	if t == nil {
		return ""
	}
	return t.Channel
}

func (t *TelephonyCallRequestProperties) GetToken() string {
	if t == nil {
		return ""
	}
	return t.Token
}

func (t *TelephonyCallRequestProperties) GetAgentRtcUID() string {
	if t == nil {
		return ""
	}
	return t.AgentRtcUID
}

func (t *TelephonyCallRequestProperties) GetExtraProperties() map[string]interface{} {
	return t.ExtraProperties
}

func (t *TelephonyCallRequestProperties) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetChannel sets the Channel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyCallRequestProperties) SetChannel(channel string) {
	t.Channel = channel
	t.require(telephonyCallRequestPropertiesFieldChannel)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyCallRequestProperties) SetToken(token string) {
	t.Token = token
	t.require(telephonyCallRequestPropertiesFieldToken)
}

// SetAgentRtcUID sets the AgentRtcUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyCallRequestProperties) SetAgentRtcUID(agentRtcUID string) {
	t.AgentRtcUID = agentRtcUID
	t.require(telephonyCallRequestPropertiesFieldAgentRtcUID)
}

func (t *TelephonyCallRequestProperties) UnmarshalJSON(data []byte) error {
	type embed TelephonyCallRequestProperties
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*t = TelephonyCallRequestProperties(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.ExtraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TelephonyCallRequestProperties) MarshalJSON() ([]byte, error) {
	type embed TelephonyCallRequestProperties
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, t.ExtraProperties)
}

func (t *TelephonyCallRequestProperties) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// SIP (Session Initiation Protocol) call configuration object.
var (
	telephonyCallRequestSipFieldToNumber    = big.NewInt(1 << 0)
	telephonyCallRequestSipFieldFromNumber  = big.NewInt(1 << 1)
	telephonyCallRequestSipFieldSipRtcUID   = big.NewInt(1 << 2)
	telephonyCallRequestSipFieldSipRtcToken = big.NewInt(1 << 3)
)

type TelephonyCallRequestSip struct {
	// Called number (target phone number), in E.164 format.
	ToNumber string `json:"to_number" url:"to_number"`
	// Caller ID (the number that initiated the call), in E.164 format.
	FromNumber string `json:"from_number" url:"from_number"`
	// The RTC UID used by the SIP gateway.
	SipRtcUID string `json:"sip_rtc_uid" url:"sip_rtc_uid"`
	// The RTC token used by the SIP gateway.
	SipRtcToken string `json:"sip_rtc_token" url:"sip_rtc_token"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TelephonyCallRequestSip) GetToNumber() string {
	if t == nil {
		return ""
	}
	return t.ToNumber
}

func (t *TelephonyCallRequestSip) GetFromNumber() string {
	if t == nil {
		return ""
	}
	return t.FromNumber
}

func (t *TelephonyCallRequestSip) GetSipRtcUID() string {
	if t == nil {
		return ""
	}
	return t.SipRtcUID
}

func (t *TelephonyCallRequestSip) GetSipRtcToken() string {
	if t == nil {
		return ""
	}
	return t.SipRtcToken
}

func (t *TelephonyCallRequestSip) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TelephonyCallRequestSip) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetToNumber sets the ToNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyCallRequestSip) SetToNumber(toNumber string) {
	t.ToNumber = toNumber
	t.require(telephonyCallRequestSipFieldToNumber)
}

// SetFromNumber sets the FromNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyCallRequestSip) SetFromNumber(fromNumber string) {
	t.FromNumber = fromNumber
	t.require(telephonyCallRequestSipFieldFromNumber)
}

// SetSipRtcUID sets the SipRtcUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyCallRequestSip) SetSipRtcUID(sipRtcUID string) {
	t.SipRtcUID = sipRtcUID
	t.require(telephonyCallRequestSipFieldSipRtcUID)
}

// SetSipRtcToken sets the SipRtcToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyCallRequestSip) SetSipRtcToken(sipRtcToken string) {
	t.SipRtcToken = sipRtcToken
	t.require(telephonyCallRequestSipFieldSipRtcToken)
}

func (t *TelephonyCallRequestSip) UnmarshalJSON(data []byte) error {
	type unmarshaler TelephonyCallRequestSip
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TelephonyCallRequestSip(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TelephonyCallRequestSip) MarshalJSON() ([]byte, error) {
	type embed TelephonyCallRequestSip
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TelephonyCallRequestSip) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	telephonyCallResponseFieldAgentID = big.NewInt(1 << 0)
)

type TelephonyCallResponse struct {
	// Unique ID of the agent instance. Use it to query call status, control call flow, and perform other operations.
	AgentID *string `json:"agent_id,omitempty" url:"agent_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TelephonyCallResponse) GetAgentID() *string {
	if t == nil {
		return nil
	}
	return t.AgentID
}

func (t *TelephonyCallResponse) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TelephonyCallResponse) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetAgentID sets the AgentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyCallResponse) SetAgentID(agentID *string) {
	t.AgentID = agentID
	t.require(telephonyCallResponseFieldAgentID)
}

func (t *TelephonyCallResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TelephonyCallResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TelephonyCallResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TelephonyCallResponse) MarshalJSON() ([]byte, error) {
	type embed TelephonyCallResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TelephonyCallResponse) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	telephonyGetResponseFieldToNumber   = big.NewInt(1 << 0)
	telephonyGetResponseFieldFromNumber = big.NewInt(1 << 1)
	telephonyGetResponseFieldPipelineID = big.NewInt(1 << 2)
	telephonyGetResponseFieldType       = big.NewInt(1 << 3)
	telephonyGetResponseFieldAgentID    = big.NewInt(1 << 4)
	telephonyGetResponseFieldChannel    = big.NewInt(1 << 5)
	telephonyGetResponseFieldReason     = big.NewInt(1 << 6)
	telephonyGetResponseFieldCreateTs   = big.NewInt(1 << 7)
	telephonyGetResponseFieldState      = big.NewInt(1 << 8)
	telephonyGetResponseFieldStopTs     = big.NewInt(1 << 9)
)

type TelephonyGetResponse struct {
	// The number called.
	ToNumber *string `json:"to_number,omitempty" url:"to_number,omitempty"`
	// Caller ID.
	FromNumber *string `json:"from_number,omitempty" url:"from_number,omitempty"`
	// The unique ID of a published project in AI Studio. Can be obtained in AI Studio - Project - Release Management.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Call type:
	// - `inbound`: Inbound call.
	// - `outbound`: Outbound call.
	Type *TelephonyGetResponseType `json:"type,omitempty" url:"type,omitempty"`
	// A unique identifier for the call session.
	AgentID *string `json:"agent_id,omitempty" url:"agent_id,omitempty"`
	// RTC channel name.
	Channel *string `json:"channel,omitempty" url:"channel,omitempty"`
	// Reason for call ending:
	// - `request`: Actively hung up.
	// - `hangup`: The other party hung up.
	// - `failed`: Call failed.
	Reason *TelephonyGetResponseReason `json:"reason,omitempty" url:"reason,omitempty"`
	// Call creation timestamp (in seconds).
	CreateTs *int `json:"create_ts,omitempty" url:"create_ts,omitempty"`
	// Call status:
	// - `answered`: The call was answered.
	// - `hangup`: The call was disconnected.
	State *TelephonyGetResponseState `json:"state,omitempty" url:"state,omitempty"`
	// Call end timestamp (in seconds). Returns `0` or `null` if the call has not ended.
	StopTs *int `json:"stop_ts,omitempty" url:"stop_ts,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TelephonyGetResponse) GetToNumber() *string {
	if t == nil {
		return nil
	}
	return t.ToNumber
}

func (t *TelephonyGetResponse) GetFromNumber() *string {
	if t == nil {
		return nil
	}
	return t.FromNumber
}

func (t *TelephonyGetResponse) GetPipelineID() *string {
	if t == nil {
		return nil
	}
	return t.PipelineID
}

func (t *TelephonyGetResponse) GetType() *TelephonyGetResponseType {
	if t == nil {
		return nil
	}
	return t.Type
}

func (t *TelephonyGetResponse) GetAgentID() *string {
	if t == nil {
		return nil
	}
	return t.AgentID
}

func (t *TelephonyGetResponse) GetChannel() *string {
	if t == nil {
		return nil
	}
	return t.Channel
}

func (t *TelephonyGetResponse) GetReason() *TelephonyGetResponseReason {
	if t == nil {
		return nil
	}
	return t.Reason
}

func (t *TelephonyGetResponse) GetCreateTs() *int {
	if t == nil {
		return nil
	}
	return t.CreateTs
}

func (t *TelephonyGetResponse) GetState() *TelephonyGetResponseState {
	if t == nil {
		return nil
	}
	return t.State
}

func (t *TelephonyGetResponse) GetStopTs() *int {
	if t == nil {
		return nil
	}
	return t.StopTs
}

func (t *TelephonyGetResponse) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TelephonyGetResponse) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetToNumber sets the ToNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyGetResponse) SetToNumber(toNumber *string) {
	t.ToNumber = toNumber
	t.require(telephonyGetResponseFieldToNumber)
}

// SetFromNumber sets the FromNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyGetResponse) SetFromNumber(fromNumber *string) {
	t.FromNumber = fromNumber
	t.require(telephonyGetResponseFieldFromNumber)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyGetResponse) SetPipelineID(pipelineID *string) {
	t.PipelineID = pipelineID
	t.require(telephonyGetResponseFieldPipelineID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyGetResponse) SetType(type_ *TelephonyGetResponseType) {
	t.Type = type_
	t.require(telephonyGetResponseFieldType)
}

// SetAgentID sets the AgentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyGetResponse) SetAgentID(agentID *string) {
	t.AgentID = agentID
	t.require(telephonyGetResponseFieldAgentID)
}

// SetChannel sets the Channel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyGetResponse) SetChannel(channel *string) {
	t.Channel = channel
	t.require(telephonyGetResponseFieldChannel)
}

// SetReason sets the Reason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyGetResponse) SetReason(reason *TelephonyGetResponseReason) {
	t.Reason = reason
	t.require(telephonyGetResponseFieldReason)
}

// SetCreateTs sets the CreateTs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyGetResponse) SetCreateTs(createTs *int) {
	t.CreateTs = createTs
	t.require(telephonyGetResponseFieldCreateTs)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyGetResponse) SetState(state *TelephonyGetResponseState) {
	t.State = state
	t.require(telephonyGetResponseFieldState)
}

// SetStopTs sets the StopTs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyGetResponse) SetStopTs(stopTs *int) {
	t.StopTs = stopTs
	t.require(telephonyGetResponseFieldStopTs)
}

func (t *TelephonyGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TelephonyGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TelephonyGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TelephonyGetResponse) MarshalJSON() ([]byte, error) {
	type embed TelephonyGetResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TelephonyGetResponse) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Reason for call ending:
// - `request`: Actively hung up.
// - `hangup`: The other party hung up.
// - `failed`: Call failed.
type TelephonyGetResponseReason string

const (
	TelephonyGetResponseReasonRequest TelephonyGetResponseReason = "request"
	TelephonyGetResponseReasonHangup  TelephonyGetResponseReason = "hangup"
	TelephonyGetResponseReasonFailed  TelephonyGetResponseReason = "failed"
)

func NewTelephonyGetResponseReasonFromString(s string) (TelephonyGetResponseReason, error) {
	switch s {
	case "request":
		return TelephonyGetResponseReasonRequest, nil
	case "hangup":
		return TelephonyGetResponseReasonHangup, nil
	case "failed":
		return TelephonyGetResponseReasonFailed, nil
	}
	var t TelephonyGetResponseReason
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TelephonyGetResponseReason) Ptr() *TelephonyGetResponseReason {
	return &t
}

// Call status:
// - `answered`: The call was answered.
// - `hangup`: The call was disconnected.
type TelephonyGetResponseState string

const (
	TelephonyGetResponseStateAnswered TelephonyGetResponseState = "answered"
	TelephonyGetResponseStateHangup   TelephonyGetResponseState = "hangup"
)

func NewTelephonyGetResponseStateFromString(s string) (TelephonyGetResponseState, error) {
	switch s {
	case "answered":
		return TelephonyGetResponseStateAnswered, nil
	case "hangup":
		return TelephonyGetResponseStateHangup, nil
	}
	var t TelephonyGetResponseState
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TelephonyGetResponseState) Ptr() *TelephonyGetResponseState {
	return &t
}

// Call type:
// - `inbound`: Inbound call.
// - `outbound`: Outbound call.
type TelephonyGetResponseType string

const (
	TelephonyGetResponseTypeInbound  TelephonyGetResponseType = "inbound"
	TelephonyGetResponseTypeOutbound TelephonyGetResponseType = "outbound"
)

func NewTelephonyGetResponseTypeFromString(s string) (TelephonyGetResponseType, error) {
	switch s {
	case "inbound":
		return TelephonyGetResponseTypeInbound, nil
	case "outbound":
		return TelephonyGetResponseTypeOutbound, nil
	}
	var t TelephonyGetResponseType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TelephonyGetResponseType) Ptr() *TelephonyGetResponseType {
	return &t
}

type TelephonyHangupResponse struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TelephonyHangupResponse) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TelephonyHangupResponse) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

func (t *TelephonyHangupResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TelephonyHangupResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TelephonyHangupResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TelephonyHangupResponse) MarshalJSON() ([]byte, error) {
	type embed TelephonyHangupResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TelephonyHangupResponse) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

type TelephonyListRequestType string

const (
	TelephonyListRequestTypeInbound  TelephonyListRequestType = "inbound"
	TelephonyListRequestTypeOutbound TelephonyListRequestType = "outbound"
)

func NewTelephonyListRequestTypeFromString(s string) (TelephonyListRequestType, error) {
	switch s {
	case "inbound":
		return TelephonyListRequestTypeInbound, nil
	case "outbound":
		return TelephonyListRequestTypeOutbound, nil
	}
	var t TelephonyListRequestType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TelephonyListRequestType) Ptr() *TelephonyListRequestType {
	return &t
}

var (
	telephonyListResponseFieldData   = big.NewInt(1 << 0)
	telephonyListResponseFieldMeta   = big.NewInt(1 << 1)
	telephonyListResponseFieldStatus = big.NewInt(1 << 2)
)

type TelephonyListResponse struct {
	// Call data object.
	Data *TelephonyListResponseData `json:"data,omitempty" url:"data,omitempty"`
	// Metadata about the list.
	Meta *TelephonyListResponseMeta `json:"meta,omitempty" url:"meta,omitempty"`
	// Request status.
	Status *string `json:"status,omitempty" url:"status,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TelephonyListResponse) GetData() *TelephonyListResponseData {
	if t == nil {
		return nil
	}
	return t.Data
}

func (t *TelephonyListResponse) GetMeta() *TelephonyListResponseMeta {
	if t == nil {
		return nil
	}
	return t.Meta
}

func (t *TelephonyListResponse) GetStatus() *string {
	if t == nil {
		return nil
	}
	return t.Status
}

func (t *TelephonyListResponse) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TelephonyListResponse) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListResponse) SetData(data *TelephonyListResponseData) {
	t.Data = data
	t.require(telephonyListResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListResponse) SetMeta(meta *TelephonyListResponseMeta) {
	t.Meta = meta
	t.require(telephonyListResponseFieldMeta)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListResponse) SetStatus(status *string) {
	t.Status = status
	t.require(telephonyListResponseFieldStatus)
}

func (t *TelephonyListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TelephonyListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TelephonyListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TelephonyListResponse) MarshalJSON() ([]byte, error) {
	type embed TelephonyListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TelephonyListResponse) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Call data object.
var (
	telephonyListResponseDataFieldCount = big.NewInt(1 << 0)
	telephonyListResponseDataFieldList  = big.NewInt(1 << 1)
)

type TelephonyListResponseData struct {
	// The number of calls returned in this response.
	Count *int `json:"count,omitempty" url:"count,omitempty"`
	// A list of calls that meet the criteria.
	List []*TelephonyListResponseDataListItem `json:"list,omitempty" url:"list,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TelephonyListResponseData) GetCount() *int {
	if t == nil {
		return nil
	}
	return t.Count
}

func (t *TelephonyListResponseData) GetList() []*TelephonyListResponseDataListItem {
	if t == nil {
		return nil
	}
	return t.List
}

func (t *TelephonyListResponseData) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TelephonyListResponseData) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListResponseData) SetCount(count *int) {
	t.Count = count
	t.require(telephonyListResponseDataFieldCount)
}

// SetList sets the List field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListResponseData) SetList(list []*TelephonyListResponseDataListItem) {
	t.List = list
	t.require(telephonyListResponseDataFieldList)
}

func (t *TelephonyListResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler TelephonyListResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TelephonyListResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TelephonyListResponseData) MarshalJSON() ([]byte, error) {
	type embed TelephonyListResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TelephonyListResponseData) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	telephonyListResponseDataListItemFieldToNumber   = big.NewInt(1 << 0)
	telephonyListResponseDataListItemFieldFromNumber = big.NewInt(1 << 1)
	telephonyListResponseDataListItemFieldPipelineID = big.NewInt(1 << 2)
	telephonyListResponseDataListItemFieldType       = big.NewInt(1 << 3)
	telephonyListResponseDataListItemFieldAgentID    = big.NewInt(1 << 4)
	telephonyListResponseDataListItemFieldChannel    = big.NewInt(1 << 5)
	telephonyListResponseDataListItemFieldCreateTs   = big.NewInt(1 << 6)
	telephonyListResponseDataListItemFieldState      = big.NewInt(1 << 7)
	telephonyListResponseDataListItemFieldStopTs     = big.NewInt(1 << 8)
)

type TelephonyListResponseDataListItem struct {
	// The number called.
	ToNumber *string `json:"to_number,omitempty" url:"to_number,omitempty"`
	// Caller ID.
	FromNumber *string `json:"from_number,omitempty" url:"from_number,omitempty"`
	// The unique ID of a published project in AI Studio. Can be obtained in AI Studio - Project - Release Management.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Call type:
	// - `inbound`: Inbound call.
	// - `outbound`: Outbound call.
	Type *TelephonyListResponseDataListItemType `json:"type,omitempty" url:"type,omitempty"`
	// A unique identifier for the call session.
	AgentID *string `json:"agent_id,omitempty" url:"agent_id,omitempty"`
	// RTC channel name.
	Channel *string `json:"channel,omitempty" url:"channel,omitempty"`
	// Call creation timestamp (in seconds).
	CreateTs *int `json:"create_ts,omitempty" url:"create_ts,omitempty"`
	// Call status:
	// - `answered`: The call was answered.
	// - `hangup`: The call was disconnected.
	State *TelephonyListResponseDataListItemState `json:"state,omitempty" url:"state,omitempty"`
	// Call end timestamp (in seconds). Returns `0` or `null` if the call has not ended.
	StopTs *int `json:"stop_ts,omitempty" url:"stop_ts,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TelephonyListResponseDataListItem) GetToNumber() *string {
	if t == nil {
		return nil
	}
	return t.ToNumber
}

func (t *TelephonyListResponseDataListItem) GetFromNumber() *string {
	if t == nil {
		return nil
	}
	return t.FromNumber
}

func (t *TelephonyListResponseDataListItem) GetPipelineID() *string {
	if t == nil {
		return nil
	}
	return t.PipelineID
}

func (t *TelephonyListResponseDataListItem) GetType() *TelephonyListResponseDataListItemType {
	if t == nil {
		return nil
	}
	return t.Type
}

func (t *TelephonyListResponseDataListItem) GetAgentID() *string {
	if t == nil {
		return nil
	}
	return t.AgentID
}

func (t *TelephonyListResponseDataListItem) GetChannel() *string {
	if t == nil {
		return nil
	}
	return t.Channel
}

func (t *TelephonyListResponseDataListItem) GetCreateTs() *int {
	if t == nil {
		return nil
	}
	return t.CreateTs
}

func (t *TelephonyListResponseDataListItem) GetState() *TelephonyListResponseDataListItemState {
	if t == nil {
		return nil
	}
	return t.State
}

func (t *TelephonyListResponseDataListItem) GetStopTs() *int {
	if t == nil {
		return nil
	}
	return t.StopTs
}

func (t *TelephonyListResponseDataListItem) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TelephonyListResponseDataListItem) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetToNumber sets the ToNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListResponseDataListItem) SetToNumber(toNumber *string) {
	t.ToNumber = toNumber
	t.require(telephonyListResponseDataListItemFieldToNumber)
}

// SetFromNumber sets the FromNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListResponseDataListItem) SetFromNumber(fromNumber *string) {
	t.FromNumber = fromNumber
	t.require(telephonyListResponseDataListItemFieldFromNumber)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListResponseDataListItem) SetPipelineID(pipelineID *string) {
	t.PipelineID = pipelineID
	t.require(telephonyListResponseDataListItemFieldPipelineID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListResponseDataListItem) SetType(type_ *TelephonyListResponseDataListItemType) {
	t.Type = type_
	t.require(telephonyListResponseDataListItemFieldType)
}

// SetAgentID sets the AgentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListResponseDataListItem) SetAgentID(agentID *string) {
	t.AgentID = agentID
	t.require(telephonyListResponseDataListItemFieldAgentID)
}

// SetChannel sets the Channel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListResponseDataListItem) SetChannel(channel *string) {
	t.Channel = channel
	t.require(telephonyListResponseDataListItemFieldChannel)
}

// SetCreateTs sets the CreateTs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListResponseDataListItem) SetCreateTs(createTs *int) {
	t.CreateTs = createTs
	t.require(telephonyListResponseDataListItemFieldCreateTs)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListResponseDataListItem) SetState(state *TelephonyListResponseDataListItemState) {
	t.State = state
	t.require(telephonyListResponseDataListItemFieldState)
}

// SetStopTs sets the StopTs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListResponseDataListItem) SetStopTs(stopTs *int) {
	t.StopTs = stopTs
	t.require(telephonyListResponseDataListItemFieldStopTs)
}

func (t *TelephonyListResponseDataListItem) UnmarshalJSON(data []byte) error {
	type unmarshaler TelephonyListResponseDataListItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TelephonyListResponseDataListItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TelephonyListResponseDataListItem) MarshalJSON() ([]byte, error) {
	type embed TelephonyListResponseDataListItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TelephonyListResponseDataListItem) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Call status:
// - `answered`: The call was answered.
// - `hangup`: The call was disconnected.
type TelephonyListResponseDataListItemState string

const (
	TelephonyListResponseDataListItemStateAnswered TelephonyListResponseDataListItemState = "answered"
	TelephonyListResponseDataListItemStateHangup   TelephonyListResponseDataListItemState = "hangup"
)

func NewTelephonyListResponseDataListItemStateFromString(s string) (TelephonyListResponseDataListItemState, error) {
	switch s {
	case "answered":
		return TelephonyListResponseDataListItemStateAnswered, nil
	case "hangup":
		return TelephonyListResponseDataListItemStateHangup, nil
	}
	var t TelephonyListResponseDataListItemState
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TelephonyListResponseDataListItemState) Ptr() *TelephonyListResponseDataListItemState {
	return &t
}

// Call type:
// - `inbound`: Inbound call.
// - `outbound`: Outbound call.
type TelephonyListResponseDataListItemType string

const (
	TelephonyListResponseDataListItemTypeInbound  TelephonyListResponseDataListItemType = "inbound"
	TelephonyListResponseDataListItemTypeOutbound TelephonyListResponseDataListItemType = "outbound"
)

func NewTelephonyListResponseDataListItemTypeFromString(s string) (TelephonyListResponseDataListItemType, error) {
	switch s {
	case "inbound":
		return TelephonyListResponseDataListItemTypeInbound, nil
	case "outbound":
		return TelephonyListResponseDataListItemTypeOutbound, nil
	}
	var t TelephonyListResponseDataListItemType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TelephonyListResponseDataListItemType) Ptr() *TelephonyListResponseDataListItemType {
	return &t
}

// Metadata about the list.
var (
	telephonyListResponseMetaFieldCursor = big.NewInt(1 << 0)
	telephonyListResponseMetaFieldTotal  = big.NewInt(1 << 1)
)

type TelephonyListResponseMeta struct {
	// Pagination cursor for the next page.
	Cursor *string `json:"cursor,omitempty" url:"cursor,omitempty"`
	// The total number of calls that meet the query criteria.
	Total *int `json:"total,omitempty" url:"total,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TelephonyListResponseMeta) GetCursor() *string {
	if t == nil {
		return nil
	}
	return t.Cursor
}

func (t *TelephonyListResponseMeta) GetTotal() *int {
	if t == nil {
		return nil
	}
	return t.Total
}

func (t *TelephonyListResponseMeta) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TelephonyListResponseMeta) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListResponseMeta) SetCursor(cursor *string) {
	t.Cursor = cursor
	t.require(telephonyListResponseMetaFieldCursor)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyListResponseMeta) SetTotal(total *int) {
	t.Total = total
	t.require(telephonyListResponseMetaFieldTotal)
}

func (t *TelephonyListResponseMeta) UnmarshalJSON(data []byte) error {
	type unmarshaler TelephonyListResponseMeta
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TelephonyListResponseMeta(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TelephonyListResponseMeta) MarshalJSON() ([]byte, error) {
	type embed TelephonyListResponseMeta
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TelephonyListResponseMeta) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}
