// Code generated by Fern. DO NOT EDIT.

package Agora

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/fern-demo/agoraio-go-sdk/internal"
	big "math/big"
)

type HangupCallRequest struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (h *HangupCallRequest) require(field *big.Int) {
	if h.explicitFields == nil {
		h.explicitFields = big.NewInt(0)
	}
	h.explicitFields.Or(h.explicitFields, field)
}

var (
	initiateOutboundCallRequestFieldName       = big.NewInt(1 << 0)
	initiateOutboundCallRequestFieldSip        = big.NewInt(1 << 1)
	initiateOutboundCallRequestFieldPipelineID = big.NewInt(1 << 2)
	initiateOutboundCallRequestFieldProperties = big.NewInt(1 << 3)
)

type InitiateOutboundCallRequest struct {
	// The name identifier of the call session.
	Name string `json:"name" url:"-"`
	// SIP (Session Initiation Protocol) call configuration object.
	Sip *InitiateOutboundCallRequestSip `json:"sip,omitempty" url:"-"`
	// The unique ID of a published project in AI Studio.
	PipelineID *string `json:"pipeline_id,omitempty" url:"-"`
	// Call attribute configuration. The content of this field varies depending on the invocation method:
	// - **Using pipeline ID**: Simply pass in `channel`, `token`, and `agent_rtc_uid`.
	// - **Using complete configuration**: Pass in the complete parameters of the [Start a conversational AI agent](https://docs.agora.io/en/conversational-ai/rest-api/agent/join) `properties`, including all required fields such as `channel`, `token`, `agent_rtc_uid`, `remote_rtc_uids`, `tts`, and `llm`.
	Properties *InitiateOutboundCallRequestProperties `json:"properties,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InitiateOutboundCallRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InitiateOutboundCallRequest) SetName(name string) {
	i.Name = name
	i.require(initiateOutboundCallRequestFieldName)
}

// SetSip sets the Sip field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InitiateOutboundCallRequest) SetSip(sip *InitiateOutboundCallRequestSip) {
	i.Sip = sip
	i.require(initiateOutboundCallRequestFieldSip)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InitiateOutboundCallRequest) SetPipelineID(pipelineID *string) {
	i.PipelineID = pipelineID
	i.require(initiateOutboundCallRequestFieldPipelineID)
}

// SetProperties sets the Properties field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InitiateOutboundCallRequest) SetProperties(properties *InitiateOutboundCallRequestProperties) {
	i.Properties = properties
	i.require(initiateOutboundCallRequestFieldProperties)
}

var (
	retrieveCallRecordsRequestFieldNumber   = big.NewInt(1 << 0)
	retrieveCallRecordsRequestFieldFromTime = big.NewInt(1 << 1)
	retrieveCallRecordsRequestFieldToTime   = big.NewInt(1 << 2)
	retrieveCallRecordsRequestFieldType     = big.NewInt(1 << 3)
	retrieveCallRecordsRequestFieldLimit    = big.NewInt(1 << 4)
	retrieveCallRecordsRequestFieldCursor   = big.NewInt(1 << 5)
)

type RetrieveCallRecordsRequest struct {
	// Filter by phone number. Can be either the calling number or the called number.
	Number *string `json:"-" url:"number,omitempty"`
	// Query list start timestamp (in seconds). Default is 60 days ago.
	FromTime *int `json:"-" url:"from_time,omitempty"`
	// Query list end timestamp (in seconds). Default is current time.
	ToTime *int `json:"-" url:"to_time,omitempty"`
	// Call type filter:
	// - `inbound`: Inbound call.
	// - `outbound`: Outbound call.
	//
	// If not specified, all call types are returned.
	Type *RetrieveCallRecordsRequestType `json:"-" url:"type,omitempty"`
	// Maximum number of items returned in a single page.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Pagination cursor. Use the `agent_id` from the previous page as the cursor for the next page.
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RetrieveCallRecordsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetNumber sets the Number field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsRequest) SetNumber(number *string) {
	r.Number = number
	r.require(retrieveCallRecordsRequestFieldNumber)
}

// SetFromTime sets the FromTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsRequest) SetFromTime(fromTime *int) {
	r.FromTime = fromTime
	r.require(retrieveCallRecordsRequestFieldFromTime)
}

// SetToTime sets the ToTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsRequest) SetToTime(toTime *int) {
	r.ToTime = toTime
	r.require(retrieveCallRecordsRequestFieldToTime)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsRequest) SetType(type_ *RetrieveCallRecordsRequestType) {
	r.Type = type_
	r.require(retrieveCallRecordsRequestFieldType)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsRequest) SetLimit(limit *int) {
	r.Limit = limit
	r.require(retrieveCallRecordsRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsRequest) SetCursor(cursor *string) {
	r.Cursor = cursor
	r.require(retrieveCallRecordsRequestFieldCursor)
}

type HangupCallResponse struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (h *HangupCallResponse) GetExtraProperties() map[string]interface{} {
	return h.extraProperties
}

func (h *HangupCallResponse) require(field *big.Int) {
	if h.explicitFields == nil {
		h.explicitFields = big.NewInt(0)
	}
	h.explicitFields.Or(h.explicitFields, field)
}

func (h *HangupCallResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler HangupCallResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*h = HangupCallResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *h)
	if err != nil {
		return err
	}
	h.extraProperties = extraProperties
	h.rawJSON = json.RawMessage(data)
	return nil
}

func (h *HangupCallResponse) MarshalJSON() ([]byte, error) {
	type embed HangupCallResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*h),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, h.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (h *HangupCallResponse) String() string {
	if len(h.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(h.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(h); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", h)
}

// Call attribute configuration. The content of this field varies depending on the invocation method:
// - **Using pipeline ID**: Simply pass in `channel`, `token`, and `agent_rtc_uid`.
// - **Using complete configuration**: Pass in the complete parameters of the [Start a conversational AI agent](https://docs.agora.io/en/conversational-ai/rest-api/agent/join) `properties`, including all required fields such as `channel`, `token`, `agent_rtc_uid`, `remote_rtc_uids`, `tts`, and `llm`.
var (
	initiateOutboundCallRequestPropertiesFieldChannel     = big.NewInt(1 << 0)
	initiateOutboundCallRequestPropertiesFieldToken       = big.NewInt(1 << 1)
	initiateOutboundCallRequestPropertiesFieldAgentRtcUID = big.NewInt(1 << 2)
)

type InitiateOutboundCallRequestProperties struct {
	// RTC channel name.
	Channel string `json:"channel" url:"channel"`
	// RTC Channel Token.
	Token string `json:"token" url:"token"`
	// The agent's user ID in the RTC channel.
	AgentRtcUID string `json:"agent_rtc_uid" url:"agent_rtc_uid"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (i *InitiateOutboundCallRequestProperties) GetChannel() string {
	if i == nil {
		return ""
	}
	return i.Channel
}

func (i *InitiateOutboundCallRequestProperties) GetToken() string {
	if i == nil {
		return ""
	}
	return i.Token
}

func (i *InitiateOutboundCallRequestProperties) GetAgentRtcUID() string {
	if i == nil {
		return ""
	}
	return i.AgentRtcUID
}

func (i *InitiateOutboundCallRequestProperties) GetExtraProperties() map[string]interface{} {
	return i.ExtraProperties
}

func (i *InitiateOutboundCallRequestProperties) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetChannel sets the Channel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InitiateOutboundCallRequestProperties) SetChannel(channel string) {
	i.Channel = channel
	i.require(initiateOutboundCallRequestPropertiesFieldChannel)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InitiateOutboundCallRequestProperties) SetToken(token string) {
	i.Token = token
	i.require(initiateOutboundCallRequestPropertiesFieldToken)
}

// SetAgentRtcUID sets the AgentRtcUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InitiateOutboundCallRequestProperties) SetAgentRtcUID(agentRtcUID string) {
	i.AgentRtcUID = agentRtcUID
	i.require(initiateOutboundCallRequestPropertiesFieldAgentRtcUID)
}

func (i *InitiateOutboundCallRequestProperties) UnmarshalJSON(data []byte) error {
	type embed InitiateOutboundCallRequestProperties
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = InitiateOutboundCallRequestProperties(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.ExtraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InitiateOutboundCallRequestProperties) MarshalJSON() ([]byte, error) {
	type embed InitiateOutboundCallRequestProperties
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, i.ExtraProperties)
}

func (i *InitiateOutboundCallRequestProperties) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// SIP (Session Initiation Protocol) call configuration object.
var (
	initiateOutboundCallRequestSipFieldToNumber    = big.NewInt(1 << 0)
	initiateOutboundCallRequestSipFieldFromNumber  = big.NewInt(1 << 1)
	initiateOutboundCallRequestSipFieldSipRtcUID   = big.NewInt(1 << 2)
	initiateOutboundCallRequestSipFieldSipRtcToken = big.NewInt(1 << 3)
)

type InitiateOutboundCallRequestSip struct {
	// Called number (target phone number), in E.164 format.
	ToNumber string `json:"to_number" url:"to_number"`
	// Caller ID (the number that initiated the call), in E.164 format.
	FromNumber string `json:"from_number" url:"from_number"`
	// The RTC UID used by the SIP gateway.
	SipRtcUID string `json:"sip_rtc_uid" url:"sip_rtc_uid"`
	// The RTC token used by the SIP gateway.
	SipRtcToken string `json:"sip_rtc_token" url:"sip_rtc_token"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InitiateOutboundCallRequestSip) GetToNumber() string {
	if i == nil {
		return ""
	}
	return i.ToNumber
}

func (i *InitiateOutboundCallRequestSip) GetFromNumber() string {
	if i == nil {
		return ""
	}
	return i.FromNumber
}

func (i *InitiateOutboundCallRequestSip) GetSipRtcUID() string {
	if i == nil {
		return ""
	}
	return i.SipRtcUID
}

func (i *InitiateOutboundCallRequestSip) GetSipRtcToken() string {
	if i == nil {
		return ""
	}
	return i.SipRtcToken
}

func (i *InitiateOutboundCallRequestSip) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *InitiateOutboundCallRequestSip) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetToNumber sets the ToNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InitiateOutboundCallRequestSip) SetToNumber(toNumber string) {
	i.ToNumber = toNumber
	i.require(initiateOutboundCallRequestSipFieldToNumber)
}

// SetFromNumber sets the FromNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InitiateOutboundCallRequestSip) SetFromNumber(fromNumber string) {
	i.FromNumber = fromNumber
	i.require(initiateOutboundCallRequestSipFieldFromNumber)
}

// SetSipRtcUID sets the SipRtcUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InitiateOutboundCallRequestSip) SetSipRtcUID(sipRtcUID string) {
	i.SipRtcUID = sipRtcUID
	i.require(initiateOutboundCallRequestSipFieldSipRtcUID)
}

// SetSipRtcToken sets the SipRtcToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InitiateOutboundCallRequestSip) SetSipRtcToken(sipRtcToken string) {
	i.SipRtcToken = sipRtcToken
	i.require(initiateOutboundCallRequestSipFieldSipRtcToken)
}

func (i *InitiateOutboundCallRequestSip) UnmarshalJSON(data []byte) error {
	type unmarshaler InitiateOutboundCallRequestSip
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InitiateOutboundCallRequestSip(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InitiateOutboundCallRequestSip) MarshalJSON() ([]byte, error) {
	type embed InitiateOutboundCallRequestSip
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InitiateOutboundCallRequestSip) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	initiateOutboundCallResponseFieldAgentID = big.NewInt(1 << 0)
)

type InitiateOutboundCallResponse struct {
	// Unique ID of the agent instance. Use it to query call status, control call flow, and perform other operations.
	AgentID *string `json:"agent_id,omitempty" url:"agent_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InitiateOutboundCallResponse) GetAgentID() *string {
	if i == nil {
		return nil
	}
	return i.AgentID
}

func (i *InitiateOutboundCallResponse) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *InitiateOutboundCallResponse) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetAgentID sets the AgentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InitiateOutboundCallResponse) SetAgentID(agentID *string) {
	i.AgentID = agentID
	i.require(initiateOutboundCallResponseFieldAgentID)
}

func (i *InitiateOutboundCallResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler InitiateOutboundCallResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InitiateOutboundCallResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InitiateOutboundCallResponse) MarshalJSON() ([]byte, error) {
	type embed InitiateOutboundCallResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InitiateOutboundCallResponse) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type RetrieveCallRecordsRequestType string

const (
	RetrieveCallRecordsRequestTypeInbound  RetrieveCallRecordsRequestType = "inbound"
	RetrieveCallRecordsRequestTypeOutbound RetrieveCallRecordsRequestType = "outbound"
)

func NewRetrieveCallRecordsRequestTypeFromString(s string) (RetrieveCallRecordsRequestType, error) {
	switch s {
	case "inbound":
		return RetrieveCallRecordsRequestTypeInbound, nil
	case "outbound":
		return RetrieveCallRecordsRequestTypeOutbound, nil
	}
	var t RetrieveCallRecordsRequestType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RetrieveCallRecordsRequestType) Ptr() *RetrieveCallRecordsRequestType {
	return &r
}

var (
	retrieveCallRecordsResponseFieldData   = big.NewInt(1 << 0)
	retrieveCallRecordsResponseFieldMeta   = big.NewInt(1 << 1)
	retrieveCallRecordsResponseFieldStatus = big.NewInt(1 << 2)
)

type RetrieveCallRecordsResponse struct {
	// Call data object.
	Data *RetrieveCallRecordsResponseData `json:"data,omitempty" url:"data,omitempty"`
	// Metadata about the list.
	Meta *RetrieveCallRecordsResponseMeta `json:"meta,omitempty" url:"meta,omitempty"`
	// Request status.
	Status *string `json:"status,omitempty" url:"status,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RetrieveCallRecordsResponse) GetData() *RetrieveCallRecordsResponseData {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *RetrieveCallRecordsResponse) GetMeta() *RetrieveCallRecordsResponseMeta {
	if r == nil {
		return nil
	}
	return r.Meta
}

func (r *RetrieveCallRecordsResponse) GetStatus() *string {
	if r == nil {
		return nil
	}
	return r.Status
}

func (r *RetrieveCallRecordsResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RetrieveCallRecordsResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsResponse) SetData(data *RetrieveCallRecordsResponseData) {
	r.Data = data
	r.require(retrieveCallRecordsResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsResponse) SetMeta(meta *RetrieveCallRecordsResponseMeta) {
	r.Meta = meta
	r.require(retrieveCallRecordsResponseFieldMeta)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsResponse) SetStatus(status *string) {
	r.Status = status
	r.require(retrieveCallRecordsResponseFieldStatus)
}

func (r *RetrieveCallRecordsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RetrieveCallRecordsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RetrieveCallRecordsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RetrieveCallRecordsResponse) MarshalJSON() ([]byte, error) {
	type embed RetrieveCallRecordsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RetrieveCallRecordsResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Call data object.
var (
	retrieveCallRecordsResponseDataFieldCount = big.NewInt(1 << 0)
	retrieveCallRecordsResponseDataFieldList  = big.NewInt(1 << 1)
)

type RetrieveCallRecordsResponseData struct {
	// The number of calls returned in this response.
	Count *int `json:"count,omitempty" url:"count,omitempty"`
	// A list of calls that meet the criteria.
	List []*RetrieveCallRecordsResponseDataListItem `json:"list,omitempty" url:"list,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RetrieveCallRecordsResponseData) GetCount() *int {
	if r == nil {
		return nil
	}
	return r.Count
}

func (r *RetrieveCallRecordsResponseData) GetList() []*RetrieveCallRecordsResponseDataListItem {
	if r == nil {
		return nil
	}
	return r.List
}

func (r *RetrieveCallRecordsResponseData) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RetrieveCallRecordsResponseData) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsResponseData) SetCount(count *int) {
	r.Count = count
	r.require(retrieveCallRecordsResponseDataFieldCount)
}

// SetList sets the List field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsResponseData) SetList(list []*RetrieveCallRecordsResponseDataListItem) {
	r.List = list
	r.require(retrieveCallRecordsResponseDataFieldList)
}

func (r *RetrieveCallRecordsResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler RetrieveCallRecordsResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RetrieveCallRecordsResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RetrieveCallRecordsResponseData) MarshalJSON() ([]byte, error) {
	type embed RetrieveCallRecordsResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RetrieveCallRecordsResponseData) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	retrieveCallRecordsResponseDataListItemFieldToNumber   = big.NewInt(1 << 0)
	retrieveCallRecordsResponseDataListItemFieldFromNumber = big.NewInt(1 << 1)
	retrieveCallRecordsResponseDataListItemFieldPipelineID = big.NewInt(1 << 2)
	retrieveCallRecordsResponseDataListItemFieldType       = big.NewInt(1 << 3)
	retrieveCallRecordsResponseDataListItemFieldAgentID    = big.NewInt(1 << 4)
	retrieveCallRecordsResponseDataListItemFieldChannel    = big.NewInt(1 << 5)
	retrieveCallRecordsResponseDataListItemFieldCreateTs   = big.NewInt(1 << 6)
	retrieveCallRecordsResponseDataListItemFieldState      = big.NewInt(1 << 7)
	retrieveCallRecordsResponseDataListItemFieldStopTs     = big.NewInt(1 << 8)
)

type RetrieveCallRecordsResponseDataListItem struct {
	// The number called.
	ToNumber *string `json:"to_number,omitempty" url:"to_number,omitempty"`
	// Caller ID.
	FromNumber *string `json:"from_number,omitempty" url:"from_number,omitempty"`
	// The unique ID of a published project in AI Studio. Can be obtained in AI Studio - Project - Release Management.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Call type:
	// - `inbound`: Inbound call.
	// - `outbound`: Outbound call.
	Type *RetrieveCallRecordsResponseDataListItemType `json:"type,omitempty" url:"type,omitempty"`
	// A unique identifier for the call session.
	AgentID *string `json:"agent_id,omitempty" url:"agent_id,omitempty"`
	// RTC channel name.
	Channel *string `json:"channel,omitempty" url:"channel,omitempty"`
	// Call creation timestamp (in seconds).
	CreateTs *int `json:"create_ts,omitempty" url:"create_ts,omitempty"`
	// Call status:
	// - `answered`: The call was answered.
	// - `hangup`: The call was disconnected.
	State *RetrieveCallRecordsResponseDataListItemState `json:"state,omitempty" url:"state,omitempty"`
	// Call end timestamp (in seconds). Returns `0` or `null` if the call has not ended.
	StopTs *int `json:"stop_ts,omitempty" url:"stop_ts,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RetrieveCallRecordsResponseDataListItem) GetToNumber() *string {
	if r == nil {
		return nil
	}
	return r.ToNumber
}

func (r *RetrieveCallRecordsResponseDataListItem) GetFromNumber() *string {
	if r == nil {
		return nil
	}
	return r.FromNumber
}

func (r *RetrieveCallRecordsResponseDataListItem) GetPipelineID() *string {
	if r == nil {
		return nil
	}
	return r.PipelineID
}

func (r *RetrieveCallRecordsResponseDataListItem) GetType() *RetrieveCallRecordsResponseDataListItemType {
	if r == nil {
		return nil
	}
	return r.Type
}

func (r *RetrieveCallRecordsResponseDataListItem) GetAgentID() *string {
	if r == nil {
		return nil
	}
	return r.AgentID
}

func (r *RetrieveCallRecordsResponseDataListItem) GetChannel() *string {
	if r == nil {
		return nil
	}
	return r.Channel
}

func (r *RetrieveCallRecordsResponseDataListItem) GetCreateTs() *int {
	if r == nil {
		return nil
	}
	return r.CreateTs
}

func (r *RetrieveCallRecordsResponseDataListItem) GetState() *RetrieveCallRecordsResponseDataListItemState {
	if r == nil {
		return nil
	}
	return r.State
}

func (r *RetrieveCallRecordsResponseDataListItem) GetStopTs() *int {
	if r == nil {
		return nil
	}
	return r.StopTs
}

func (r *RetrieveCallRecordsResponseDataListItem) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RetrieveCallRecordsResponseDataListItem) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetToNumber sets the ToNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsResponseDataListItem) SetToNumber(toNumber *string) {
	r.ToNumber = toNumber
	r.require(retrieveCallRecordsResponseDataListItemFieldToNumber)
}

// SetFromNumber sets the FromNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsResponseDataListItem) SetFromNumber(fromNumber *string) {
	r.FromNumber = fromNumber
	r.require(retrieveCallRecordsResponseDataListItemFieldFromNumber)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsResponseDataListItem) SetPipelineID(pipelineID *string) {
	r.PipelineID = pipelineID
	r.require(retrieveCallRecordsResponseDataListItemFieldPipelineID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsResponseDataListItem) SetType(type_ *RetrieveCallRecordsResponseDataListItemType) {
	r.Type = type_
	r.require(retrieveCallRecordsResponseDataListItemFieldType)
}

// SetAgentID sets the AgentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsResponseDataListItem) SetAgentID(agentID *string) {
	r.AgentID = agentID
	r.require(retrieveCallRecordsResponseDataListItemFieldAgentID)
}

// SetChannel sets the Channel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsResponseDataListItem) SetChannel(channel *string) {
	r.Channel = channel
	r.require(retrieveCallRecordsResponseDataListItemFieldChannel)
}

// SetCreateTs sets the CreateTs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsResponseDataListItem) SetCreateTs(createTs *int) {
	r.CreateTs = createTs
	r.require(retrieveCallRecordsResponseDataListItemFieldCreateTs)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsResponseDataListItem) SetState(state *RetrieveCallRecordsResponseDataListItemState) {
	r.State = state
	r.require(retrieveCallRecordsResponseDataListItemFieldState)
}

// SetStopTs sets the StopTs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsResponseDataListItem) SetStopTs(stopTs *int) {
	r.StopTs = stopTs
	r.require(retrieveCallRecordsResponseDataListItemFieldStopTs)
}

func (r *RetrieveCallRecordsResponseDataListItem) UnmarshalJSON(data []byte) error {
	type unmarshaler RetrieveCallRecordsResponseDataListItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RetrieveCallRecordsResponseDataListItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RetrieveCallRecordsResponseDataListItem) MarshalJSON() ([]byte, error) {
	type embed RetrieveCallRecordsResponseDataListItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RetrieveCallRecordsResponseDataListItem) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Call status:
// - `answered`: The call was answered.
// - `hangup`: The call was disconnected.
type RetrieveCallRecordsResponseDataListItemState string

const (
	RetrieveCallRecordsResponseDataListItemStateAnswered RetrieveCallRecordsResponseDataListItemState = "answered"
	RetrieveCallRecordsResponseDataListItemStateHangup   RetrieveCallRecordsResponseDataListItemState = "hangup"
)

func NewRetrieveCallRecordsResponseDataListItemStateFromString(s string) (RetrieveCallRecordsResponseDataListItemState, error) {
	switch s {
	case "answered":
		return RetrieveCallRecordsResponseDataListItemStateAnswered, nil
	case "hangup":
		return RetrieveCallRecordsResponseDataListItemStateHangup, nil
	}
	var t RetrieveCallRecordsResponseDataListItemState
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RetrieveCallRecordsResponseDataListItemState) Ptr() *RetrieveCallRecordsResponseDataListItemState {
	return &r
}

// Call type:
// - `inbound`: Inbound call.
// - `outbound`: Outbound call.
type RetrieveCallRecordsResponseDataListItemType string

const (
	RetrieveCallRecordsResponseDataListItemTypeInbound  RetrieveCallRecordsResponseDataListItemType = "inbound"
	RetrieveCallRecordsResponseDataListItemTypeOutbound RetrieveCallRecordsResponseDataListItemType = "outbound"
)

func NewRetrieveCallRecordsResponseDataListItemTypeFromString(s string) (RetrieveCallRecordsResponseDataListItemType, error) {
	switch s {
	case "inbound":
		return RetrieveCallRecordsResponseDataListItemTypeInbound, nil
	case "outbound":
		return RetrieveCallRecordsResponseDataListItemTypeOutbound, nil
	}
	var t RetrieveCallRecordsResponseDataListItemType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RetrieveCallRecordsResponseDataListItemType) Ptr() *RetrieveCallRecordsResponseDataListItemType {
	return &r
}

// Metadata about the list.
var (
	retrieveCallRecordsResponseMetaFieldCursor = big.NewInt(1 << 0)
	retrieveCallRecordsResponseMetaFieldTotal  = big.NewInt(1 << 1)
)

type RetrieveCallRecordsResponseMeta struct {
	// Pagination cursor for the next page.
	Cursor *string `json:"cursor,omitempty" url:"cursor,omitempty"`
	// The total number of calls that meet the query criteria.
	Total *int `json:"total,omitempty" url:"total,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RetrieveCallRecordsResponseMeta) GetCursor() *string {
	if r == nil {
		return nil
	}
	return r.Cursor
}

func (r *RetrieveCallRecordsResponseMeta) GetTotal() *int {
	if r == nil {
		return nil
	}
	return r.Total
}

func (r *RetrieveCallRecordsResponseMeta) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RetrieveCallRecordsResponseMeta) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsResponseMeta) SetCursor(cursor *string) {
	r.Cursor = cursor
	r.require(retrieveCallRecordsResponseMetaFieldCursor)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallRecordsResponseMeta) SetTotal(total *int) {
	r.Total = total
	r.require(retrieveCallRecordsResponseMetaFieldTotal)
}

func (r *RetrieveCallRecordsResponseMeta) UnmarshalJSON(data []byte) error {
	type unmarshaler RetrieveCallRecordsResponseMeta
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RetrieveCallRecordsResponseMeta(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RetrieveCallRecordsResponseMeta) MarshalJSON() ([]byte, error) {
	type embed RetrieveCallRecordsResponseMeta
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RetrieveCallRecordsResponseMeta) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	retrieveCallStatusResponseFieldToNumber   = big.NewInt(1 << 0)
	retrieveCallStatusResponseFieldFromNumber = big.NewInt(1 << 1)
	retrieveCallStatusResponseFieldPipelineID = big.NewInt(1 << 2)
	retrieveCallStatusResponseFieldType       = big.NewInt(1 << 3)
	retrieveCallStatusResponseFieldAgentID    = big.NewInt(1 << 4)
	retrieveCallStatusResponseFieldChannel    = big.NewInt(1 << 5)
	retrieveCallStatusResponseFieldReason     = big.NewInt(1 << 6)
	retrieveCallStatusResponseFieldCreateTs   = big.NewInt(1 << 7)
	retrieveCallStatusResponseFieldState      = big.NewInt(1 << 8)
	retrieveCallStatusResponseFieldStopTs     = big.NewInt(1 << 9)
)

type RetrieveCallStatusResponse struct {
	// The number called.
	ToNumber *string `json:"to_number,omitempty" url:"to_number,omitempty"`
	// Caller ID.
	FromNumber *string `json:"from_number,omitempty" url:"from_number,omitempty"`
	// The unique ID of a published project in AI Studio. Can be obtained in AI Studio - Project - Release Management.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Call type:
	// - `inbound`: Inbound call.
	// - `outbound`: Outbound call.
	Type *RetrieveCallStatusResponseType `json:"type,omitempty" url:"type,omitempty"`
	// A unique identifier for the call session.
	AgentID *string `json:"agent_id,omitempty" url:"agent_id,omitempty"`
	// RTC channel name.
	Channel *string `json:"channel,omitempty" url:"channel,omitempty"`
	// Reason for call ending:
	// - `request`: Actively hung up.
	// - `hangup`: The other party hung up.
	// - `failed`: Call failed.
	Reason *RetrieveCallStatusResponseReason `json:"reason,omitempty" url:"reason,omitempty"`
	// Call creation timestamp (in seconds).
	CreateTs *int `json:"create_ts,omitempty" url:"create_ts,omitempty"`
	// Call status:
	// - `answered`: The call was answered.
	// - `hangup`: The call was disconnected.
	State *RetrieveCallStatusResponseState `json:"state,omitempty" url:"state,omitempty"`
	// Call end timestamp (in seconds). Returns `0` or `null` if the call has not ended.
	StopTs *int `json:"stop_ts,omitempty" url:"stop_ts,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RetrieveCallStatusResponse) GetToNumber() *string {
	if r == nil {
		return nil
	}
	return r.ToNumber
}

func (r *RetrieveCallStatusResponse) GetFromNumber() *string {
	if r == nil {
		return nil
	}
	return r.FromNumber
}

func (r *RetrieveCallStatusResponse) GetPipelineID() *string {
	if r == nil {
		return nil
	}
	return r.PipelineID
}

func (r *RetrieveCallStatusResponse) GetType() *RetrieveCallStatusResponseType {
	if r == nil {
		return nil
	}
	return r.Type
}

func (r *RetrieveCallStatusResponse) GetAgentID() *string {
	if r == nil {
		return nil
	}
	return r.AgentID
}

func (r *RetrieveCallStatusResponse) GetChannel() *string {
	if r == nil {
		return nil
	}
	return r.Channel
}

func (r *RetrieveCallStatusResponse) GetReason() *RetrieveCallStatusResponseReason {
	if r == nil {
		return nil
	}
	return r.Reason
}

func (r *RetrieveCallStatusResponse) GetCreateTs() *int {
	if r == nil {
		return nil
	}
	return r.CreateTs
}

func (r *RetrieveCallStatusResponse) GetState() *RetrieveCallStatusResponseState {
	if r == nil {
		return nil
	}
	return r.State
}

func (r *RetrieveCallStatusResponse) GetStopTs() *int {
	if r == nil {
		return nil
	}
	return r.StopTs
}

func (r *RetrieveCallStatusResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RetrieveCallStatusResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetToNumber sets the ToNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallStatusResponse) SetToNumber(toNumber *string) {
	r.ToNumber = toNumber
	r.require(retrieveCallStatusResponseFieldToNumber)
}

// SetFromNumber sets the FromNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallStatusResponse) SetFromNumber(fromNumber *string) {
	r.FromNumber = fromNumber
	r.require(retrieveCallStatusResponseFieldFromNumber)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallStatusResponse) SetPipelineID(pipelineID *string) {
	r.PipelineID = pipelineID
	r.require(retrieveCallStatusResponseFieldPipelineID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallStatusResponse) SetType(type_ *RetrieveCallStatusResponseType) {
	r.Type = type_
	r.require(retrieveCallStatusResponseFieldType)
}

// SetAgentID sets the AgentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallStatusResponse) SetAgentID(agentID *string) {
	r.AgentID = agentID
	r.require(retrieveCallStatusResponseFieldAgentID)
}

// SetChannel sets the Channel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallStatusResponse) SetChannel(channel *string) {
	r.Channel = channel
	r.require(retrieveCallStatusResponseFieldChannel)
}

// SetReason sets the Reason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallStatusResponse) SetReason(reason *RetrieveCallStatusResponseReason) {
	r.Reason = reason
	r.require(retrieveCallStatusResponseFieldReason)
}

// SetCreateTs sets the CreateTs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallStatusResponse) SetCreateTs(createTs *int) {
	r.CreateTs = createTs
	r.require(retrieveCallStatusResponseFieldCreateTs)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallStatusResponse) SetState(state *RetrieveCallStatusResponseState) {
	r.State = state
	r.require(retrieveCallStatusResponseFieldState)
}

// SetStopTs sets the StopTs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveCallStatusResponse) SetStopTs(stopTs *int) {
	r.StopTs = stopTs
	r.require(retrieveCallStatusResponseFieldStopTs)
}

func (r *RetrieveCallStatusResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RetrieveCallStatusResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RetrieveCallStatusResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RetrieveCallStatusResponse) MarshalJSON() ([]byte, error) {
	type embed RetrieveCallStatusResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RetrieveCallStatusResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Reason for call ending:
// - `request`: Actively hung up.
// - `hangup`: The other party hung up.
// - `failed`: Call failed.
type RetrieveCallStatusResponseReason string

const (
	RetrieveCallStatusResponseReasonRequest RetrieveCallStatusResponseReason = "request"
	RetrieveCallStatusResponseReasonHangup  RetrieveCallStatusResponseReason = "hangup"
	RetrieveCallStatusResponseReasonFailed  RetrieveCallStatusResponseReason = "failed"
)

func NewRetrieveCallStatusResponseReasonFromString(s string) (RetrieveCallStatusResponseReason, error) {
	switch s {
	case "request":
		return RetrieveCallStatusResponseReasonRequest, nil
	case "hangup":
		return RetrieveCallStatusResponseReasonHangup, nil
	case "failed":
		return RetrieveCallStatusResponseReasonFailed, nil
	}
	var t RetrieveCallStatusResponseReason
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RetrieveCallStatusResponseReason) Ptr() *RetrieveCallStatusResponseReason {
	return &r
}

// Call status:
// - `answered`: The call was answered.
// - `hangup`: The call was disconnected.
type RetrieveCallStatusResponseState string

const (
	RetrieveCallStatusResponseStateAnswered RetrieveCallStatusResponseState = "answered"
	RetrieveCallStatusResponseStateHangup   RetrieveCallStatusResponseState = "hangup"
)

func NewRetrieveCallStatusResponseStateFromString(s string) (RetrieveCallStatusResponseState, error) {
	switch s {
	case "answered":
		return RetrieveCallStatusResponseStateAnswered, nil
	case "hangup":
		return RetrieveCallStatusResponseStateHangup, nil
	}
	var t RetrieveCallStatusResponseState
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RetrieveCallStatusResponseState) Ptr() *RetrieveCallStatusResponseState {
	return &r
}

// Call type:
// - `inbound`: Inbound call.
// - `outbound`: Outbound call.
type RetrieveCallStatusResponseType string

const (
	RetrieveCallStatusResponseTypeInbound  RetrieveCallStatusResponseType = "inbound"
	RetrieveCallStatusResponseTypeOutbound RetrieveCallStatusResponseType = "outbound"
)

func NewRetrieveCallStatusResponseTypeFromString(s string) (RetrieveCallStatusResponseType, error) {
	switch s {
	case "inbound":
		return RetrieveCallStatusResponseTypeInbound, nil
	case "outbound":
		return RetrieveCallStatusResponseTypeOutbound, nil
	}
	var t RetrieveCallStatusResponseType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RetrieveCallStatusResponseType) Ptr() *RetrieveCallStatusResponseType {
	return &r
}
