// Code generated by Fern. DO NOT EDIT.

package phonenumbermanagement

import (
	context "context"
	Agora "github.com/fern-demo/agoraio-go-sdk/v505"
	core "github.com/fern-demo/agoraio-go-sdk/v505/core"
	internal "github.com/fern-demo/agoraio-go-sdk/v505/internal"
	option "github.com/fern-demo/agoraio-go-sdk/v505/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieve a list of all imported phone numbers under the current account.
func (c *Client) List(
	ctx context.Context,
	opts ...option.RequestOption,
) ([]*Agora.PhoneNumberManagementListResponseItem, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Import a pre-configured phone number that can be used for inbound or outbound calls.
func (c *Client) Add(
	ctx context.Context,
	request *Agora.PhoneNumberManagementAddRequest,
	opts ...option.RequestOption,
) (*Agora.PhoneNumberManagementAddResponse, error) {
	response, err := c.WithRawResponse.Add(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve detailed information for a specific phone number.
func (c *Client) Get(
	ctx context.Context,
	// Telephone number in E.164 format. For example, +11234567890.
	phoneNumber string,
	opts ...option.RequestOption,
) (*Agora.PhoneNumberManagementGetResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		phoneNumber,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Remove an imported phone number from the system.
//
// Note: This operation only removes the number configuration from the Agora system; the number stored with the phone service provider is not deleted. After calling this endpoint, the number stops receiving calls routed through this system. To delete the number from the service provider, remove it in the service provider's console.
func (c *Client) Delete(
	ctx context.Context,
	// Telephone number in E.164 format. For example, +11234567890.
	phoneNumber string,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		phoneNumber,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Update the configuration for a phone number.
func (c *Client) Update(
	ctx context.Context,
	// Telephone number in E.164 format. For example, +11234567890.
	phoneNumber string,
	request *Agora.PhoneNumberManagementUpdateRequest,
	opts ...option.RequestOption,
) (*Agora.PhoneNumberManagementUpdateResponse, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		phoneNumber,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
