// Code generated by Fern. DO NOT EDIT.

package phonenumbermanagement

import (
	context "context"
	Agora "github.com/fern-demo/agoraio-go-sdk"
	core "github.com/fern-demo/agoraio-go-sdk/core"
	internal "github.com/fern-demo/agoraio-go-sdk/internal"
	option "github.com/fern-demo/agoraio-go-sdk/option"
	http "net/http"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) RetrieveNumberList(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[[]*Agora.RetrieveNumberListResponseItem], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.agora.io/api/conversational-ai-agent",
	)
	endpointURL := baseURL + "/v2/phone-numbers"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response []*Agora.RetrieveNumberListResponseItem
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[[]*Agora.RetrieveNumberListResponseItem]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ImportNumber(
	ctx context.Context,
	request *Agora.ImportNumberRequest,
	opts ...option.RequestOption,
) (*core.Response[*Agora.ImportNumberResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.agora.io/api/conversational-ai-agent",
	)
	endpointURL := baseURL + "/v2/phone-numbers"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *Agora.ImportNumberResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*Agora.ImportNumberResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) RetrieveNumberInformation(
	ctx context.Context,
	// Telephone number in E.164 format. For example, +11234567890.
	phoneNumber string,
	opts ...option.RequestOption,
) (*core.Response[*Agora.RetrieveNumberInformationResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.agora.io/api/conversational-ai-agent",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/phone-numbers/%v",
		phoneNumber,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *Agora.RetrieveNumberInformationResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*Agora.RetrieveNumberInformationResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteNumber(
	ctx context.Context,
	// Telephone number in E.164 format. For example, +11234567890.
	phoneNumber string,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.agora.io/api/conversational-ai-agent",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/phone-numbers/%v",
		phoneNumber,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) UpdateNumberConfiguration(
	ctx context.Context,
	// Telephone number in E.164 format. For example, +11234567890.
	phoneNumber string,
	request *Agora.UpdateNumberConfigurationRequest,
	opts ...option.RequestOption,
) (*core.Response[*Agora.UpdateNumberConfigurationResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.agora.io/api/conversational-ai-agent",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/phone-numbers/%v",
		phoneNumber,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *Agora.UpdateNumberConfigurationResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*Agora.UpdateNumberConfigurationResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
