// Code generated by Fern. DO NOT EDIT.

package telephony_test

import (
	context "context"
	fmt "fmt"
	agoraiogosdk "github.com/fern-demo/agoraio-go-sdk"
	client "github.com/fern-demo/agoraio-go-sdk/client"
	option "github.com/fern-demo/agoraio-go-sdk/option"
	require "github.com/stretchr/testify/require"
	gowiremock "github.com/wiremock/go-wiremock"
	wiremocktestcontainersgo "github.com/wiremock/wiremock-testcontainers-go"
	http "net/http"
	os "os"
	testing "testing"
)

// TestMain sets up shared test fixtures for all tests in this package// Global test fixtures
var (
	WireMockContainer *wiremocktestcontainersgo.WireMockContainer
	WireMockBaseURL   string
	WireMockClient    *gowiremock.Client
)

// TestMain sets up shared test fixtures for all tests in this package
func TestMain(m *testing.M) {
	// Setup shared WireMock container
	ctx := context.Background()
	container, err := wiremocktestcontainersgo.RunContainerAndStopOnCleanup(
		ctx,
		&testing.T{},
		wiremocktestcontainersgo.WithImage("docker.io/wiremock/wiremock:3.9.1"),
	)
	if err != nil {
		fmt.Printf("Failed to start WireMock container: %v\n", err)
		os.Exit(1)
	}

	// Store global references
	WireMockContainer = container

	// Try to get the base URL using the standard method first
	baseURL, err := container.Endpoint(ctx, "")
	if err == nil {
		// Standard method worked (running outside DinD)
		// This uses the mapped port (e.g., localhost:59553)
		WireMockBaseURL = "http://" + baseURL
		WireMockClient = container.Client
	} else {
		// Standard method failed, use internal IP fallback (DinD environment)
		fmt.Printf("Standard endpoint resolution failed, using internal IP fallback: %v\n", err)

		inspect, err := container.Inspect(ctx)
		if err != nil {
			fmt.Printf("Failed to inspect WireMock container: %v\n", err)
			os.Exit(1)
		}

		// Find the IP address from the container's networks
		var containerIP string
		for _, network := range inspect.NetworkSettings.Networks {
			if network.IPAddress != "" {
				containerIP = network.IPAddress
				break
			}
		}

		if containerIP == "" {
			fmt.Printf("Failed to get WireMock container IP address\n")
			os.Exit(1)
		}

		// In DinD, use the internal port directly (8080 for WireMock HTTP)
		// Don't use the mapped port since it doesn't exist in this environment
		WireMockBaseURL = fmt.Sprintf("http://%s:8080", containerIP)

		// The container.Client was created with a bad URL, so we need a new one
		WireMockClient = gowiremock.NewClient(WireMockBaseURL)
	}

	fmt.Printf("WireMock available at: %s\n", WireMockBaseURL)

	// Run all tests
	code := m.Run()

	// Cleanup
	if WireMockContainer != nil {
		WireMockContainer.Terminate(ctx)
	}

	// Exit with the same code as the tests
	os.Exit(code)
}

func TestTelephonyRetrieveCallRecordsWithWireMock(
	t *testing.T,
) {
	// wiremock client and server initialized in shared main_test.go
	defer WireMockClient.Reset()
	stub := gowiremock.Get(gowiremock.URLPathTemplate("/v2/projects/{appid}/call")).WithPathParam(
		"appid",
		gowiremock.Matching("appid"),
	).WillReturnResponse(
		gowiremock.NewResponse().WithJSONBody(
			map[string]interface{}{"data": map[string]interface{}{"count": 1, "list": []interface{}{map[string]interface{}{"to_number": "2222", "from_number": "111", "pipeline_id": "28", "type": "inbound", "agent_id": "A42AA22ATxxxxx4RH76AM92W", "channel": "channel_1111", "create_ts": 1758498988, "state": "answered"}}}, "meta": map[string]interface{}{"cursor": "A42AA22AT45LDxxxxxH76AM92W", "total": 1}, "status": "ok"},
		).WithStatus(http.StatusOK),
	)
	err := WireMockClient.StubFor(stub)
	require.NoError(t, err, "Failed to create WireMock stub")

	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.RetrieveCallRecordsRequest{
		Number: Agora.String(
			"number",
		),
		FromTime: Agora.Int(
			1,
		),
		ToTime: Agora.Int(
			1,
		),
		Type: Agora.RetrieveCallRecordsRequestTypeInbound.Ptr(),
		Limit: Agora.Int(
			1,
		),
		Cursor: Agora.String(
			"cursor",
		),
	}
	_, invocationErr := client.Telephony.RetrieveCallRecords(
		context.TODO(),
		"appid",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	ok, countErr := WireMockClient.Verify(stub.Request(), 1)
	require.NoError(t, countErr, "Failed to verify WireMock request was matched")
	require.True(t, ok, "WireMock request was not matched")
}

func TestTelephonyInitiateOutboundCallWithWireMock(
	t *testing.T,
) {
	// wiremock client and server initialized in shared main_test.go
	defer WireMockClient.Reset()
	stub := gowiremock.Post(gowiremock.URLPathTemplate("/v2/projects/{appid}/call")).WithPathParam(
		"appid",
		gowiremock.Matching("appid"),
	).WithBodyPattern(gowiremock.MatchesJsonSchema(`{
                    "$schema": "https://json-schema.org/draft/2020-12/schema",
                    "type": "object",
                    "required": ["name", "sip", "properties"],
                    "properties": {
                        "name": {"type": "string"}, "sip": {"type": "object"}, "properties": {"type": "object"}
                    },
                    "additionalProperties": true
                }`, "V202012")).WillReturnResponse(
		gowiremock.NewResponse().WithJSONBody(
			map[string]interface{}{"agent_id": "A42AK62PExxxxxxxx74LN47MF46E"},
		).WithStatus(http.StatusOK),
	)
	err := WireMockClient.StubFor(stub)
	require.NoError(t, err, "Failed to create WireMock stub")

	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.InitiateOutboundCallRequest{
		Name: "customer_service",
		Sip: &Agora.InitiateOutboundCallRequestSip{
			ToNumber:    "+19876543210",
			FromNumber:  "+11234567890",
			SipRtcUID:   "100",
			SipRtcToken: "<agora_sip_rtc_token>",
		},
		PipelineID: Agora.String(
			"fzufjlweixxxxnlp",
		),
		Properties: &Agora.InitiateOutboundCallRequestProperties{
			Channel:     "<agora_channel>",
			Token:       "<agora_channel_token>",
			AgentRtcUID: "111",
		},
	}
	_, invocationErr := client.Telephony.InitiateOutboundCall(
		context.TODO(),
		"appid",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	ok, countErr := WireMockClient.Verify(stub.Request(), 1)
	require.NoError(t, countErr, "Failed to verify WireMock request was matched")
	require.True(t, ok, "WireMock request was not matched")
}

func TestTelephonyRetrieveCallStatusWithWireMock(
	t *testing.T,
) {
	// wiremock client and server initialized in shared main_test.go
	defer WireMockClient.Reset()
	stub := gowiremock.Get(gowiremock.URLPathTemplate("/v2/projects/{appid}/calls/{agent_id}")).WithPathParam(
		"appid",
		gowiremock.Matching("appid"),
	).WithPathParam(
		"agent_id",
		gowiremock.Matching("agent_id"),
	).WillReturnResponse(
		gowiremock.NewResponse().WithJSONBody(
			map[string]interface{}{"to_number": "1300000000", "from_number": "1330000000", "pipeline_id": "28", "type": "inbound", "agent_id": "A42AA22AT45xxxxxxRH76AM92W", "channel": "channel_1111", "reason": "request", "create_ts": 1758498988, "state": "hangup", "stop_ts": 1758498995},
		).WithStatus(http.StatusOK),
	)
	err := WireMockClient.StubFor(stub)
	require.NoError(t, err, "Failed to create WireMock stub")

	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.Telephony.RetrieveCallStatus(
		context.TODO(),
		"appid",
		"agent_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	ok, countErr := WireMockClient.Verify(stub.Request(), 1)
	require.NoError(t, countErr, "Failed to verify WireMock request was matched")
	require.True(t, ok, "WireMock request was not matched")
}

func TestTelephonyHangupCallWithWireMock(
	t *testing.T,
) {
	// wiremock client and server initialized in shared main_test.go
	defer WireMockClient.Reset()
	stub := gowiremock.Post(gowiremock.URLPathTemplate("/v2/projects/{appid}/calls/{agent_id}/hangup")).WithPathParam(
		"appid",
		gowiremock.Matching("appid"),
	).WithPathParam(
		"agent_id",
		gowiremock.Matching("agent_id"),
	).WithBodyPattern(gowiremock.MatchesJsonSchema(`{
                    "$schema": "https://json-schema.org/draft/2020-12/schema",
                    "type": "object",
                    "required": [],
                    "properties": {
                        
                    },
                    "additionalProperties": true
                }`, "V202012")).WillReturnResponse(
		gowiremock.NewResponse().WithJSONBody(
			map[string]interface{}{},
		).WithStatus(http.StatusOK),
	)
	err := WireMockClient.StubFor(stub)
	require.NoError(t, err, "Failed to create WireMock stub")

	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.HangupCallRequest{}
	_, invocationErr := client.Telephony.HangupCall(
		context.TODO(),
		"appid",
		"agent_id",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	ok, countErr := WireMockClient.Verify(stub.Request(), 1)
	require.NoError(t, countErr, "Failed to verify WireMock request was matched")
	require.True(t, ok, "WireMock request was not matched")
}
