// Code generated by Fern. DO NOT EDIT.

package agents_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	Agora "github.com/fern-demo/agoraio-go-sdk"
	client "github.com/fern-demo/agoraio-go-sdk/client"
	option "github.com/fern-demo/agoraio-go-sdk/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestAgentsStartWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.StartAgentsRequest{
		Appid: "appid",
		Name:  "unique_name",
		Properties: &Agora.StartAgentsRequestProperties{
			Channel:     "channel_name",
			Token:       "token",
			AgentRtcUID: "1001",
			RemoteRtcUIDs: []string{
				"1002",
			},
			IdleTimeout: Agora.Int(
				120,
			),
			AdvancedFeatures: &Agora.StartAgentsRequestPropertiesAdvancedFeatures{
				EnableAivad: Agora.Bool(
					true,
				),
			},
			Asr: &Agora.StartAgentsRequestPropertiesAsr{
				Language: Agora.String(
					"en-US",
				),
			},
			Tts: &Agora.StartAgentsRequestPropertiesTts{
				Vendor: Agora.StartAgentsRequestPropertiesTtsVendorMicrosoft,
				Params: map[string]any{
					"key":        "<your_tts_api_key>",
					"region":     "eastus",
					"voice_name": "en-US-AndrewMultilingualNeural",
				},
			},
			Llm: &Agora.StartAgentsRequestPropertiesLlm{
				URL: "https://api.openai.com/v1/chat/completions",
				APIKey: Agora.String(
					"<your_llm_key>",
				),
				SystemMessages: []map[string]any{
					map[string]any{
						"role":    "system",
						"content": "You are a helpful chatbot.",
					},
				},
				Params: map[string]any{
					"model": "gpt-4o-mini",
				},
				MaxHistory: Agora.Int(
					32,
				),
				GreetingMessage: Agora.String(
					"Hello, how can I assist you today?",
				),
				FailureMessage: Agora.String(
					"Please hold on a second.",
				),
			},
		},
	}
	_, invocationErr := client.Agents.Start(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsStartWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsStartWithWireMock", "POST", "/v2/projects/appid/join", nil, 1)
}

func TestAgentsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.ListAgentsRequest{
		Appid: "appid",
	}
	_, invocationErr := client.Agents.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsListWithWireMock", "GET", "/v2/projects/appid/agents", nil, 1)
}

func TestAgentsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.GetAgentsRequest{
		Appid:   "appid",
		AgentID: "agentId",
	}
	_, invocationErr := client.Agents.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsGetWithWireMock", "GET", "/v2/projects/appid/agents/agentId", nil, 1)
}

func TestAgentsGetHistoryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.GetHistoryAgentsRequest{
		Appid:   "appid",
		AgentID: "agentId",
	}
	_, invocationErr := client.Agents.GetHistory(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsGetHistoryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsGetHistoryWithWireMock", "GET", "/v2/projects/appid/agents/agentId/history", nil, 1)
}

func TestAgentsStopWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.StopAgentsRequest{
		Appid:   "appid",
		AgentID: "agentId",
	}
	invocationErr := client.Agents.Stop(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsStopWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsStopWithWireMock", "POST", "/v2/projects/appid/agents/agentId/leave", nil, 1)
}

func TestAgentsUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.UpdateAgentsRequest{
		Appid:   "appid",
		AgentID: "agentId",
		Properties: &Agora.UpdateAgentsRequestProperties{
			Token: Agora.String(
				"007eJxTYxxxxxxxxxxIaHMLAAAA0ex66",
			),
			Llm: &Agora.UpdateAgentsRequestPropertiesLlm{
				SystemMessages: []map[string]any{
					map[string]any{
						"role":    "system",
						"content": "You are a helpful assistant. xxx",
					},
					map[string]any{
						"role":    "system",
						"content": "Previously, user has talked about their favorite hobbies with some key topics: xxx",
					},
				},
				Params: map[string]any{
					"model":     "abab6.5s-chat",
					"max_token": 1024,
				},
			},
		},
	}
	_, invocationErr := client.Agents.Update(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsUpdateWithWireMock", "POST", "/v2/projects/appid/agents/agentId/update", nil, 1)
}

func TestAgentsSpeakWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.SpeakAgentsRequest{
		Appid:    "appid",
		AgentID:  "agentId",
		Text:     "Sorry, the conversation content is not compliant.",
		Priority: Agora.SpeakAgentsRequestPriorityInterrupt.Ptr(),
		Interruptable: Agora.Bool(
			false,
		),
	}
	_, invocationErr := client.Agents.Speak(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsSpeakWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsSpeakWithWireMock", "POST", "/v2/projects/appid/agents/agentId/speak", nil, 1)
}

func TestAgentsInterruptWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.InterruptAgentsRequest{
		Appid:   "appid",
		AgentID: "agentId",
	}
	_, invocationErr := client.Agents.Interrupt(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsInterruptWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsInterruptWithWireMock", "POST", "/v2/projects/appid/agents/agentId/interrupt", nil, 1)
}
