// Code generated by Fern. DO NOT EDIT.

package phone_number_management_test

import (
	context "context"
	fmt "fmt"
	agoraiogosdk "github.com/fern-demo/agoraio-go-sdk"
	client "github.com/fern-demo/agoraio-go-sdk/client"
	option "github.com/fern-demo/agoraio-go-sdk/option"
	require "github.com/stretchr/testify/require"
	gowiremock "github.com/wiremock/go-wiremock"
	wiremocktestcontainersgo "github.com/wiremock/wiremock-testcontainers-go"
	http "net/http"
	os "os"
	testing "testing"
)

// TestMain sets up shared test fixtures for all tests in this package// Global test fixtures
var (
	WireMockContainer *wiremocktestcontainersgo.WireMockContainer
	WireMockBaseURL   string
	WireMockClient    *gowiremock.Client
)

// TestMain sets up shared test fixtures for all tests in this package
func TestMain(m *testing.M) {
	// Setup shared WireMock container
	ctx := context.Background()
	container, err := wiremocktestcontainersgo.RunContainerAndStopOnCleanup(
		ctx,
		&testing.T{},
		wiremocktestcontainersgo.WithImage("docker.io/wiremock/wiremock:3.9.1"),
	)
	if err != nil {
		fmt.Printf("Failed to start WireMock container: %v\n", err)
		os.Exit(1)
	}

	// Store global references
	WireMockContainer = container

	// Try to get the base URL using the standard method first
	baseURL, err := container.Endpoint(ctx, "")
	if err == nil {
		// Standard method worked (running outside DinD)
		// This uses the mapped port (e.g., localhost:59553)
		WireMockBaseURL = "http://" + baseURL
		WireMockClient = container.Client
	} else {
		// Standard method failed, use internal IP fallback (DinD environment)
		fmt.Printf("Standard endpoint resolution failed, using internal IP fallback: %v\n", err)

		inspect, err := container.Inspect(ctx)
		if err != nil {
			fmt.Printf("Failed to inspect WireMock container: %v\n", err)
			os.Exit(1)
		}

		// Find the IP address from the container's networks
		var containerIP string
		for _, network := range inspect.NetworkSettings.Networks {
			if network.IPAddress != "" {
				containerIP = network.IPAddress
				break
			}
		}

		if containerIP == "" {
			fmt.Printf("Failed to get WireMock container IP address\n")
			os.Exit(1)
		}

		// In DinD, use the internal port directly (8080 for WireMock HTTP)
		// Don't use the mapped port since it doesn't exist in this environment
		WireMockBaseURL = fmt.Sprintf("http://%s:8080", containerIP)

		// The container.Client was created with a bad URL, so we need a new one
		WireMockClient = gowiremock.NewClient(WireMockBaseURL)
	}

	fmt.Printf("WireMock available at: %s\n", WireMockBaseURL)

	// Run all tests
	code := m.Run()

	// Cleanup
	if WireMockContainer != nil {
		WireMockContainer.Terminate(ctx)
	}

	// Exit with the same code as the tests
	os.Exit(code)
}

func TestPhoneNumberManagementRetrieveNumberListWithWireMock(
	t *testing.T,
) {
	// wiremock client and server initialized in shared main_test.go
	defer WireMockClient.Reset()
	stub := gowiremock.Get(gowiremock.URLPathTemplate("/v2/phone-numbers")).WillReturnResponse(
		gowiremock.NewResponse().WithJSONBody(
			[]interface{}{map[string]interface{}{"provider": "twilio", "phone_number": "+11234567890", "label": "Customer Support Line", "inbound": true, "outbound": true, "associated_pipeline": map[string]interface{}{"pipeline_id": "pipeline_0987654321fedcba", "pipeline_name": "Customer Service"}, "inbound_config": map[string]interface{}{"key": "value"}, "outbound_config": map[string]interface{}{"key": "value"}}, map[string]interface{}{"provider": "byo", "phone_number": "+19876543210", "label": "Sales", "inbound": false, "outbound": true, "associated_pipeline": map[string]interface{}{"pipeline_id": "pipeline_id", "pipeline_name": "pipeline_name"}, "inbound_config": map[string]interface{}{"key": "value"}, "outbound_config": map[string]interface{}{"key": "value"}}},
		).WithStatus(http.StatusOK),
	)
	err := WireMockClient.StubFor(stub)
	require.NoError(t, err, "Failed to create WireMock stub")

	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.PhoneNumberManagement.RetrieveNumberList(
		context.TODO(),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	ok, countErr := WireMockClient.Verify(stub.Request(), 1)
	require.NoError(t, countErr, "Failed to verify WireMock request was matched")
	require.True(t, ok, "WireMock request was not matched")
}

func TestPhoneNumberManagementImportNumberWithWireMock(
	t *testing.T,
) {
	// wiremock client and server initialized in shared main_test.go
	defer WireMockClient.Reset()
	stub := gowiremock.Post(gowiremock.URLPathTemplate("/v2/phone-numbers")).WithBodyPattern(gowiremock.MatchesJsonSchema(`{
                    "$schema": "https://json-schema.org/draft/2020-12/schema",
                    "type": "object",
                    "required": ["provider", "phone_number", "label", "inbound_config", "outbound_config"],
                    "properties": {
                        "provider": {"type": "string"}, "phone_number": {"type": "string"}, "label": {"type": "string"}, "inbound_config": {"type": "object"}, "outbound_config": {"type": "object"}
                    },
                    "additionalProperties": true
                }`, "V202012")).WillReturnResponse(
		gowiremock.NewResponse().WithJSONBody(
			map[string]interface{}{"phone_number": "+11234567890", "label": "Customer Support Line", "provider": "byo", "inbound": true, "outbound": true, "associated_pipeline": map[string]interface{}{"pipeline_id": "pipeline_id", "pipeline_name": "pipeline_name"}},
		).WithStatus(http.StatusOK),
	)
	err := WireMockClient.StubFor(stub)
	require.NoError(t, err, "Failed to create WireMock stub")

	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.ImportNumberRequest{
		Provider:    Agora.ImportNumberRequestProviderByo,
		PhoneNumber: "+19876543210",
		Label:       "Sales Hotline",
		Inbound: Agora.Bool(
			true,
		),
		Outbound: Agora.Bool(
			true,
		),
		InboundConfig: &Agora.ImportNumberRequestInboundConfig{
			AllowedAddresses: []string{
				"112.126.15.64/27",
			},
		},
		OutboundConfig: &Agora.ImportNumberRequestOutboundConfig{
			Address: Agora.String(
				"xxx:xxx@sip.example.com",
			),
			Transport: Agora.String(
				"tls",
			),
		},
	}
	_, invocationErr := client.PhoneNumberManagement.ImportNumber(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	ok, countErr := WireMockClient.Verify(stub.Request(), 1)
	require.NoError(t, countErr, "Failed to verify WireMock request was matched")
	require.True(t, ok, "WireMock request was not matched")
}

func TestPhoneNumberManagementRetrieveNumberInformationWithWireMock(
	t *testing.T,
) {
	// wiremock client and server initialized in shared main_test.go
	defer WireMockClient.Reset()
	stub := gowiremock.Get(gowiremock.URLPathTemplate("/v2/phone-numbers/{phone_number}")).WithPathParam(
		"phone_number",
		gowiremock.Matching("phone_number"),
	).WillReturnResponse(
		gowiremock.NewResponse().WithJSONBody(
			map[string]interface{}{"provider": "byo", "phone_number": "+11234567890", "label": "Customer Support Line", "inbound": true, "outbound": true, "associated_pipeline": map[string]interface{}{"pipeline_id": "pipeline_id", "pipeline_name": "pipeline_name"}, "inbound_config": map[string]interface{}{"key": "value"}, "outbound_config": map[string]interface{}{"key": "value"}},
		).WithStatus(http.StatusOK),
	)
	err := WireMockClient.StubFor(stub)
	require.NoError(t, err, "Failed to create WireMock stub")

	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.PhoneNumberManagement.RetrieveNumberInformation(
		context.TODO(),
		"phone_number",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	ok, countErr := WireMockClient.Verify(stub.Request(), 1)
	require.NoError(t, countErr, "Failed to verify WireMock request was matched")
	require.True(t, ok, "WireMock request was not matched")
}

func TestPhoneNumberManagementDeleteNumberWithWireMock(
	t *testing.T,
) {
	// wiremock client and server initialized in shared main_test.go
	defer WireMockClient.Reset()
	stub := gowiremock.Delete(gowiremock.URLPathTemplate("/v2/phone-numbers/{phone_number}")).WithPathParam(
		"phone_number",
		gowiremock.Matching("phone_number"),
	).WillReturnResponse(
		gowiremock.NewResponse().WithJSONBody(
			map[string]interface{}{},
		).WithStatus(http.StatusOK),
	)
	err := WireMockClient.StubFor(stub)
	require.NoError(t, err, "Failed to create WireMock stub")

	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	invocationErr := client.PhoneNumberManagement.DeleteNumber(
		context.TODO(),
		"phone_number",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	ok, countErr := WireMockClient.Verify(stub.Request(), 1)
	require.NoError(t, countErr, "Failed to verify WireMock request was matched")
	require.True(t, ok, "WireMock request was not matched")
}

func TestPhoneNumberManagementUpdateNumberConfigurationWithWireMock(
	t *testing.T,
) {
	// wiremock client and server initialized in shared main_test.go
	defer WireMockClient.Reset()
	stub := gowiremock.Patch(gowiremock.URLPathTemplate("/v2/phone-numbers/{phone_number}")).WithPathParam(
		"phone_number",
		gowiremock.Matching("phone_number"),
	).WithBodyPattern(gowiremock.MatchesJsonSchema(`{
                    "$schema": "https://json-schema.org/draft/2020-12/schema",
                    "type": "object",
                    "required": [],
                    "properties": {
                        
                    },
                    "additionalProperties": true
                }`, "V202012")).WillReturnResponse(
		gowiremock.NewResponse().WithJSONBody(
			map[string]interface{}{"provider": "byo", "phone_number": "+11234567890", "label": "Customer Support Line", "inbound": true, "outbound": true, "associated_pipeline": map[string]interface{}{"pipeline_id": "pipeline_id_12345", "pipeline_name": "New Support Bot"}, "inbound_config": map[string]interface{}{"key": "value"}, "outbound_config": map[string]interface{}{"key": "value"}},
		).WithStatus(http.StatusOK),
	)
	err := WireMockClient.StubFor(stub)
	require.NoError(t, err, "Failed to create WireMock stub")

	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.UpdateNumberConfigurationRequest{
		InboundConfig: &Agora.UpdateNumberConfigurationRequestInboundConfig{
			PipelineID: Agora.String(
				"xxxxx",
			),
		},
		OutboundConfig: &Agora.UpdateNumberConfigurationRequestOutboundConfig{
			PipelineID: Agora.String(
				"xxxxx",
			),
		},
	}
	_, invocationErr := client.PhoneNumberManagement.UpdateNumberConfiguration(
		context.TODO(),
		"phone_number",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	ok, countErr := WireMockClient.Verify(stub.Request(), 1)
	require.NoError(t, countErr, "Failed to verify WireMock request was matched")
	require.True(t, ok, "WireMock request was not matched")
}
