// Code generated by Fern. DO NOT EDIT.

package agent_management_test

import (
	context "context"
	fmt "fmt"
	agoraiogosdk "github.com/fern-demo/agoraio-go-sdk"
	client "github.com/fern-demo/agoraio-go-sdk/client"
	option "github.com/fern-demo/agoraio-go-sdk/option"
	require "github.com/stretchr/testify/require"
	gowiremock "github.com/wiremock/go-wiremock"
	wiremocktestcontainersgo "github.com/wiremock/wiremock-testcontainers-go"
	http "net/http"
	os "os"
	testing "testing"
)

// TestMain sets up shared test fixtures for all tests in this package// Global test fixtures
var (
	WireMockContainer *wiremocktestcontainersgo.WireMockContainer
	WireMockBaseURL   string
	WireMockClient    *gowiremock.Client
)

// TestMain sets up shared test fixtures for all tests in this package
func TestMain(m *testing.M) {
	// Setup shared WireMock container
	ctx := context.Background()
	container, err := wiremocktestcontainersgo.RunContainerAndStopOnCleanup(
		ctx,
		&testing.T{},
		wiremocktestcontainersgo.WithImage("docker.io/wiremock/wiremock:3.9.1"),
	)
	if err != nil {
		fmt.Printf("Failed to start WireMock container: %v\n", err)
		os.Exit(1)
	}

	// Store global references
	WireMockContainer = container

	// Try to get the base URL using the standard method first
	baseURL, err := container.Endpoint(ctx, "")
	if err == nil {
		// Standard method worked (running outside DinD)
		// This uses the mapped port (e.g., localhost:59553)
		WireMockBaseURL = "http://" + baseURL
		WireMockClient = container.Client
	} else {
		// Standard method failed, use internal IP fallback (DinD environment)
		fmt.Printf("Standard endpoint resolution failed, using internal IP fallback: %v\n", err)

		inspect, err := container.Inspect(ctx)
		if err != nil {
			fmt.Printf("Failed to inspect WireMock container: %v\n", err)
			os.Exit(1)
		}

		// Find the IP address from the container's networks
		var containerIP string
		for _, network := range inspect.NetworkSettings.Networks {
			if network.IPAddress != "" {
				containerIP = network.IPAddress
				break
			}
		}

		if containerIP == "" {
			fmt.Printf("Failed to get WireMock container IP address\n")
			os.Exit(1)
		}

		// In DinD, use the internal port directly (8080 for WireMock HTTP)
		// Don't use the mapped port since it doesn't exist in this environment
		WireMockBaseURL = fmt.Sprintf("http://%s:8080", containerIP)

		// The container.Client was created with a bad URL, so we need a new one
		WireMockClient = gowiremock.NewClient(WireMockBaseURL)
	}

	fmt.Printf("WireMock available at: %s\n", WireMockBaseURL)

	// Run all tests
	code := m.Run()

	// Cleanup
	if WireMockContainer != nil {
		WireMockContainer.Terminate(ctx)
	}

	// Exit with the same code as the tests
	os.Exit(code)
}

func TestAgentManagementStartAgentWithWireMock(
	t *testing.T,
) {
	// wiremock client and server initialized in shared main_test.go
	defer WireMockClient.Reset()
	stub := gowiremock.Post(gowiremock.URLPathTemplate("/v2/projects/{appid}/join")).WithPathParam(
		"appid",
		gowiremock.Matching("appid"),
	).WithBodyPattern(gowiremock.MatchesJsonSchema(`{
                    "$schema": "https://json-schema.org/draft/2020-12/schema",
                    "type": "object",
                    "required": ["name", "properties"],
                    "properties": {
                        "name": {"type": "string"}, "properties": {"type": "object"}
                    },
                    "additionalProperties": true
                }`, "V202012")).WillReturnResponse(
		gowiremock.NewResponse().WithJSONBody(
			map[string]interface{}{"agent_id": "1NT29X10YHxxxxxWJOXLYHNYB", "create_ts": 1737111452, "status": "RUNNING"},
		).WithStatus(http.StatusOK),
	)
	err := WireMockClient.StubFor(stub)
	require.NoError(t, err, "Failed to create WireMock stub")

	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.StartAgentRequest{
		Name: "unique_name",
		Properties: &Agora.StartAgentRequestProperties{
			Channel:     "channel_name",
			Token:       "token",
			AgentRtcUID: "1001",
			RemoteRtcUIDs: []string{
				"1002",
			},
			IdleTimeout: Agora.Int(
				120,
			),
			AdvancedFeatures: &Agora.StartAgentRequestPropertiesAdvancedFeatures{
				EnableAivad: Agora.Bool(
					true,
				),
			},
			Asr: &Agora.StartAgentRequestPropertiesAsr{
				Language: Agora.String(
					"en-US",
				),
			},
			Tts: &Agora.StartAgentRequestPropertiesTts{
				Vendor: Agora.StartAgentRequestPropertiesTtsVendorMicrosoft,
				Params: map[string]any{
					"key":        "<your_tts_api_key>",
					"region":     "eastus",
					"voice_name": "en-US-AndrewMultilingualNeural",
				},
			},
			Llm: &Agora.StartAgentRequestPropertiesLlm{
				URL: "https://api.openai.com/v1/chat/completions",
				APIKey: Agora.String(
					"<your_llm_key>",
				),
				SystemMessages: []map[string]any{
					map[string]any{
						"role":    "system",
						"content": "You are a helpful chatbot.",
					},
				},
				Params: map[string]any{
					"model": "gpt-4o-mini",
				},
				MaxHistory: Agora.Int(
					32,
				),
				GreetingMessage: Agora.String(
					"Hello, how can I assist you today?",
				),
				FailureMessage: Agora.String(
					"Please hold on a second.",
				),
			},
		},
	}
	_, invocationErr := client.AgentManagement.StartAgent(
		context.TODO(),
		"appid",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	ok, countErr := WireMockClient.Verify(stub.Request(), 1)
	require.NoError(t, countErr, "Failed to verify WireMock request was matched")
	require.True(t, ok, "WireMock request was not matched")
}

func TestAgentManagementListAgentsWithWireMock(
	t *testing.T,
) {
	// wiremock client and server initialized in shared main_test.go
	defer WireMockClient.Reset()
	stub := gowiremock.Get(gowiremock.URLPathTemplate("/v2/projects/{appid}/agents")).WithPathParam(
		"appid",
		gowiremock.Matching("appid"),
	).WillReturnResponse(
		gowiremock.NewResponse().WithJSONBody(
			map[string]interface{}{"data": map[string]interface{}{"count": 1, "list": []interface{}{map[string]interface{}{"start_ts": 1735035893, "status": "RUNNING", "agent_id": "1234567890ABCDE1CVGZNU80BEIN56XF"}}}, "meta": map[string]interface{}{"cursor": "", "total": 1}, "status": "ok"},
		).WithStatus(http.StatusOK),
	)
	err := WireMockClient.StubFor(stub)
	require.NoError(t, err, "Failed to create WireMock stub")

	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.ListAgentsRequest{
		Channel: Agora.String(
			"channel",
		),
		FromTime: Agora.Float64(
			1.1,
		),
		ToTime: Agora.Float64(
			1.1,
		),
		State: Agora.ListAgentsRequestStateZero.Ptr(),
		Limit: Agora.Int(
			1,
		),
		Cursor: Agora.String(
			"cursor",
		),
	}
	_, invocationErr := client.AgentManagement.ListAgents(
		context.TODO(),
		"appid",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	ok, countErr := WireMockClient.Verify(stub.Request(), 1)
	require.NoError(t, countErr, "Failed to verify WireMock request was matched")
	require.True(t, ok, "WireMock request was not matched")
}

func TestAgentManagementQueryAgentStatusWithWireMock(
	t *testing.T,
) {
	// wiremock client and server initialized in shared main_test.go
	defer WireMockClient.Reset()
	stub := gowiremock.Get(gowiremock.URLPathTemplate("/v2/projects/{appid}/agents/{agentId}")).WithPathParam(
		"appid",
		gowiremock.Matching("appid"),
	).WithPathParam(
		"agentId",
		gowiremock.Matching("agentId"),
	).WillReturnResponse(
		gowiremock.NewResponse().WithJSONBody(
			map[string]interface{}{"message": "agent exits with reason: xxxx", "start_ts": 1735035893, "stop_ts": 1735035900, "status": "FAILED", "agent_id": "1NT29X11GQSxxxxxNU80BEIN56XF"},
		).WithStatus(http.StatusOK),
	)
	err := WireMockClient.StubFor(stub)
	require.NoError(t, err, "Failed to create WireMock stub")

	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.AgentManagement.QueryAgentStatus(
		context.TODO(),
		"appid",
		"agentId",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	ok, countErr := WireMockClient.Verify(stub.Request(), 1)
	require.NoError(t, countErr, "Failed to verify WireMock request was matched")
	require.True(t, ok, "WireMock request was not matched")
}

func TestAgentManagementGetAgentHistoryWithWireMock(
	t *testing.T,
) {
	// wiremock client and server initialized in shared main_test.go
	defer WireMockClient.Reset()
	stub := gowiremock.Get(gowiremock.URLPathTemplate("/v2/projects/{appid}/agents/{agentId}/history")).WithPathParam(
		"appid",
		gowiremock.Matching("appid"),
	).WithPathParam(
		"agentId",
		gowiremock.Matching("agentId"),
	).WillReturnResponse(
		gowiremock.NewResponse().WithJSONBody(
			map[string]interface{}{"agent_id": "xxxx", "start_ts": 123, "status": "RUNNING", "contents": []interface{}{map[string]interface{}{"role": "user", "content": "hello."}, map[string]interface{}{"role": "assistant", "content": "hi, how can I help you?"}}},
		).WithStatus(http.StatusOK),
	)
	err := WireMockClient.StubFor(stub)
	require.NoError(t, err, "Failed to create WireMock stub")

	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.AgentManagement.GetAgentHistory(
		context.TODO(),
		"appid",
		"agentId",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	ok, countErr := WireMockClient.Verify(stub.Request(), 1)
	require.NoError(t, countErr, "Failed to verify WireMock request was matched")
	require.True(t, ok, "WireMock request was not matched")
}

func TestAgentManagementStopAgentWithWireMock(
	t *testing.T,
) {
	// wiremock client and server initialized in shared main_test.go
	defer WireMockClient.Reset()
	stub := gowiremock.Post(gowiremock.URLPathTemplate("/v2/projects/{appid}/agents/{agentId}/leave")).WithPathParam(
		"appid",
		gowiremock.Matching("appid"),
	).WithPathParam(
		"agentId",
		gowiremock.Matching("agentId"),
	).WillReturnResponse(
		gowiremock.NewResponse().WithJSONBody(
			map[string]interface{}{},
		).WithStatus(http.StatusOK),
	)
	err := WireMockClient.StubFor(stub)
	require.NoError(t, err, "Failed to create WireMock stub")

	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	invocationErr := client.AgentManagement.StopAgent(
		context.TODO(),
		"appid",
		"agentId",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	ok, countErr := WireMockClient.Verify(stub.Request(), 1)
	require.NoError(t, countErr, "Failed to verify WireMock request was matched")
	require.True(t, ok, "WireMock request was not matched")
}

func TestAgentManagementUpdateAgentWithWireMock(
	t *testing.T,
) {
	// wiremock client and server initialized in shared main_test.go
	defer WireMockClient.Reset()
	stub := gowiremock.Post(gowiremock.URLPathTemplate("/v2/projects/{appid}/agents/{agentId}/update")).WithPathParam(
		"appid",
		gowiremock.Matching("appid"),
	).WithPathParam(
		"agentId",
		gowiremock.Matching("agentId"),
	).WithBodyPattern(gowiremock.MatchesJsonSchema(`{
                    "$schema": "https://json-schema.org/draft/2020-12/schema",
                    "type": "object",
                    "required": [],
                    "properties": {
                        
                    },
                    "additionalProperties": true
                }`, "V202012")).WillReturnResponse(
		gowiremock.NewResponse().WithJSONBody(
			map[string]interface{}{"agent_id": "1NT29X10YHxxxxxWJOXLYHNYB", "create_ts": 1737123456, "status": "RUNNING"},
		).WithStatus(http.StatusOK),
	)
	err := WireMockClient.StubFor(stub)
	require.NoError(t, err, "Failed to create WireMock stub")

	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.UpdateAgentRequest{
		Properties: &Agora.UpdateAgentRequestProperties{
			Token: Agora.String(
				"007eJxTYxxxxxxxxxxIaHMLAAAA0ex66",
			),
			Llm: &Agora.UpdateAgentRequestPropertiesLlm{
				SystemMessages: []map[string]any{
					map[string]any{
						"role":    "system",
						"content": "You are a helpful assistant. xxx",
					},
					map[string]any{
						"role":    "system",
						"content": "Previously, user has talked about their favorite hobbies with some key topics: xxx",
					},
				},
				Params: map[string]any{
					"model":     "abab6.5s-chat",
					"max_token": 1024,
				},
			},
		},
	}
	_, invocationErr := client.AgentManagement.UpdateAgent(
		context.TODO(),
		"appid",
		"agentId",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	ok, countErr := WireMockClient.Verify(stub.Request(), 1)
	require.NoError(t, countErr, "Failed to verify WireMock request was matched")
	require.True(t, ok, "WireMock request was not matched")
}

func TestAgentManagementAgentSpeakWithWireMock(
	t *testing.T,
) {
	// wiremock client and server initialized in shared main_test.go
	defer WireMockClient.Reset()
	stub := gowiremock.Post(gowiremock.URLPathTemplate("/v2/projects/{appid}/agents/{agentId}/speak")).WithPathParam(
		"appid",
		gowiremock.Matching("appid"),
	).WithPathParam(
		"agentId",
		gowiremock.Matching("agentId"),
	).WithBodyPattern(gowiremock.MatchesJsonSchema(`{
                    "$schema": "https://json-schema.org/draft/2020-12/schema",
                    "type": "object",
                    "required": ["text"],
                    "properties": {
                        "text": {"type": "string"}
                    },
                    "additionalProperties": true
                }`, "V202012")).WillReturnResponse(
		gowiremock.NewResponse().WithJSONBody(
			map[string]interface{}{"agent_id": "1NT29XxxxxxxxxELWEHC8OS", "channel": "test_channel", "start_ts": 1744877089},
		).WithStatus(http.StatusOK),
	)
	err := WireMockClient.StubFor(stub)
	require.NoError(t, err, "Failed to create WireMock stub")

	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.AgentSpeakRequest{
		Text:     "Sorry, the conversation content is not compliant.",
		Priority: Agora.AgentSpeakRequestPriorityInterrupt.Ptr(),
		Interruptable: Agora.Bool(
			false,
		),
	}
	_, invocationErr := client.AgentManagement.AgentSpeak(
		context.TODO(),
		"appid",
		"agentId",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	ok, countErr := WireMockClient.Verify(stub.Request(), 1)
	require.NoError(t, countErr, "Failed to verify WireMock request was matched")
	require.True(t, ok, "WireMock request was not matched")
}

func TestAgentManagementAgentInterruptWithWireMock(
	t *testing.T,
) {
	// wiremock client and server initialized in shared main_test.go
	defer WireMockClient.Reset()
	stub := gowiremock.Post(gowiremock.URLPathTemplate("/v2/projects/{appid}/agents/{agentId}/interrupt")).WithPathParam(
		"appid",
		gowiremock.Matching("appid"),
	).WithPathParam(
		"agentId",
		gowiremock.Matching("agentId"),
	).WithBodyPattern(gowiremock.MatchesJsonSchema(`{
                    "$schema": "https://json-schema.org/draft/2020-12/schema",
                    "type": "object",
                    "required": [],
                    "properties": {
                        
                    },
                    "additionalProperties": true
                }`, "V202012")).WillReturnResponse(
		gowiremock.NewResponse().WithJSONBody(
			map[string]interface{}{"agent_id": "1NT29XxxxxxxxxELWEHC8OS", "channel": "test_channel", "start_ts": 1744877089},
		).WithStatus(http.StatusOK),
	)
	err := WireMockClient.StubFor(stub)
	require.NoError(t, err, "Failed to create WireMock stub")

	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.AgentInterruptRequest{}
	_, invocationErr := client.AgentManagement.AgentInterrupt(
		context.TODO(),
		"appid",
		"agentId",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	ok, countErr := WireMockClient.Verify(stub.Request(), 1)
	require.NoError(t, countErr, "Failed to verify WireMock request was matched")
	require.True(t, ok, "WireMock request was not matched")
}
