// Code generated by Fern. DO NOT EDIT.

package agent_management_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	Agora "github.com/fern-demo/agoraio-go-sdk/v505"
	client "github.com/fern-demo/agoraio-go-sdk/v505/client"
	option "github.com/fern-demo/agoraio-go-sdk/v505/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func ResetWireMockRequests(
	t *testing.T,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	_, err := http.Post(WiremockAdminURL+"/requests/reset", "application/json", nil)
	require.NoError(t, err)
}

func VerifyRequestCount(
	t *testing.T,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`"}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestAgentManagementStartWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.StartAgentManagementRequest{
		Appid: "appid",
		Name:  "unique_name",
		Properties: &Agora.StartAgentManagementRequestProperties{
			Channel:     "channel_name",
			Token:       "token",
			AgentRtcUID: "1001",
			RemoteRtcUIDs: []string{
				"1002",
			},
			IdleTimeout: Agora.Int(
				120,
			),
			AdvancedFeatures: &Agora.StartAgentManagementRequestPropertiesAdvancedFeatures{
				EnableAivad: Agora.Bool(
					true,
				),
			},
			Asr: &Agora.StartAgentManagementRequestPropertiesAsr{
				Language: Agora.String(
					"en-US",
				),
			},
			Tts: &Agora.StartAgentManagementRequestPropertiesTts{
				Vendor: Agora.StartAgentManagementRequestPropertiesTtsVendorMicrosoft,
				Params: map[string]any{
					"key":        "<your_tts_api_key>",
					"region":     "eastus",
					"voice_name": "en-US-AndrewMultilingualNeural",
				},
			},
			Llm: &Agora.StartAgentManagementRequestPropertiesLlm{
				URL: "https://api.openai.com/v1/chat/completions",
				APIKey: Agora.String(
					"<your_llm_key>",
				),
				SystemMessages: []map[string]any{
					map[string]any{
						"role":    "system",
						"content": "You are a helpful chatbot.",
					},
				},
				Params: map[string]any{
					"model": "gpt-4o-mini",
				},
				MaxHistory: Agora.Int(
					32,
				),
				GreetingMessage: Agora.String(
					"Hello, how can I assist you today?",
				),
				FailureMessage: Agora.String(
					"Please hold on a second.",
				),
			},
		},
	}
	_, invocationErr := client.AgentManagement.Start(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/projects/appid/join", nil, 1)
}

func TestAgentManagementListWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.ListAgentManagementRequest{
		Appid: "appid",
	}
	_, invocationErr := client.AgentManagement.List(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/projects/appid/agents", nil, 1)
}

func TestAgentManagementGetWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.GetAgentManagementRequest{
		Appid:   "appid",
		AgentID: "agentId",
	}
	_, invocationErr := client.AgentManagement.Get(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/projects/appid/agents/agentId", nil, 1)
}

func TestAgentManagementGetHistoryWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.GetHistoryAgentManagementRequest{
		Appid:   "appid",
		AgentID: "agentId",
	}
	_, invocationErr := client.AgentManagement.GetHistory(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/projects/appid/agents/agentId/history", nil, 1)
}

func TestAgentManagementStopWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.StopAgentManagementRequest{
		Appid:   "appid",
		AgentID: "agentId",
	}
	invocationErr := client.AgentManagement.Stop(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/projects/appid/agents/agentId/leave", nil, 1)
}

func TestAgentManagementUpdateWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.UpdateAgentManagementRequest{
		Appid:   "appid",
		AgentID: "agentId",
		Properties: &Agora.UpdateAgentManagementRequestProperties{
			Token: Agora.String(
				"007eJxTYxxxxxxxxxxIaHMLAAAA0ex66",
			),
			Llm: &Agora.UpdateAgentManagementRequestPropertiesLlm{
				SystemMessages: []map[string]any{
					map[string]any{
						"role":    "system",
						"content": "You are a helpful assistant. xxx",
					},
					map[string]any{
						"role":    "system",
						"content": "Previously, user has talked about their favorite hobbies with some key topics: xxx",
					},
				},
				Params: map[string]any{
					"model":     "abab6.5s-chat",
					"max_token": 1024,
				},
			},
		},
	}
	_, invocationErr := client.AgentManagement.Update(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/projects/appid/agents/agentId/update", nil, 1)
}

func TestAgentManagementSpeakWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.SpeakAgentManagementRequest{
		Appid:    "appid",
		AgentID:  "agentId",
		Text:     "Sorry, the conversation content is not compliant.",
		Priority: Agora.SpeakAgentManagementRequestPriorityInterrupt.Ptr(),
		Interruptable: Agora.Bool(
			false,
		),
	}
	_, invocationErr := client.AgentManagement.Speak(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/projects/appid/agents/agentId/speak", nil, 1)
}

func TestAgentManagementInterruptWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.InterruptAgentManagementRequest{
		Appid:   "appid",
		AgentID: "agentId",
	}
	_, invocationErr := client.AgentManagement.Interrupt(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/projects/appid/agents/agentId/interrupt", nil, 1)
}
